### ISSUE TITLE
Feature request: Richardson Maturity Model

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#1018]
http://martinfowler.com/articles/richardsonMaturityModel.html

Each json element returned from api contains hypermedia controls, which describe the entity and their associations. Looks like a great thing for sailsjs feature...

> The point of hypermedia controls is that they tell us what we can do next, and the URI of the resource we need to manipulate to do it. Rather than us having to know where to post our appointment request, the hypermedia controls in the response tell us how to do it.

**Comment by gtramontina** [comment]
Then it shouldn't be advertised that it generates REST, given that hypermedia is a constraint in this architecture...

**Comment by Akath19** [comment]
@gtramontina 

Hypermedia isn't a constraint in REST architecture, it's the final level (3) of the Richardson Maturity Model (linked in the first post).

The original REST architecture description by Roy Fielding (http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm) doesn't talk about hypermedia controls and since there is no formal definition of REST yet by the W3C there aren't any specific constraints.

The only place that says that hypermedia controls are an architectural constraint for REST is Wikipedia, and without citations.

**Comment by gtramontina** [comment]
It _is_ a constraint. Richardson's Maturity Model is a _path_ to a RESTful architecture.

From your very own Roy Fielding: http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven
> What needs to be done to make the REST architectural style clear on the notion that hypertext is a constraint?

**Comment by Akath19** [comment]
Reading the blog post you linked, you're right, Roy Fielding does expand on the meaning of hypertext in the REST architecture and Sails doesn't conform to that.

However Sails generates a REST CRUD, just that, I still stand by my original point that generating hypermedia controls automagically should be done by developers, not by the framework, I don't really see how the framework could generate hypermedia links to your method actions unless you wrote the controllers first.

**Comment by gtramontina** [comment]
Agree... It definitely needs business and domain knowledge to make proper use of hypermedia. 

Addressing Roy's question: "Is there some broken manual somewhere that needs to be fixed?", I wouldn't even mention REST, to avoid confusion. And just advertise it as generating CRUD, or even RPC API. :smile:

cc/ @balderdashy

**Comment by elennaro** [comment]
I give my vote for at least HATEOAS implematation of Hypermedia. It's a must have in our days!
