### ISSUE TITLE
Enable Express compression in Sails.js by default

### ISSUE THREAD

**Issue by pierredewilde** [balderdashy/sails#1150]
In `config/express.js` file:

```
module.exports.express = {
    customMiddleware: function (app) {
        var express = require('../node_modules/sails/node_modules/express');
        app.use(express.compress());
    }
};
```

It will speed up Sails.js by compressing all Express responses.

**Comment by mattcodez** [comment]
@pierredewilde Is there a simple way to enable compression only for certain methods? Given the discussion in this thread, off by default on JSON sounds appropriate, so I'd like to enable for a particular method I have. I tried to setup using policies, connection hangs and I'm guessing it's because policy middleware runs before the application method, and I would need this to run after right?

**Comment by pierredewilde** [comment]
Dunno.

**Comment by animedbz16** [comment]
Or you could use the buildProd grunt task and host static assets behind nginx so that your node server doesnt even have to handle serving static assets since if it had to handle serving static assets this means it can't be doing other things that it actually has to do such as handling API requests and interfacing with the database.

Leave static assets to be handled by nginx for production. The buildProd grunt task already handles concatination, minification and uglification of statics assets into a `www` directory which a simple nginx config can point to handle serving those assets and routing all other requests to the backend node server.
