### ISSUE TITLE
After 10x generating model + controller. server not starting.

### ISSUE THREAD

**Issue by ghost** [balderdashy/sails#1401]
Hi, i was trying to create more than 10 controllers and models, but landed with an issue.

When i lift the server Sails.js tels me this:

```
error: Server doesn't seem to be starting.
error: Perhaps something else is already running on port 1337?
```

What i did before:

```
sails generate State
info: Generating model and controller for State...
sails generate State1
info: Generating model and controller for State1...
sails generate State2
info: Generating model and controller for State2...
sails generate State3
info: Generating model and controller for State3...
sails generate State4
info: Generating model and controller for State4...
sails generate State5
info: Generating model and controller for State5...
sails generate State6
info: Generating model and controller for State6...
sails generate State7
info: Generating model and controller for State7...
sails generate State8
info: Generating model and controller for State8...
sails generate State9
info: Generating model and controller for State9...
sails lift
...
error: Server doesn't seem to be starting.
error: Perhaps something else is already running on port 1337?
```

Is there a way to fix it?

Versions:
Sails.js: v0.9.8
Node.js: v0.10.22
Linux: Ubuntu 10.04.4 LTS

**Edit**: Also wanted to mention that the Sails server is **still running** on that port but annoying part is that i get an error everytime i lift sails server.

Laptop specs:
CPU: Intel I7
RAM: 16GB

**Comment by statyan** [comment]
The same to me. I was using sails@0.11 and ugraded to sails@0.12.3 with sails-postgresql@0.11.3. Now sails lift it shows an error in terminal: 
`error: Grunt :: error: Server failed to start.
error: Grunt :: error: (received error: EADDRINUSE)
error: 
error: Troubleshooting tips:
error: 
error:  -> Is something else already running on port 1337 ?
error: 
error:  -> Are you deploying on a platform that requires an explicit hostname, like OpenShift?
error:     (Try setting the `explicitHost` config to the hostname where the server will be accessible.)
error:     (e.g. `mydomain.com` or `183.24.244.42`)`

But server lifted up correctly, it works and processes requests. The only thing - this buzzy message during startup.

**Comment by 2pay** [comment]
Try Fixed:

`$sudo lsof -i:1337`

On Output you will kill pid of node on listing:

`$kill [pid number]`

Start sails again:

`$sails lift

It work for me.

**Comment by saumya04** [comment]
This is the worst support I've ever seen from a framework team. This issue still occurs and repo contributors don't provide any robust and fixed solution.
This issue still not fixed for me.

**Comment by kavuri** [comment]
@saumya04 I don't think you are paying for any service (?) and you need to use a different tone to solicit responses. Moreover, this is an open source project and you are free to contribute solutions or find your own solutions.

**Comment by saumya04** [comment]
@kavuri I know I am not paying for any service, but there many other open-source services available online (just like laravel), and their support is great. I know I've used a wrong tone, but by seeing the upper issue & its responses its although a direct closing of an issue without any solutions.
That's not the response which a framework user expects.

**Comment by sgress454** [comment]
@saumya04 This issue was closed because the original poster stated that the issue, "After 10x generating model + controller. server not starting" was fixed for them.  If you're having this exact issue -- that you're generating ten models and the server doesn't start, but that it starts with nine -- and you can post a link to a repo that we can use to reproduce it, then I'm happy to re-open it.  It sounds, however, like this is not your issue, and that the only similarity is that Sails isn't starting for you.  If that's the case, then please open a _new_ issue with details on how we can reliably reproduce the problem, and we'll look into it.  

Issues are closed when appropriate to keep the queue from getting unmanageable, and we don't often patrol closed issues for new comments (I just happened to luck onto this one).  If you think an issue is closed in error in the future, you can @ mention one of the Sails team to get us to take a look.

**Comment by saumya04** [comment]
@sgress454 Ya, I got your point.
