### ISSUE TITLE
Move to gulp instead of grunt

### ISSUE THREAD

**Issue by BlueHotDog** [balderdashy/sails#1461]
Hey,
All the cool guys are moving to gulp :)

Few reasons to consider gulp vs grunt:
1. i've used it and absolutely love it
2. uses stream and code vs configuration approach, which makes the code much more readable
3. task dependency done correctly
4. faster

I've run a few tests on some of my projects and the results are really great. lines of code reduced and the all this grunt config(ala xml but in json) is gone.

what do you think?

**Comment by gregorypierce** [comment]
Adding my +1 as I'm having to do some funkiness to support gulp with the current config since it is our 'production' approach.

**Comment by mattblang** [comment]
@gregorypierce What funkiness?  We were able to completely strip it pretty easily, just have to make sure and edit the .sailsrc.

**Comment by gregorypierce** [comment]
I used a tool to convert the grunt to gulp and I've had a stream of dependencies grow from it to the point that there was a lot of concern about whether or not this was an astute approach to solving the problem vs just waiting for the framework to support it.

**Comment by VladShcherbin** [comment]
+1

gulp is very needed. currently the only thing stopping the use of sails js for some people.

**Comment by loicsaintroch** [comment]
As I already said on an other issue:

* The Sails asset pipeline is very flexible. Whether you choose Grunt or Gulp or whatever you want, it will work. The Sails team decided to choose Grunt because it was the best tool when Sails was created.
* Don't forget Sails is a back-end framework and the front-end workflow is juste here for convenience.
* The new version of Sails allows you to load custom hook such as the Gulp hook directly from the `node_modules` directory. So, feel free to use community hooks/generators or don't hesitate to create your own and share it with the community.
* If we move from Grunt to Gulp, a lot of applications will be broken.

Then, as we can read on a presentation of the Grunt team about the state of Grunt:
> Grunt, Gulp, Broccoli, they're actually all good options. As long as you're using something, you're ahead of the game!

In my opinion Sails shouldn't take care of the front-end at all but it's pretty convenient for a lot of developers to have something running by default.

Thank you for your comprehension.

**Comment by psi-4ward** [comment]
> In my opinion Sails shouldn't take care of the front-end at all but it's pretty convenient for a lot of developers to have something running by default.

Exactly my opinion. I would strip everything frontend related from sails and build meta-packages like "sails-grunt-mvc" or "sails-gulp-angular". Everytime fetich the huge grunt stack and disable it via .sailsrc is not very nice

**Comment by VladShcherbin** [comment]
ok, so now when you start a sails js project - you get grunt by default, its modules and different configuration files.

is there a flag to not install grunt? for just the backend skeleton app?

**Comment by loicsaintroch** [comment]
You can do `sails new myApp --no-frontend`

**Comment by psi-4ward** [comment]
you only can disable it but npm will fetch grunt

**Comment by VladShcherbin** [comment]
yes, by using the `--no-frontend` some grunt files are not included in the app, but still grunt is present in node_modules and is tightly coupled with generators, etc.

it would be awesome to exclude all the grunt files and let the user use grunt\gulp or any other generators aside from sails js skeleton.

don't you share that idea?

**Comment by loicsaintroch** [comment]
Yes I agree. Indeed, this is what I have done on our own fork of Sails...

**Comment by psi-4ward** [comment]
Is your fork public?
Im planning a fork too to solve issues like this

**Comment by loicsaintroch** [comment]
Yes it is: https://github.com/extensdotio. Still a lot of work to do, it's only a developer preview.

**Comment by VladShcherbin** [comment]
thank you for the info, will try sails and the gulp extensions.

I hope some day, maybe 0.12 or 0.15 this would be easily done out of the box

**Comment by swarthy** [comment]
+1

**Comment by andyhu** [comment]
@loicsaintroch Thanks for the info, extens.io looks very promising, I'm planning to build a CMS system on top of sails, which will borrow some ideas from Drupal and KeystoneJS, I may try to build it with extens.io

**Comment by ItsLeeOwen** [comment]
+1

**Comment by Deminetix** [comment]
+1 

What is the current best way to swap in gulp?

**Comment by ItsLeeOwen** [comment]
There are a few gulp generators out there for sails:  https://www.npmjs.com/package/sails-generate-new-gulp

You can also disable grunt in .sailsrc, and add your own gulp hook to build your own gulp tasks from the ground up.  Something like:
```
.sailsrc
{
  "hooks": {
    "gulp": true,
    "grunt": false
  }
}
```

```
/api/hooks/gulp/index.js
"use strict";
var spawn = require('child_process').spawn,
module.exports = function (sails) {
  return {
    initialize: function (next) {
      if (!sails.config.hooks.gulp) {
        return next()
      }
      var gulp = spawn('gulp', 'lift:'+sails.config.environment, {stdio: 'inherit'})
      gulp.on('exit', function (code) {
        next()
      })
    }
  }
}
```

**Comment by Karnith** [comment]
Oh, those generators are mine! Thanks for reminding me,  I need to update them and ensure they still work with the changes made in Sails...

**Comment by Deminetix** [comment]
Thanks, I gave that generator a whirl and it seemed to work ok but it still installed a bunch of grunt modules.

I ended up using --no-frontend and did the gulp system from scratch as our frontend build system is quite a bit more complex.

**Comment by Karnith** [comment]
I started working on integrating gulp into sails natively. It's still in dev stage, but if anyone wants they can try

npm install -g Karnith/sails

I ripped out grunt and wanted to get gulp working first before I create a switch for sails new and pr the sails dev team with it. :)

**Comment by niallobrien** [comment]
@Karnith How has your progress been?

**Comment by Karnith** [comment]
I got it working,  I changed the name to sails-for-gulp. I haven't had much time to work on it more though... I've been swamped at Microsoft and had a daughter 2 months ago... well my wife did, not me... lol. I plan on picking back up the project here soon, so if anyone wants to help let me know. I was starting on making core revisions to the generators and converting them to machine packs.

**Comment by Adam-Goldman7** [comment]
If I just want to use my own gulp file for front end stuff, how do I got about it?

I don't care much about the generators, I just want a good build/rebuild time when I code.

Is there a documentation anywhere how to do so?

If not I'd be happy to write it with some directions :)

**Comment by Karnith** [comment]
Well first you'don't need to create a hook for gulp, then you'd need to disable grunt in sailsrc. You would then need to recreate any tasks to move assets, images, etc. to the temp folder (or folder of your choice). You can do this all yourself, but generators do all that work for you so that all you need to worry about is coding...

**Comment by Adam-Goldman7** [comment]
I don't understand.

I never tried sailsjs. I don't know where to begin.
what's the flow. where do I put client logic and where server.

Can't find documentation either.

Can someone point me?

Any tutorial or example app?

**Comment by whiskas** [comment]
Hi  Karnith , is sails-generate-new-gulp yet supported?

**Comment by Karnith** [comment]
@Whiskas sails-generate-new-gulp has been deprecated. Use https://github.com/Karnith/machinepack-sailsgulpify it allows you to switch between sails and gulp using a command. It's a better module than sails-generate-new-gulp.

**Comment by Karnith** [comment]
I'm working on an angular machinepack as well.

**Comment by Karnith** [comment]
I abandoned forking sails and adding gulp natively, not because I couldn't get it to work  (I actually did get it to work), but because I didn't want the job of maintaining a fork. Hence the machinepack

**Comment by 1mike12** [comment]
@Karnith thanks for the work you did do though. Not having gulp really bothered me.

**Comment by jordyvandomselaar** [comment]
So, it's 2016 now... Any signs on official gulp support?

**Comment by kevinburkeshyp** [comment]
@jordyvandomselaar the maintainers don't owe you anything and your attitude is unhelpful. It's a free project. If you want it, build it or pay Balderdash - they are a consulting company.

-kevin

**Comment by Karnith** [comment]
wow, people seem on edge these days... @jordyvandomselaar while I don't think you meant any wrong, the discussion of gulp vs grunt with sails has become a sensitive topic these days. I have a project, [machinepack-sailsgulpify](https://github.com/Karnith/machinepack-sailsgulpify) that will add gulp support to sails in the same way they have grunt added. In the past I have questioned the same, if they would support grunt, and although feedback was extremely high for this feature, they decided against this. I even created a fork of sails and added gulp natively, which wasn't hard seeing as gulp is similar to grunt (if memory serves me right, I believe the creators of grunt also created gulp). I since closed that project as I didn't want or have the time to maintain it and sails team wasn't about to. at any rate, I don't believe there will be an official gulp version of sails, but if someone wants to start and maintain one I'd be more than happy to show them how to integrate gulp natively.

**Comment by jordyvandomselaar** [comment]
You're right @Karnith, I didn't mean any wrong. I didn't see anyone talking so I decided to ask about it as I might have missed them adding support for it in any way. I would start and maintain a gulp workflow but I really don't have the time, bummer. As for @kevinburke I know they don't owe me anything, and I never wanted imply such a thing. And again; I would do it myself if only I had the time to do so.

**Comment by kevinburkeshyp** [comment]
Ok - when you start off your comment saying "it's 2016", that's a pretty strong implication you think they're "behind" and you expect something different

-kevin

**Comment by dadleyy** [comment]
@jordyvandomselaar have you tried separating your browser-side code from your server side code? I've worked on a few projects where all the browser side code lives in a completely separate repository; the sails application is strictly used for json/rest api and serves *no* html.

Taking that approach would free you up to use whatever build system you want. It also frees up your platform to release browser-side code and server-side code independently. It works best with single page applications but even with traditional server-side-view-rendered browser applications, the deployment could take compiled browser side code and put it on the server - or better yet push it to a cdn.

I'd actually prefer it if sails came *without* grunt, gulp, a view engine, or anything along those lines. I like my backend code stripped down to routing, orm models and business logic services only.

**Comment by jordyvandomselaar** [comment]
@dadleyy, to be completely honest I thought grunt was doing some back-end stuff aswell. Especially with node I like to separate front & back as it makes some things a bit easier; building an app only needs a front-end rather than having to build another back-end. @kevinburkeshyp It's true that I think using grunt is a little behind, but my opinion should not matter as much. I personally think gulp is better than grunt but you're free to feel different about this. I started my post by saying "it's 2016 now" because I didn't know if they were working on it and I hoped that if they were that it'd be done in 2016.

**Comment by laoshaw** [comment]
why is sails.js staying with grunt still, and isn't connect dependency removed in express4? and what about typescript support?

without these I don't feel sails.js appealing at all these days.

**Comment by andyhu** [comment]
I think now the topic should be something like change to `webpack` insead of `grunt`

**Comment by aalokit** [comment]
I have a yoeman angular fullstack project. I am currently using grunt, now i want to move to gulp. Can anybody help, what is the process to do so..

**Comment by nbkhope** [comment]
So what is Sails going to have by default in the upcoming 1.0 version? It seems like everyone is using webpack these days. I use webpack together with the Sails grunt tasks, but feel like I will be disabling the latter soon.
