### ISSUE TITLE
the form's method put and delete dosen't work

### ISSUE THREAD

**Issue by funkyLover** [balderdashy/sails#1651]
part of routes.js

``` js
'get /user/:id?': {
    controller: 'task',
    action: 'find'
  },

  'put /task/:id': {
    controller: 'task',
    action:'update'
  },

  'delete /user/:id': {
    controller: 'task',
    action: 'destroy'
  }

```

front end test

``` jade
h3 test form method put
form(formmethod='put', action='/task/14')
    label title
    input(type='text', name='title')
    br
    label descp
    input(type='textarea', name='descp')
    br
    button(type='submit') submit

h3 test form method delete
form(formmethod='delete', action='/task/14')
    button(type='submit') submit
```

Whether it's `put` or `delete`,
it will be convert to `get`
`console.log(req)` in server-side
the req.target
`target: { controller: 'task', action: 'find' }`

the req.route
`route: 
   { path: '/task/:id?',
     method: 'get',
     callbacks: [ [Function] ],
     keys: [ [Object] ],
     regexp: /^\/task(?:\/([^\/]+?))?\/?$/i,
     params: [ id: '14' ] }`

**Comment by ravi-ture** [comment]
hi
Following is my config/http.js

<code>
/**
 * HTTP Server Settings
 * (sails.config.http)
 *
 * Configuration for the underlying HTTP server in Sails.
 * Only applies to HTTP requests (not WebSockets)
 *
 * For more information on configuration, check out:
 * http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.http.html
 */

module.exports.http = {

  /****************************************************************************
  *                                                                           *
  * Express middleware to use for every Sails request. To add custom          *
  * middleware to the mix, add a function to the middleware config object and *
  * add its key to the "order" array. The $custom key is reserved for         *
  * backwards-compatibility with Sails v0.9.x apps that use the               *
  * `customMiddleware` config option.                                         *
  *                                                                           *
  ****************************************************************************/

   middleware: {

  /***************************************************************************
  *                                                                          *
  * The order in which middleware should be run for HTTP request. (the Sails *
  * router is invoked by the "router" middleware below.)                     *
  *                                                                          *
  ***************************************************************************/

    order: [
      'startRequestTimer',
      'cookieParser',
      'session',
      'bodyParser',
      'handleBodyParserError',
      'compress',
      'poweredBy',
      '$custom',
      'router',
      'methodOverride',
      'requestLogger',
      'www',
      'favicon',
      '404',
      '500'
    ],

  /****************************************************************************
  *                                                                           *
  * Example custom middleware; logs each request to the console.              *
  *                                                                           *
  ****************************************************************************/

    requestLogger: function (req, res, next) {
        if(
            (req.url.indexOf('/js/') == -1) &&
            (req.url.indexOf('/styles/') == -1) &&
            (req.url.indexOf('/images/') == -1) &&
            (req.url.indexOf('/fonts/') == -1)
          ){
          console.log("Requested :: ", req.method, req.url);
          console.log('Params::', req.allParams())
        }
        return next();
    }

  /***************************************************************************
  *                                                                          *
  * The body parser that will handle incoming multipart HTTP requests. By    *
  * default as of v0.10, Sails uses                                          *
  * [skipper](http://github.com/balderdashy/skipper). See                    *
  * http://www.senchalabs.org/connect/multipart.html for other options.      *
  *                                                                          *
  ***************************************************************************/

    // bodyParser: require('skipper')

  }//,

  /***************************************************************************
  *                                                                          *
  * The number of seconds to cache flat files on disk being served by        *
  * Express static middleware (by default, these files are in `.tmp/public`) *
  *                                                                          *
  * The HTTP static cache is only active in a 'production' environment,      *
  * since that's the only time Express will cache flat-files.                *
  *                                                                          *
  ***************************************************************************/

  // cache: 31557600000
};

</code>

I have included hidden field `<input type="hidden" name="_method" value="PUT"/>`

But still I am not able to hit PUT or DELETE request.

Please suggest if any config setting is missing.
