### ISSUE TITLE
onConnect for socket.io not called

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#1738]
Is there any reason why onConnect is not called? I have a connected client in browser but onConnect in sockets.js was never called.

I am on sails-v10-rc7.

**Comment by oneHappyCanuck** [comment]
Having the same issue with v11; a client subscribing on a 'connect' event doesn't get a callback.  

In my case the client is Ionic based and uses with JWT authentication, and I want the socket connection lifecycle to track the user session lifecycle.  To do so I set autoconnect to false, and after user authentication I call io.sails.connect manually with a JWT token query parameter.  After that I want to receive connect / disconnect events at the client so that I can run post login queries and visually represent the connection status, but there doesn't seem to be any way to get a connect event (not sure about disconnect).  I also want to be able to manually disconnect when the user logs out and manually reconnect when the user logs back in, but after disconnecting manually the socket seems to have been torn down forever and I can no longer call connect? 

Looks to me like this kind of manual connection management is outside the design intent of sails.io. 

Any suggestions on how to meet my goals? Would the lower level websocket api be a better starting point or am I missing something somewhere in the sails api's?
