### ISSUE TITLE
Feature Request: Public actionUtil like service

### ISSUE THREAD

**Issue by mikeg2** [balderdashy/sails#1829]
It's very easy to create a basic REST API in sailsjs without blueprint, just by putting `res.json(...)` in after a `find()` call. 

It's not as simple to add in featured like deep-subscribe or even to securely add in features like `/resource?populate=` or to blacklist values. That's not to say it's incredibly hard, but I've ended up just copying the `actionUtil` class (what Blueprint uses to do this stuff) into a service and tweaking it so it works for non-blueprint APIs.

It makes sense for there to be a built in service that assists with creating full featured APIs even if you don't use blueprint.

**Comment by kevinob11** [comment]
+1

**Comment by rhewitt22** [comment]
+1

**Comment by leejt489** [comment]
+1 I think it's a good feature request.  My solution was to write an ActionUtilityService as a wrapper.  In that service, `var actionUtil = require('../../node_modules/sails/lib/hooks/blueprints/actionUtil')`, and then expose the methods I need.  I use the wrapper because I don't like to have references to file structure within node_module dependencies (maintainers of modules are allowed to change their file hierarchy without breaking their api), and this keeps the reference in one place.

**Comment by jvanalst** [comment]
++
