### ISSUE TITLE
sails-linker modifies views in the source repository?

### ISSUE THREAD

**Issue by simoami** [balderdashy/sails#2007]
It appears that grunt-sails-linker is configured to modify views in the source code as this configuration implies.

```
'sails-linker': {

            devJs: {
                options: {
                    startTag: '<!--SCRIPTS-->',
                    endTag: '<!--SCRIPTS END-->',
                    fileTmpl: '<script src="%s"></script>',
                    appRoot: '.tmp/public'
                },
                files: {
                    '.tmp/public/**/*.html': jsFilesToInject,
                    'views/**/*.html': jsFilesToInject,  <------ here
                    'views/**/*.dot': jsFilesToInject     <------ here
                }
},
```

This is generally not recommended. Code that is versioned will be flagged as modified. If one performs a merge from another branch and wants to test that the app is running before committing the merged code, then this will interfere with the process, since the sails-linker turns views as modified.

**Comment by rishabhmhjn** [comment]
I tried to find a workaround to this issue by copying the `views/**.*.ejs` to `.tmp/views` and updated the `sails-linker` tasks to modify the files in the `.tmp/views/**` and its doing it well.

Now, I wanted to change the `sails.config.paths.views` to `./tmp/views`.
I found 2 problems

1. Adding a `config/paths.js` with the following did not update the `sails.config.paths.views` value

        module.exports.paths = {
          views: '/path/to/app/.tmp/views'
        }

2. I tried to modify the `sails.config.paths.views` value to `.tmp/views` in the `config/bootstrap.js` and it updates the config fine. However, if I open the pages, it still does not select the files in the `.tmp/views` folder even though the logs says otherwise

        silly: Serving view at rel path:  homepage
        silly: View root:  /path/to/app/.tmp/views
        verbose: Rendering view: "homepage" (located @ "/path/to/app/.tmp/views/homepage")
        verbose: • using configured layout:: layout (located @ "/path/to/app/.tmp/views/layout"

BUG?

**Comment by robgrimball** [comment]
While you can remove the linker tags/injection of source files and do it manually yourself, we tend to use the linker even for bringing in scripts for production environment.  Our main problem with this approach was the lack of versioning in sails resources because of use of the linker.  In case someone else is doing the same, but needs versioning of their sails resources brought in by the linker, the following stackoverflow question helped point me in the right direction, particularly the link in the second answer : 

http://naya.com.np/@developer.naya/post/391862c0520b5b5632e99e812749a85b

**Comment by animedbz16** [comment]
I agree with @simoami here. This is an issue @sgress454.

There is no reason why Sails should be configured out of the box to have grunt / sails linker modify the actual source template as it makes is confusing as git sees this as a change and users will likley just commit the file over and over which is unnecessary.

The dynamic linking is important and definitely useful, so I don't think that disabling it all together is a "solution".

Sails should just be a bit smarter to see if someone who has grunt enabled, sails linker should modify the copied files in the .tmp directory as @rishabhmhjn is suggesting. This way the source file doesn't get modified, only the grunt built file is.

Though there is another use case where what if grunt is disabled say for a production server. We use the build/buildProd task to build a www static path. While we have nginx set up to serve out these files statically, I'm not sure if modifying the bootstrap.js file to point to the .tmp directory would work in the case where grunt is disabled entirely and there is no .tmp directory.
