### ISSUE TITLE
loading services from a subdirectory

### ISSUE THREAD

**Issue by aminjam** [balderdashy/sails#2236]
Is there a way to load Sails Services from both the `api/services` and `api/services/subCategory`. I have looked at `node_modules/sails/lib/hooks/moduleloaders/index.js`, and it looks like I can resolve only a single directory `services: path.resolve(config.appPath, 'api/services')`. Is there a way to load from multiple locations?

**Comment by loicsaintroch** [comment]
@sgress454 is working on a `subapps` hooks that loads API and config from `node_modules` or other directories. So, you have two different options: use this hook or override the default `moduleloader`

**Comment by elennaro** [comment]
+1 for this feature

**Comment by marekkalnik** [comment]
+1 from me too. The services directory becomes polluted rapidly and refactoring everything into separate modules is sometimes very time consuming.

**Comment by sgress454** [comment]
The reasons this won't be added to core are:

1. It would break existing apps that already use subfolders in `api/services` to hold shared files, e.g. 
2. It's a little weird to globalize things living in subfolders, because it's not clear what the globalized name should be (this is the same reason we don't load models from subfolders).  

If you're _not_ globalizing the services (i.e. you have `services: false` in `config/globals.js`), then it doesn't really matter if you have them in subfolders, since you'll be `require()`ing them manually anyway.

**Comment by tjwebb** [comment]
> already use subfolders in api/services to hold shared files,
What does this mean?

>  since you'll be require()ing them manually anyway.
You'd load them via `sails.services` namespace, yes?

**Comment by sgress454** [comment]
> already use subfolders in api/services to hold shared files,
> What does this mean? I don't know what a "shared file" is.

Sorry, accidentally cut off my comment--fixed above.  I meant cases where there's a `lib` folder with shared files.

> since you'll be require()ing them manually anyway.
> You'd load them via sails.services namespace, yes?

Yup, forgot about that.  And if `flattenDictionaries` were on, you could probably do something like `sails.services['foo/bar/baz']` to access something in a subdirectory.
