### ISSUE TITLE
pod structure generator option?

### ISSUE THREAD

**Issue by mgenev** [balderdashy/sails#2241]
Hi,
I really like sails, but I noticed that for big projects using the generator will quickly get out of hand as it starts putting everything in the same folder. The same thing became an issue with Ember and there is now an alternative convention structure called pods. You can check it here: http://www.ember-cli.com/  - search for 'pod structure'.

Is there a way to generate something like that with sails and if not,  would you guys consider it?

**Comment by kriswill** [comment]
I concur.  I feel like a pod structure would more closely resemble the conventions of an API.  consider the following folder/file structure:

```
api/
  users/
    model.js
    http/
      get/
        index.js
        -id.js
      post/
        index.js
        register.js
      patch.js
```

In this example, `users` would represent the routing structure for a resource.  The model mapping would be defined in model.js, and each allowed http verb would get a folder with the verb supported and an index.js for the default dispatch, or a hyphenated id specifier for parameter mapped in the corresponding path, or simply the `[verb].js` in that position.  Each javascript file could implement an interface that exports usage information, data validation requirements, and policy declarations that could be used to generate documentation for the endpoint, think swagger or generating admin UIs, etc.

Similarly, you could define a non-resource route using a similar technique.  for example:

```
api/
  time-http-get.js
```

In this case, we might not use a full directory structure, since there is a simple resource that has no other operations, and maps to `HTTP GET /time`

Thoughts?

**Comment by mgenev** [comment]
+1 for this proposal

**Comment by Globegitter** [comment]
:+1: On this proposal. Whenever I get some time over the next few weeks/months I'll try to take a stab on it.

**Comment by loicsaintroch** [comment]
I like the idea, could be great. Do you mind help us on this feature by writing a PR @mgenev @kriswill @Globegitter? I'll be happy to see it in Sails. Thank you for your help, awesome!

**Comment by Jan-Jan** [comment]
:+1:

**Comment by Globegitter** [comment]
There is now a quite interesting project which supports a somewhat similar idea to the proposed POD structure: https://github.com/taitulism/Bootstruct

Could possibly be used as a basis for a sails implementation.

**Comment by Jan-Jan** [comment]
I use sane, ie, sails and ember. If these two mirror each other in pod structure, that would be fantastic.

@Globegitter looks interesting.
