### ISSUE TITLE
A hook (`orm`) failed to load!

### ISSUE THREAD

**Issue by nosensezzz** [balderdashy/sails#2267]
I have sails-mongo installed on my sails.js , and I set my connection and model to mongodb, but when I run the project, it report this error.

Should I need to activate mongodb before sails lift? if do , how can I start my mongodb service, I type "mongod" , it's not such commend.

**Comment by loicsaintroch** [comment]
Thank you for your answer @konstantinzolotarev.

**Comment by sridhar47** [comment]
@konstantinzolotarev 
Yes i want still showing same error
and its showing failed to connect [example.db:27017]] that db i enter in /etc/hosts

**Comment by konstantinzolotarev** [comment]
@sridhar47 is it working if you set it `localhost:1337` or `ip.address:1337` ?

**Comment by sridhar47** [comment]
@konstantinzolotarev 
thanks for your answer i got solution

**Comment by theambitious** [comment]
I ran into what might be the same problem. My issue was caused because Sails requires validating connections listed in connections.js even if they aren't explicitly used in the context of the environment. I wrote up the details and solution to this issue here: http://theambitious.com/index.php/2015/07/31/sailsjs-a-hook-orm-failed-to-load/

**Comment by particlebanana** [comment]
@theambitious you can define those connections in the `config/env/development.js`, `config/env/test.js` or `config/env/production.js` files so that they only spin up pools for the correct environments.

**Comment by theambitious** [comment]
Thanks. Will update article with your feedback and credit.

**Comment by tjwebb** [comment]
@theambitious thanks for writing about Sails! The docs on environment-specific configs are here: http://sailsjs.org/documentation/concepts/configuration#?environmentspecific-files-config-env

It's the framework's assumption that if you define a connection, Sails should try to connect to it, because if it's defined then Sails assumes that you want to use it for something, even if no models have that connection set.

**Comment by theambitious** [comment]
@tjwebb, @particlebanana  - I have updated the blog post. I believe the confusion stems from the fact that connections that come out of the box, including a MySQL connection, are defined yet ignored by sails on lift. 

It appears that only when a connection is defined in a Waterline model, all other connections that use the same adapter are then checked on lift. I thought maybe validation of a connection occurs once the adapter npm module is installed (sails-mysql, sails-mongo), but after installing the sails-mysql module, it still ignored the default mysql connection. 

To keep consistency and avoid confusion, I recommend commenting out the connections in connections.js by default (maybe leave the disk-based one for quick-start purposes).

Thanks for pointing me to the environment specific configuration docs!
