### ISSUE TITLE
Completely disabling sessions

### ISSUE THREAD

**Issue by lwansbrough** [balderdashy/sails#2273]
Would you guys accept a PR for this? I'm working on using JWTs, and sessions keep getting in the way (need a sails cookie to handshake, etc.) Would the process be reasonably straight forward to accomplish this?

**Comment by r0hitsharma** [comment]
This might be relevant here: http://stackoverflow.com/questions/28015873/disable-some-built-in-functionality-in-sails-js/28017720#28017720

**Comment by loicsaintroch** [comment]
Thank you @RWOverdijk and @r0hitsharma.

**Comment by cburatto** [comment]
Is is possible to disable session (i.e. not storing it on Redis or in memory) but still deal with cookies?

Here's my reasoning:

I am working with JWT and expect it to be used in between tabs in a browser. This means once the user is JWT-authenticated on the initial tab, if he/she tries to access another resource by opening a second tab, this GET request will not have the JWT in it, since there is no way to inject it on a header.

The first thing that comes to mind is storing on localStorage (sessionStorage is not shared between tabs). Still, you would need the new tab to be redirected to an auth endpoint that would download a JS, read the localStorage, inject it on a header and then proceed to the original restricted resource, which would be able to read it and authorize or not.

The first problem is this redirection. The second one is that it is not advisable to store sensitive information on localStorage. Cookies are still somewhat safe (provided you have CSRFtoken) - ore about this here: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/

So my approach is to create a local cookie when the first tab is authenticated (using js cookie - https://github.com/js-cookie/js-cookie ) an store the received JWT in a "access_token" variable. This way, whenever a new tab is opened, the browser sends this improved cookie and the server is able to read the access_token variable and validate it. It works fine.

My idea is to make an hybrid policy, where the server first checks for a header containing the JWT. This is for scenarios where the resource is accessed by an app, not a browser. If this fails, the policy checks if there is a cookie with the access_token in it, and then tries validating it.

So, remember that the idea here is to relief the server from session storage -- especially on clusters and scaling. So it won't be cool if the server still has to rely on some database to handle a cookie.

What do you think? Can I disable sessions and still work with cookie manipulation?

**Comment by leobudima** [comment]
@cburatto Good thinking, I would love to hear suggestions on how to make this work as well.

**Comment by cburatto** [comment]
@leobudima, thanks. I've created a policy that is working fine for me:

https://github.com/cburatto/jwtAuth

Cheers

**Comment by leomperes** [comment]
You can disable sessions in Sails, that should disable cookies. Add the code below in your `.sailsrc`:

```
{
  ...

  "hooks": {
    "session": false
  }
}
```

Source: http://sailsjs.org/documentation/reference/configuration/sails-config-session#?disabling-sessions

**Comment by jeff-kilbride** [comment]
I wish it was that easy. This does NOT work. I have disabled sessions in my `.sailsrc` and I still get the `sid` cookie in the headers as well as errors in the logs:
```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
I'm having problems with a production server crashing and this is a possible source.

**Comment by mikermcneil** [comment]
@leomperes thanks for updating!  See also https://gitter.im/balderdashy/sails?at=5a2b9e9ca2be4668287cb804 for some related tips
