### ISSUE TITLE
req.params.all() returns TRUE

### ISSUE THREAD

**Issue by rumyhuampas** [balderdashy/sails#2524]
Hi.
We are having issues with sails when parsing req values in blueprints actions.
req.params.all() instead of returning the same as req.allParams() it returns TRUE.
Why could this be happening? They are suppossed to be synonyms right?
req.allParams() works fine and returns an object with all request params.

Node 0.10.33
Sails 0.10.5

Any help is appreciated.

**Comment by pyrokinetiq** [comment]
I'm running node `0.11.14` and `req.params.all()` returns an array/object of the parameters as expected. Try upgrading your node?

**Comment by rumyhuampas** [comment]
I have upgraded to node 0.11.14 and req.params.all() still returns true!
Is really weird...

This is my `params.all` file in `sails/lib/hooks/request/`

~~~
/**
 * Module dependencies
 */
var _ = require('lodash');
var defaultsDeep = require('merge-defaults');



/**
 * _mixinReqParamsAll
 *
 * Mixes in `req.params.all()`, a convenience method to grab all parameters,
 * whether they're in the path (req.params), query string (req.query),
 * or request body (req.body).
 *
 * Note: this has to be applied per-route, not per request,
 * in order to refer to the proper route/path parameters
 *
 * @param {Request} req
 * @param {Response} res
 * @api private
 */

module.exports = function _mixinReqParamsAll(req, res) {

  ////////////////////////////////////////////////////////////////////
  // The check below is deprecatable since action blueprints
  // will no longer automatically receive the :id? param in their route.
  //
  // // Make sure `id` is omitted if it's undefined
  // // (since action blueprint routes name an optional :id)
  // if (typeof req.param('id') === 'undefined') {
  // 	delete req.params.id;
  // }
  //////////////////////////////////////////////////////////////////

  // Combines parameters from the query string, and encoded request body
  // to compose a monolithic object of named parameters, irrespective of source
  var queryParams = _.cloneDeep(req.query) || {};
  var bodyParams = _.cloneDeep(req.body) || {};
  var allParams = {};
  defaultsDeep(allParams, queryParams);
  defaultsDeep(allParams, bodyParams);


  // Mixin route params
  _.each(Object.keys(req.params), function(paramName) {
    allParams[paramName] = allParams[paramName] || req.params[paramName];
  });

  // Define a new non-enuerable property: `req.allParams()`
  req.allParams = function () {
    return allParams;
  };


  // Define a new non-enuerable property: req.params.all()
  // and make it a synonym to `req.allParams()`
  // (but only if `req.params.all` doesn't already exist!)
  if (!req.params.all) {
    Object.defineProperty(req.params, 'all', {
      value: function getAllParams() {
        return allParams;
      }
    });
  }

};
~~~

What are we doing wrong?

Please help!!!

**Comment by CWyrtzen** [comment]
Are you still having issues after v0.11?

**Comment by ejohnsonw** [comment]
had this problem just yesterday. when changed to req.allParams() it works as intended. I'm using 0.11.0

**Comment by ejohnsonw** [comment]
problem appears to be on the params.all.js. Disabling the if alleviates the problem.
<code>
 if (!req.params.all) {
    Object.defineProperty(req.params, 'all', {
      value: function getAllParams() {
        return allParams;
      }
    });
  }
</code>

**Comment by billyshena** [comment]
Hello guys, I'm currently having the same issue with node 5.0.0 and sails 0.11.2.
My blueprints action like GET /pets?name=toto does not work anymore if I append a condition (?field=...).
I have tried to debug and req.params.all() also returns TRUE instead of the where clause.
Any ideas?

Best,

**Comment by Zaggen** [comment]
Same here, using node 4.2.4 and sails 0.11.3, switching to `req.allParams()` works though...

**Comment by Bazze** [comment]
I just encountered this very same issue just now. Using sails 0.12.7 and node 4.3.0. It happens on my feature branch but not on master, so I'm gonna try to find the culprit!

**Comment by Bazze** [comment]
Okay, I've debugged for hours and finally found the issue. So I went into the [params.all.js](https://github.com/balderdashy/sails/blob/master/lib/hooks/request/params.all.js#L60) file and logged the value of `req.params.all` just before the if, it showed me the following value:

```javascript
// console.log(req.params.all)
function () {
    return this.every(Boolean);
}
```

Very interesting. I decided to do a `grep -R "this.every(Boolean)" node_modules` in my project which resulted in one match in a package called [collections](https://github.com/montagejs/collections/blob/master/generic-collection.js#L142). I scrolled down in the file and found an interesting [require statement](https://github.com/montagejs/collections/blob/master/generic-collection.js#L290) which got my attention: "shim-array" (!?). That didn't sound good.

In the [shim-array.js](https://github.com/montagejs/collections/blob/master/shim-array.js) file I found the culprit. They actually [define properties, `all` amongst others, on the Array prototype in the global scope](https://github.com/montagejs/collections/blob/master/shim-array.js#L68), effectively destroying the `req.params.all()` feature in sails. I found an issue regarding this in their issue tracker (https://github.com/montagejs/collections/issues/162) where they seem to solve the issue by downgrading to `collections@2.0.2`. This solution seems to work for me too, but since the collections package is a dependency of my dependency I need to make sure they are compatible.
