### ISSUE TITLE
`escape` and `escapeId` on a Model return undefined

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [balderdashy/sails#2525]
`MyModel.escape("hello world")` return `undefined` whereas 
`MyModel.waterline.connections.MyConnectionName._adapter.escape("hello world")` returns `'\'hello world\''` as expected

sails version : `0.10.5`

**Comment by sgress454** [comment]
I'm surprised it doesn't just give you an error, since `escape` and `escapeId` are not model methods at all.  I'm not sure what gave you that impression!  See the [Sails documentation on Waterline](http://sailsjs.org/#/documentation/reference/waterline) for all available model class and instance methods.  What you see is what you get!

**Comment by GuillaumeLeclerc** [comment]
If they are not method model how can you explain this : 
```javascript
sails> User.escape
[Function: bound]
```

**Comment by particlebanana** [comment]
@GuillaumeLeclerc that may be coming from whatever adapter you are using. It's not a method on Waterline.
