### ISSUE TITLE
Multiple sails.config.session.key values?

### ISSUE THREAD

**Issue by thebigsandwich** [balderdashy/sails#2526]
Is there anyway to set the cookie key (sails.config.session.key) on a per route basis.

I am using one server to host multiple apps (different flavors of the same game) and I would like to have a different cookie ID per app.

Example:
 
my.game.com/game1 -- cookie key game1.id
my.game.com/game2 -- cookie key game2.id

I tried changing the value of -- sails.config.session.key -- on a per route basis but it seems to break the session parser.

Thanks

**Comment by sgress454** [comment]
Hi @thebigsandwich, sorry for the delay and thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core; in the future for support requests please visit [http://stackoverflow.com](StackOverflow) or our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or IRC channel (irc://irc.freenode.org/sailsjs)

---

No, there's no way to do this in Sails, and I'm not sure how great an idea it would be.  As a workaround, you could namespace your session object (e.g. `req.session.game1`, `req.session.game2`, etc), and then use a [policy](http://sailsjs.org/#/documentation/concepts/Policies) to determine which game a route referred to and make `req.options.gameSession` refer to the correct session object.  Then instead of dealing directly with `req.session`, you'd instead read / write to `req.options.gameSession`.
