### ISSUE TITLE
req parameter in afterPublishAdd is false when using `sails.blueprint.mirror`

### ISSUE THREAD

**Issue by askmike** [balderdashy/sails#2535]
I am trying to hook a function on the `afterPublishAdd` method provided by the pubsub system

    this.afterPublishAdd(id, alias, idAdded, req);

However, after setting `req.options.mirror` to true the `req` parameter became false. This is caused by [the add blueprint giving](https://github.com/balderdashy/sails/blob/622e8a5a02baffd0cb3ddb7fc9f22becb6964fe0/lib/hooks/blueprints/actions/add.js#L173) the following parameter to `publishAdd`:

    !req.options.mirror && req

-----

- Is `afterPublishAdd` supposed to be public?
- Can I create a PR where I move the decision logic about skipping the current request to the publishAdd (et al.) functions?

**Comment by sgress454** [comment]
Hi @askmike,

`afterPublishAdd` isn't a private method; it's just not documented because there aren't tests for it.  But the `req` argument is at the moment intended solely to indicate a socket that should NOT receive the notification (this is the behavior that `mirror` toggles).  I would take a look at a PR that used the `options` argument for this instead.  Just FYI it might be a little while before it got merged as we're on the verge of releasing v0.11.x!
