### ISSUE TITLE
Mock a policy object

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/sails#2595]
Say I have a policy that does something complicated and I want to stub it in a test, something like

##### hardwork.js

```javascript
module.exports = function(req, res, next) {
     doSomethingReallyHardAndAnnoying();
     next()
}
```

I want to just stub this so it doesn't do anything

```
hardwork = function(req, res, next) { next(); }
```

I tried to figure out what's going on in the code - my first attempt was to stub `sails.hooks.policies.middleware.hardwork`

```javascript
sails.hooks.policies.middleware.hardwork = function(req, res, next) { console.log("running!"); next(); }
```

I also tried overwriting the policy by requiring it & reassigning in the test

```javascript
hardwork = require('hardwork');
hardwork = function(req, res, next) { console.log("running!"); next(); }
```

Neither of these worked. Sort of tricky to figure out, but if I'm reading this correctly, are you attaching a copy of the function object to the sails controller where it's referenced? which would make it virtually impossible to mock, or require N mocks for N routes which require the policy.

**Comment by kevinburke** [comment]
I also tried stubbing the object on `sails.middleware.policies`

```javascript
sails.middleware.policies.hardwork = (req, res, next) ->
        console.log "we mocked it!!!!!"
        next()
```

this did not work

**Comment by Dallas62** [comment]
You can add a check of the environment in your policy
```
        if( sails.config.environment === 'testing' ) return next(); 
```

But it's not a mock...

**Comment by sgress454** [comment]
@kevinburke interesting question.  @Dallas62's workaround is probably the simplest way, but not 100% ideal as it touches your policy code instead of replacing it entirely.  There's no place to really hook into the Sails load system that would let you replace a policy before it's bound to a route, in the way that you can use runtime config to turn hooks on or off.  The best I can think of is to use the `moduleLoaderOverride` runtime config to replace the `loadPolicies` block of `moduleLoader`:

```
  sails.lift({
    moduleLoaderOverride: function(sails, origModuleLoader) {
      // Get a handle to the original policy loader that we're overriding
      var loadPoliciesOrig = origModuleLoader.loadPolicies;
      return {
        loadPolicies: function(cb) {
          // Call the original policy loader so we load them from disk as usual
          loadPoliciesOrig(function(err, policies) {
            // Override the policy we want to mock
            policies.hardwork = function(req, res, next) {console.log("we mocked it!!!"); next();};
            // Return the list of policy functions
            return cb(err, policies);
          });
        }
      };
    }
  }, sailsLoadedCallback);
```

Bit of a mouthful for what you're trying to do, but it will work!

FYI in the future if you wouldn't mind throwing questions like these out to the [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [StackOverflow](http://stackoverflow.com) first, it helps us keep this forum manageable by restricting it to core bug reports and feature requests.  Thanks!

**Comment by joepuzzo** [comment]
@kevinburke This solution allows you to do what you want. You will have access to the policies through mocks.policies

`global.mocks = {}; 

before(function(done) {

  // Increase the Mocha timeout so that Sails has enough time to lift.
  this.timeout(5000);

  // Define options for sails lift
  var options = { 
    hooks: { 
      grunt: false
    }, 
    moduleLoaderOverride: function(sails, origModuleLoader) {
      // Get a handle to the original policy loader that we're overriding
      var loadPoliciesOrig = origModuleLoader.loadPolicies;
      return {
        loadPolicies: function(cb) {
          // Call the original policy loader so we load them from disk as usual
          loadPoliciesOrig(function(err, policies) {
            
            // Define mocked policeis
						var policy;
						var mockPolicy;
            // Give tests acess to policies
						global.mocks.policies = {};
            for( var id in policies ){ 

              // Get the cur policy
							policy = policies[id];

              // Put original policy on mocked policies
						  global.mocks.policies[id] = policy;

              // Wrap the original policy
              mockPolicy = function( req, res, next){ 
                return global.mocks.policies[id]( req, res, next ); 
							};

              // Add content from original
							mockPolicy.identity = policy.identity;
  						mockPolicy.globalId = policy.globalId;
  						mockPolicy.sails 		= policy.sails;  

              // Overide original
              policies[id] = mockPolicy;
            }
            //policies.jwtauth = function(req, res, next) {console.log("we mocked it!!!"); next();};
            // Return the list of policy functions
            return cb(err, policies);
          });
        }
      };
    }
  }

  // Bring up the sails application
  sails.lift( options, function(err, server) {
    if (err) return done(err);
    // here you can load fixtures, etc.
    done(err, sails);
  });

});
`

**Comment by kevinburke** [comment]
FWIW I think the problem was that this was a global object

**Comment by svmn** [comment]
In Sails v1 `moduleLoaderOverride` function is no longer available. How to deal with it?
