### ISSUE TITLE
which time upgrade global Lodash version to v3.1.0?

### ISSUE THREAD

**Issue by zieglar** [balderdashy/sails#2626]

**Comment by boogerlad** [comment]
There are breaking changes between 2.4.1 and 3.1.0, so existing users may be screwed. You can upgrade at your own risk.

**Comment by Globegitter** [comment]
Just wanted to note that I tried it out and it is not working.

First error I am getting:
```js
project/node_modules/sails/lib/app/private/after.js:50
    _emit.apply(emitter, args);
          ^
TypeError: undefined is not a function
```

If anyone wants to digg in, would probably not be too hard to patch.

**Comment by sgress454** [comment]
I'm not clear on what the question is here.  Sails hasn't upgraded [its version of Lodash](https://github.com/balderdashy/sails/blob/master/package.json#L61)...

**Comment by Globegitter** [comment]
Sorry, no question just thought if anyone was coming to look for the exact same issue (which someone probably will) they would at least have an immediate reference of it not working.

**Comment by sgress454** [comment]
@Globegitter what did you try out?  Upgrading the Lodash inside of Sails core?  Why oh why :crying_cat_face: ?

**Comment by blah238** [comment]
If you install Lodash 3.x as a dependency of your own project, Sails will use that version rather than its own, which results in the error @Globegitter reported.

I am not sure how to work around that. I would like to use some of Lodash 3.x's features in my own code without breaking Sails.

**Comment by mattymil** [comment]
Sails is uber awesome. However, running into the same issue. Would really like to use sortByOrder()  offered in 3.1. :(

**Comment by sgress454** [comment]
@blah238 @mattymil Does this occur even if you use the global Sails?  Or only when Sails is installed directly in the `node_modules` of your project?

**Comment by mattymil** [comment]
Only in project node_modules.

**Comment by sgress454** [comment]
Just to circle back on this, if you want to use a higher version of Lodash in your local project, I think it should work fine--just make sure you [disable the global Lodash](http://sailsjs.org/#!/documentation/concepts/Globals?q=disabling-globals) and run `npm update` afterwards so that your local Sails install downloads its own copy of Lodash 2.4.1.

**Comment by mattymil** [comment]
Got it.. thanks

From:  sgress454
Reply-To:  balderdashy/sails
Date:  Wednesday, June 3, 2015 at 7:35 PM
To:  balderdashy/sails
Cc:  "mattymil2@gmail.com"
Subject:  Re: [sails] which time upgrade global Lodash version to v3.1.0? (#2626)


Just to circle back on this, if you want to use a higher version of Lodash in your local project, I think it should work fine--just make sure you disable the global Lodash and run npm update afterwards so that your local Sails install downloads its own copy of Lodash 2.4.1.

**Comment by Vadorequest** [comment]
The question was useful indeed, just ran into the exact same issue. Thanks!

**Comment by elennaro** [comment]
experiencing the same issue.
