### ISSUE TITLE
Error: The hook `grunt` is taking too long to load - when attempt to lift in production

### ISSUE THREAD

**Issue by angel1st** [balderdashy/sails#2691]
Hi There,
I have Sails 0.11 framework. Add some additional code. Currently I have only one controller without model to it. Added MongoDB connection in config/connections.js and set it up in config/modes.js. I am using UBUNTU 14 machine. All is fine when `sails lift` is done. However, as long as I type `sails lift --prod` I have got the error below:

    error: Error: The hook `grunt` is taking too long to load. 
    Make sure it is triggering its `initialize()`    callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)
     at tooLong [as _onTimeout] (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:92:21)
     at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

I have two questions:

1. Where is actually `sails.config.grunt._hookTimeout` parameter? If it is assumed to be in `config/grunt.js` file I do not have this one in my `config` folder.
2. How to solve the issue?

Best Regards,
Angel

**Comment by angel1st** [comment]
I have just found out that the issue is caused from `angular.js` file. When the file is in `/assets/js/dependencies` folder it appears that Grunt is not able to minify / uglify it. The same goes even if I changed `angular.js` to `angular.min.js`. The `angular.min.js` is about 125K and it seems too big for Grunt. If this is the case, how to solve it?

**Comment by mikermcneil** [comment]
hey @angel1st you can solve this by setting the hookTimeout config.  We're planning on dramatically increasing the default in the next version because it's super annoying when this happens- sorry about that.  cc @sgress454

**Comment by sgress454** [comment]
@angel1st in the meantime you can set `sails.config.hookTimeout` to change the global hook timeout--for example in  `config/locals.js`:

```
module.exports = {
   hookTimeout: 30000, // 30 seconds
   ...other config...
}
```

**Comment by angel1st** [comment]
@mikermcneil & @sgress454 thanks for the feedback and the tip guys. Cheers!

**Comment by bmustata** [comment]
The change worked of us in production. Tks!

**Comment by secrettriangle** [comment]
:+1: please increase the default value!

**Comment by befreestudios** [comment]
@mikermcneil Where can I set the hookTimeout config to fix this?

**Comment by martingg88** [comment]
any update?

**Comment by RaedsLab** [comment]
Have the same issue when pushing to heroku, tried the fix suggested by @sgress454 but still fails.

**Comment by sgress454** [comment]
@RaedsLab try the fix suggested [here](https://github.com/balderdashy/sails/issues/2403#issuecomment-107298419) for Heroku.  It moves the Grunt tasks into the Heroku app startup phase, rather than having them occur during `sails lift`.

**Comment by RaedsLab** [comment]
@sgress454 Thank you this solved it

**Comment by cburatto** [comment]
I had a similar message but for `sails.config.logger._hookTimeout` for a sync service that necessarily takes too long to load.
My suggestion would be to set a higher value on my own code before it starts loading.
`sails.config.logger._hookTimeout = myHigherValue;` 
and perhaps reset it after loading. 

However:

- First, it seems this parameter name is actually `hookTimeout` not `_hookTimeout`
- Second, shouldn't is say `log` instead of `logger`?

**Comment by amberv0** [comment]
I encountered the same issue. But what is strange for me is that it occurs _only_ when sails is lifted with the `--prod` flag, even though the grunt tasks are _identical_ both for `prod` and `default` modes (I just copy-pasted) tasks from `tasks/register/default.js` to `tasks/register/prod.js`. 
Before I had `_hookTimeout` equal set to 40000. Now increased to 90000, but the problem is still there. So what is the difference for grunt between `prod` and `dev` modes beyond tasks lists?

**Comment by animedbz16** [comment]
With prod all your js is minified and uglified.

It's not good to run grunt in production. You should look to use the build
www to statically build these for deployment and leave grunt disabled in
prod
