### ISSUE TITLE
Duplicate Content-Type in response

### ISSUE THREAD

**Issue by dj-hedgehog** [balderdashy/sails#2705]
I'm building a RSS feed, set up like this:

```
  feed: function(req, res) {
    res.setHeader("Content-Type: application/rss+xml; charset=utf-8");
    Post.find({ isPublished: true }).limit(5).sort('createdAt DESC').exec(function (err, posts){
      return res.view('feed', {
        posts: posts
      })
    });
  }
```

The response content-type always looks like this:

```
Content-Type:application/rss+xml; charset=utf-8: undefined
Content-Type:text/html; charset=utf-8
``` 

What is going wrong here?

**Comment by sgress454** [comment]
Interesting--without looking into it, I'm guessing that `res.view` sets a header type automatically.  We'll take a look and fix that if it's the case (or feel free to dig in and make a PR).  Thanks for the post @dj-hedgehog!

**Comment by tjwebb** [comment]
@sgress454 any update on this?

**Comment by sgress454** [comment]
@tjwebb Thanks for checking in.  Now that I've had a second to look at it, the problem is far simpler; @dj-hedgehog was using `setHeader` incorrectly.  It actually, takes two arguments: the name of the header, and the value:

```
res.setHeader("Content-Type","application/rss+xml; charset=utf-8");
```

The way it was being used, Express was trying to set a header named `Content-Type: application/rss+xml; charset=utf-8` to `undefined`, and meanwhile was sending the default content content type header since it wasn't being overridden.
