### ISSUE TITLE
Github Chaos

### ISSUE THREAD

**Issue by lovemyjs** [balderdashy/sails#2716]
Seems to be a lot of just old pull requests and open issues from a long while ago. Are these still relevant items or needed to be cleansed? 

Looking to perhaps contribute myself since I'm working with Sails and want to make myself as familiar as I can.

**Comment by sgress454** [comment]
@lovemyjs agreed that a triage is in order.  We do keep an eye on things to make sure that the house isn't burning down...

**Comment by lovemyjs** [comment]
Well, that's good. Anything I can do to assist to keep Sails alive and thriving for my foreseeable future of development. Lol.

**Comment by emosher** [comment]
:+1:  for a cleanup/triage.  Recently became interested in Sails and might like to contribute.

**Comment by rex** [comment]
I'd like to submit my support as well. If any assistance on my part to assist in identification and cleanup of resolved or void issues would help, please let me know. Sails is far too bad ass a product to watch it even seem to go down the path of abandonment.

**Comment by rex** [comment]
I apologize for double commenting here, but I felt compelled to after opening and subsequently closing #2724. There are many moving parts to the sails application and it seems that at least one (and possibly more, unconfirmed) are out of date on npm. Given that this is a wildly popular npm package, the out-of-date nature of npm combined with the overabundance of open issues is an even stronger indicator that this package is in dire need of some attention and that the maintainer needs some assistance in playing catch up.

To whomever maintains this repository, **please** let the community come to Sails' aid. You can kick us back out after it's cleaned up and nursed back to health if you want. But seriously. Sails is awesome and we want to help.

**Comment by sgress454** [comment]
@rex yup, pushed this a couple of days ago but didn't push a new version to npm.  Thanks for pointing it out, fixed now!

**Comment by sgress454** [comment]
Re: the chaos in general, let's not start panicking quite yet! :open_mouth: :fire: :skull:  Yes, there are a lot of open issues, but many of them can probably be closed with some variation of:

> Hi @awsumPossum, thanks for using Sails!  This forum is for bug reports on the Sails core; for support requests, please use [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [Gitter Chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).  For feature requests, please see our [contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#requesting-features).

There are a few reasons why there are so many open issues right now:

1. We like to take the time to make sure each one doesn't present some underlying problem the Sails core, and
2. If it's a first-time poster, we tend to answer their question even if it isn't a bug, after letting them know that they should post elsewhere next time , and
3. The core team is working on something pretty big, which we'll have more details on very soon.

If you really want to get involved, no special privileges or superpowers are required!  You are free to post comments on any issue, especially if you think you can help, and if it seems like it is something that requires a lot of work and is *not* a bug report, feel free to let the poster know that they might have better luck posting elsewhere.  Sometimes they'll close the issue themselves; even if they don't, it'll give us the freedom to close it out if appropriate without spending more time.

Thanks for y'alls support, and for your patience!

**Comment by rex** [comment]
@sgress454 Thank you for the prompt response! I am extremely glad to hear a maintainer's voice, not just because Sails is great but I may or may not be deploying Sails into multiple production parts of my team's infrastructure.

As I'm going to be spending quite a bit of time in Sails documentation in the next few months I'll comment on issues where I can and mention you on ones I feel can be closed. 

Thanks again!

**Comment by Kikobeats** [comment]
Btw, @sgress454, what happened with the [sails trello roadmap](https://trello.com/b/cGzNVE0b/sails-roadmap)?

Can be awesome and useful uses for the community. Personally I'm in love with [Ghost Roadmap](https://trello.com/b/EceUgtCL/ghost-roadmap)

**Comment by tjwebb** [comment]
We are the most popular node.js MVC framework, so things unfortunately do appear chaotic now and then. We recently released sails 0.11 so the volume is high than usual, which may distract us from other issues. We are definitely committed to the project, and are working to bring more resources on board to help out.

**Comment by sgress454** [comment]
@Kikobeats you know, we've been using Trello internally with really great results, but it never clicked when using it for the roadmap.  Looking at it now, it's clear that we weren't really using it right--the lists we picked weren't really helpful for us to organize issues and tasks.  We might give it another go in the future.

**Comment by randallmeeker** [comment]
Here is a small little rant on this topic. I wrote it all out and was ready to take a deep breath, hit the delete key and return to work. But I figured i would post it anyway. It's all written with love as sails is my new framework of choice. As I write this the Sailsjs.org documentation site is down. I went over to the sails docs Github report to report it and found many open issues and pull requests sitting unanswered in there as well, so I figured why bother.

---------------------------------------

When do we start to panic? Treeline is an exciting new product, but now I feel like there is an entirely new product that the sails team will be supporting. Then there is the "Really Big Product", which @sgress454 already admitting is taking people away. 

The outstanding issues in here have been here well before the latest version. I think simply labeling every issue would help. 

I appreciate that Sails.js needs community support and I think you find you have many supporters, but we need more support from the sails team in closing issues, labeling issues, fixing the website and consolidating support channels (IRC,StackOverFlow,Google Groups, GitHub,Gitter, the amount of places I'm told to go to get information is insane. notice no one ever says go to the website!). I have posted questions to these on topics, with not much response. I think there is a lot of help for the little guys to get started and answer questions (I answer questions every day on stack overflow trying to help), but for the rest of us its hit or miss.

Example: I asked about the ```_config``` key that is used in controllers and could not get a peep out of anyone, and here is an issue that needs more documentation that I'm happy to write, but I have no clue about its officially sanctioned use case. I'm using it in all my apps, but I could be using and recommending it wrong to others. For instance I use it to define my model in a sub-controller, and I have told others as well. I have no idea if this is a hack or intended use. I have dug into the code to get more answers, but it should not be so hard, especially for smart people that want to help.  

I think its a perfectly good time to panic, because some of these issues (like bad docs) have been topics of conversation for well over a year. How about all the issues that reference the documentation is broken on google. This has been the case for many many many months. This is not a community issue, we can't solve for this?

**Comment by sgress454** [comment]
Randall, I can't say enough about how much we appreciate devs like you being a part of Sails.  Your contributions do not go unnoticed.  When I see your name on an answer in StackOverflow I know I can generally considered it handled and move on, and that's a big load off my back and a big smile on my face.  If your questions about `_config` or anything else have been ignored, I apologize (you mean you didn't find the section about it [buried in the v0.10 migration guide](http://sailsjs.org/#!/documentation/changelog/0.10)?).  Now, to your points:

> Treeline is an exciting new product, but now I feel like there is an entirely new product that the sails team will be supporting. Then there is the "Really Big Product", which @sgress454 already admitting is taking people away.

Treeline *is* the really big product.  To be sure, it's diverted our attention somewhat since the core team has [temporarily relocated to Mountain View](https://twitter.com/TreelineHQ/status/576025749171220481) to work on it.  But make no mistake: Treeline's success depends on Sails--both the software itself and the community around it.  It compiles Sails apps, and will continue doing so until Javascript is labeled a controlled substance (in which case we will lobby hard for its legalization).  The takeaway is that rather than abandoning it, we're committing even further to the project.  

>  (IRC,StackOverFlow,Google Groups, GitHub,Gitter, the amount of places I'm told to go to get information is insane. notice no one ever says go to the website!)

Oh man.  I agree.  There are a lot of channels.  At best, they appeal to different groups and everyone finds their niche (with the exception of Github--please only post bug reports to Github).  At worst you find yourself hopping from place to place asking the same question.  I was a little nervous about the Gitter channel, but it really seems to be working out--I peek my head in from time to time but I mainly find that the community there is taking care of itself quite nicely.  And I do tell people to go to the website, all the time--in my posts in those other channels (how else would they see it?).  The issue with the website isn't that the content isn't there, it's that there is no search.  And that searching from Google is broken.  Which brings me to...

> How about all the issues that reference the documentation is broken on google. This has been the case for many many many months. 
>
>This is not a community issue, we can't solve for this?

I respectfully disagree--the documentation web site is as open-source as everything else about Sails, and in fact @phishy has volunteered to take a pass at the changes necessary to get everything working with Google again (basically the decision to make the whole thing one giant SPA, while sexy and popular, turned out to be a bit difficult to maintain for that type of app).  The site went down today, we got some tweets about it, and we restarted it.  When no one restarts the site, *that* will be a good time to panic!

But all tit-for-tat aside, we do hear you.  We really do.  We've been trying out a system where we each take a few PRs or issues this morning and make a concerted effort to at the very least categorize them, if not respond or (ideally) close them.  The problem of spiraling issues is [not new](http://words.steveklabnik.com/how-to-be-an-open-source-gardener), but new ideas are always welcome.    

Thank you, and good night. :relieved:

**Comment by tjwebb** [comment]
> closing issues, labeling issues, fixing the website and consolidating support channels

There are a lot of channels. I am regularly on Github, Gitter, and SO, and these channels at minimum are here to stay. People have individual preferences. Gitter is better for real-time support, for example. I'm personally less in love with IRC and Groups. We will come to a compromise as to which outlets we will coalesce around for official support. But ultimately, people who have issues are going to file them wherever is momentarily convenient for them.

Closing and labeling issues is, itself, an issue, I agree. I wouldn't say Treeline is "taking people away". Treeline is now downstream from sails.js -- they will be as dependent on sails as anyone. It **is** fair to say that over the past few months we've been distracted; but while the new Treeline project is a huge effort, its success will ultimately make sails even stronger.

**Comment by randallmeeker** [comment]
@sgress454 Thanks for your kind words about my participation. I can only hope that I'm being helpful and not just whining as some people (including myself) are prone too.

In regards to the ```_config``` key. I popped this in the docs repo https://github.com/balderdashy/sails-docs/issues/410
I'll be happy to add to docs I'm just very unsure at times if an undocumented feature is a feature. I have done stuff on frameworks that ends being dropped because it depreciated and no one told me or I straight "Was doing it wrong".

I started panicking today when the docu site was down. Not because I did not know where to find the info I needed, (the docs repo) but because as that site suffers so does the the rest of our sites. It's harder to convince clients about sails and I also get a little bit nervous about my sites as well. I have to ask myself sometimes if whatever crashed the docu site is going to crash my site? This tweet from @sailsjs 

>Site back online, but still slow for some.  Extra traffic due to @TreelineHQ launch?  Mice in the server room?  You decide!" . . . . 

I appreciate that stuff happens, and the need to keep things light, but if we could provide a little more context for what happened for the rest of us for the reason listed above.

> the documentation web site is as open-source as everything else about Sails, and in fact @phishy has volunteered to take a pass at the changes necessary to get everything working ...

I was unaware @phishy's efforts and applaud him, only I just feel like its been an issue for months now. How would people know who's doing what and what progress they have made? I think this was the last issue https://github.com/balderdashy/www.sailsjs.org/issues/50 posted about it before xmass? When I said its not a community issue, I was attempting to elevate it to something the core should be involved in, especially since its been going on this long. If it takes that long to fix, that is the message you giving to interested parties. "Sails is so complicated that our docs site has been broken for a few months. "

I would +1 the labeling and just plain closing of issues of old issues. It just gives everyone that warm and fuzzy feeling. 

Thanks everyone and I will see about getting some pull requests in to make up for all this whining.

I will say that I have a my 3rd sails app going into production this next month!!!!!

**Comment by tjwebb** [comment]
> It's harder to convince clients about sails

If you'd like to talk more about this, drop me a line: tjwebb@balderdash.co

**Comment by sgress454** [comment]
Thanks @tjwebb.  In the case of the website I can pretty confidently say that the point of failure was not Sails.  As Sails apps go, www.sailsjs.org is pretty light, and it handles its responsibilities of serving the one page and its assets exceedingly well.  No, it's our adventures in overcomplicated front-end routing that have gotten us into trouble here (hence the spinning and browser locking that was reported), along with our choice of hosting provider.  We've learned our lessons on both counts, but it will take a bit of elbow grease to get the site to where we all want it to be.

**Comment by randallmeeker** [comment]
@tjwebb thanks 

@sgress454 would love to hear about your hosting woes somewhere at some point. I know I have had my issues  as well, but now were getting off topic. Maybe a groups discussion.

**Comment by phishy** [comment]
The documentation being unsearchable totally sucks, but I plan on taking a
stab next week, as some free time is coming my way. The plan is to take the
existing sails-docs repository and generate a a static version that can be
searched by Google. The conversation was going on here until we decided to
go completely static.
https://github.com/balderdashy/www.sailsjs.org/issues/56

**Comment by CWyrtzen** [comment]
We are listening~

**Comment by randallmeeker** [comment]
@CWyrtzen Moving the conversation from https://github.com/balderdashy/sails/pull/2206#issuecomment-82392667 to here (which I think was closed a bit pre-maturely) to keep things clean.

>BUMP it means it has been hand-carried on your behalf

If we could use literal syntax when their is a point of confusion it might help as nothing is really "hand-delivered". ```bumped``` without context does not seem mean anything and figures of speech don't really help. 

```bump``` however is something the public does to attract core attention too and show support for an issue. I think were conflating the two words.

I guess in the end my question is "What are we supposed to do with 'bumped~'" when we see it and in the future to limit "GitHub Chaos" if we could provide more context when updating issues because ```bumped``` does not really tell us anything.

**Comment by CWyrtzen** [comment]
@randallmeeker good points. I hope it is clear, I am here to help, to support you in what you need and to support the core team in minimizing chaos. So, your feedback let's me know that my terminology is contributing to the confusion. Fair enough.

The terms tells me and perhaps others that this is individually brought to the attention of a specific person who has been marked as an assignee. That doesn't mean they will complete it but they will help figure out the best way to keep progress going.

The term is really just for me so that I don't reassign that issue but I can see where it is confusing, may not seem helpful to some, and I can devise my own code for tracking suck things.

Again, I am here for you. Your feedback is important AND I am also asking for your patience while we devise systems to tidy things up.

Closed issues can ALWAYS have more comments attached. I felt that @sgress454  gave some pretty thorough answers and that some valid points were heard. If more activity shows up in the comments we can certainly reopen.

One of the ways we can keep this tidy is to save issues for bug reports and things that are technically challenging and encourage discussion in the Google Group or, if it is started here, give some time for comments, feedback, core response, and then close things up--again, to keep things as tidy and focused as possible.

Community feedback is ALWAYS welcomed and appreciated. Helping the core team focus is also critical to meeting your needs as well.

**Comment by randallmeeker** [comment]
@CWyrtzen why not just use the tools GitHub gives us, such as assigning and labeling? Assignment and labels won't ping our inbox's and show people a level of organisation that I think is the central issue around this particular discussion. 

In terms of closing this issue, I think an issue gets closed for 1 of 3 reasons

a.) It is not an issue after all
b.) It has been solved and the solution is shown
c.) It is a duplicate of another issue

I think "We are listening~" - closed . . . does not really file it away into any of these categories. 

. . . .  I think my feedback switch has been turned on too long . . . . .

**Comment by CWyrtzen** [comment]
Sorry for typos (above & here)- on a phone and not wanting to be unresponsive. I hear your frustrations and appreciate your suggestions and I have no problem devising a system that does not ping you.

As far as what our internal system will be...use of tools in place have been employed for some time, will continue to be meaningful,  and may be added-to temporarily, offline, as we clean house. Again, I will devise a "silent" system except that there will be assignees added.

Perhaps this assignee is all that is needed to let you know when you check in on PR/issue: we hear you. We are working on it.

I mean that as a gesture of support not as a blanket answer to your concerns.

I am here to help.

**Comment by mikermcneil** [comment]
@emosher @rex @lovemyjs thanks for the offer to help guys- we're experimenting with a system we could use to keep the flow of issues/PRs under control- a sort of "street team" approach, if you will (i.e. if you're on the team, you get a daily email with an issue or PR to take care of.  If you can't do it, you pass it on and someone else takes it.)

@randallmeeker re: sailsjs.org - most of our problems here have been my crappy client-side Angular code.  The problem this week is that the single Modulus instance serving sailsjs.org was being hit by tens of thousands of simultaneous requests for assets and 404 pages.  The solution was just to scale up to multiple servers (we were just overwhelmed)

Thanks for your support everyone.  I'll keep you posted on the status of the aforementioned "issue street team" plan  (I'm making sure it works with a small group of contributors first)

**Comment by mikermcneil** [comment]
@randallmeeker btw- in case it helps, here's some of the stats from the three production sails apps we're hosting ourselves (and running on Sails v0.11):

+ heroku deployments are going to be tricky w/ socket.io until they publicly release their sticky sessions feature.  If you need to use heroku in the mean time, if you disable other transports besides WebSockets, it works great.  See the Socket.io repo issues for more information.
+ On a normal day, sailsjs.org serves about 80 requests / minute (modulus) 
+ On a normal day, treeline.io serves about 500 web requests / minute (heroku, 9ms average response time) and 130 API requests/ minute (heroku, 25ms avg response time)
+ On a normal day, node-machine.org serves about 50 requests / minute (heroku, 17ms avg response time)

(we're using postgres as db, redis for session store, redis for socket.io store)

cc @particlebanana
