### ISSUE TITLE
Change connection used on runtime

### ISSUE THREAD

**Issue by kai23** [balderdashy/sails#2722]
Hello !

I hope you can help me (us). I'm working on a API project which have two databases : 

`Production DB : api.myapp.fr`
`Testing DB : test.api.myapp.fr`

Theses two databases are writable by the user.

When a user call our API, he can set the authorization header whichever he needs. For example : 

```
Authorization: s_0
```

Will perform  operations on `api.myapp.fr`  and 
```
Authorization: s_t_0
```

Will perform operations on  `test.api.myapp.fr` .

My question is : How can I do that with sails ? 

Actually, I have a policie which check if the user is using a production key or a testing key, and I override the default models with the one for testings purposes, like this :
 ```javascript
if (!is_production) {
	req.session.isProd = false;
	req.session.logs.environment = "test";

	User = UserTest;
	Payment = PaymentTest;
	PayzenStatus = PayzenStatusTest;
	Transaction = TransactionTest;
	Card = CardTest;
	Doc = DocTest;
}
```

But you can see the problem if a user makes a test request and then a production request, the models are still the tests ones...

If you have any idea on how ton achieve this (whatever the way, we can still perform deep changes in our code), I would be really happy to ear it.

Thanks

**Comment by sgress454** [comment]
Hi @kai23, FYI this forum is for posting bugs in the Sails core.  In the future please post support queries to [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [Gitter Chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
You definitely don't want to be reassigning those global variables like `User`, as it will affect all subsequent requests.  One idea would be to assign the models to the `req` object itself, since by definition it only represents a single request.  So:

```
req.models = {};
// If not in production, use the test models
if (!is_production) {
    req.session.isProd = false;
    req.session.logs.environment = "test";

    req.models.User = UserTest;
    req.models.Payment = PaymentTest;
    req.models.PayzenStatus = PayzenStatusTest;
    req.models.Transaction = TransactionTest;
    req.models.Card = CardTest;
    req.models.Doc = DocTest;
}
// Otherwise use the production models
 else {
    req.models.User = User;
    req.models.Payment = Payment;
    req.models.PayzenStatus = PayzenStatus;
    req.models.Transaction = Transaction;
    req.models.Card = Card;
    req.models.Doc = Doc;
}
```
Then in your controller code, reference `req.models.User` instead of plain `User`.

**Comment by randallmeeker** [comment]
http://stackoverflow.com/questions/28894661/change-connection-used-on-runtime
