### ISSUE TITLE
Delegating CORS to nginx

### ISSUE THREAD

**Issue by MrDHat** [balderdashy/sails#2749]
I am trying to delegate all cors realted settings to nginx. Here is what `nginx.conf` looks like:

```
user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
  # max_clients = worker_processes * worker_connections / 4
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/json;
  sendfile on;

  # backend applications
  upstream nodes {
    server 127.0.0.1:8000;
    server 127.0.0.1:8001;
    keepalive 64;
  }

  server {
    listen 80;
    server_name domain.com;

    # static resources
    location ~ ^/(robots.txt|humans.txt|favicon.ico) {
      root /usr/share/nginx/html;
      access_log off;
      expires max;
    }

    # everything else goes to backend node apps
    location / {
      proxy_pass http://nodes;

      proxy_redirect off;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $host;
      proxy_set_header X-NginX-Proxy true;
      proxy_set_header Connection "";
      proxy_http_version 1.1;


      if ($request_method = 'OPTIONS') {
       
        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials 'true';
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS, HEAD';
        
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #

        add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        
        #
        # Tell client that this pre-flight info is valid for 20 days
        #

        add_header Access-Control-Max-Age 1728000;
        add_header Content-Type 'application/json charset=UTF-8';

        return 204;
      }

      if ($request_method = 'POST') {

        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials 'true';
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS, HEAD';
        add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      }

      if ($request_method = 'GET') {

        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials 'true';
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS, HEAD';
        add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      }
    }
  }

}
```

As you can see, I am setting `cors` headers in the nginx conf.

Any request to the server returns 2 values for the same header. For example:
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Credentials:
Access-Control-Allow-Headers:DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
Access-Control-Allow-Headers:
```

After some debugging, I can safely guess that the empty headers are being set by `sails`. Is there a way to disable these headers from sails? As I just want sails to be my application and everything else to be handled by nginx

**Comment by kevinburkeshyp** [comment]
Try proxy_hide_header ?

-kevin

On Mar 13, 2015, at 15:54, Akshay Katyal <notifications@github.com> wrote:

I am trying to delegate all cors realted settings to nginx. Here is what
nginx.conf looks like:

user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
  # max_clients = worker_processes * worker_connections / 4
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/json;
  sendfile on;

  # backend applications
  upstream nodes {
    server 127.0.0.1:8000;
    server 127.0.0.1:8001;
    keepalive 64;
  }

  server {
    listen 80;
    server_name domain.com;

    # static resources
    location ~ ^/(robots.txt|humans.txt|favicon.ico) {
      root /usr/share/nginx/html;
      access_log off;
      expires max;
    }

    # everything else goes to backend node apps
    location / {
      proxy_pass http://nodes;

      proxy_redirect off;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $host;
      proxy_set_header X-NginX-Proxy true;
      proxy_set_header Connection "";
      proxy_http_version 1.1;


      if ($request_method = 'OPTIONS') {

        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials 'true';
        add_header Access-Control-Allow-Methods 'GET, POST, PUT,
DELETE, OPTIONS, HEAD';

        #
        # Custom headers and headers various browsers *should* be OK
with but aren't
        #

        add_header Access-Control-Allow-Headers
'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

        #
        # Tell client that this pre-flight info is valid for 20 days
        #

        add_header Access-Control-Max-Age 1728000;
        add_header Content-Type 'application/json charset=UTF-8';

        return 204;
      }

      if ($request_method = 'POST') {

        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials 'true';
        add_header Access-Control-Allow-Methods 'GET, POST, PUT,
DELETE, OPTIONS, HEAD';
        add_header Access-Control-Allow-Headers
'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      }

      if ($request_method = 'GET') {

        add_header Access-Control-Allow-Origin '*';
        add_header Access-Control-Allow-Credentials 'true';
        add_header Access-Control-Allow-Methods 'GET, POST, PUT,
DELETE, OPTIONS, HEAD';
        add_header Access-Control-Allow-Headers
'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      }
    }
  }

}

As you can see, I am setting cors headers in the nginx conf.

Any request to the server returns 2 values for the same header. For example:

Access-Control-Allow-Credentials:true
Access-Control-Allow-Credentials:
Access-Control-Allow-Headers:DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
Access-Control-Allow-Headers:

After some debugging, I can safely guess that the empty headers are being
set by sails. Is there a way to disable these headers from sails? As I just
want sails to be my application and everything else to be handled by nginx

—
Reply to this email directly or view it on GitHub
<https://github.com/balderdashy/sails/issues/2749>.

**Comment by MrDHat** [comment]
I added:

```
proxy_hide_header Access-Control-Allow-Origin;
proxy_hide_header Access-Control-Allow-Credentials;
proxy_hide_header Access-Control-Allow-Methods;
proxy_hide_header Access-Control-Allow-Headers;
proxy_hide_header Access-Control-Max-Age;
```

Now 2xx response code work find but no header is attached for any other response code. Any idea why that might be happening?

**Comment by kevinburkeshyp** [comment]
Haven't worked with nginx in a while, but it's highly possible the commands
only set headers for 2xx replies. May want to try the headers more module

On Fri, Mar 13, 2015 at 4:16 PM, Akshay Katyal <notifications@github.com>
wrote:

> I added:
>
> proxy_hide_header Access-Control-Allow-Origin;
> proxy_hide_header Access-Control-Allow-Credentials;
> proxy_hide_header Access-Control-Allow-Methods;
> proxy_hide_header Access-Control-Allow-Headers;
> proxy_hide_header Access-Control-Max-Age;
>
> Now 2xx response code work find but no header is attached for any other
> response code. Any idea why that might be happening?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails/issues/2749#issuecomment-79520078>.
>



-- 
kevin

**Comment by MrDHat** [comment]
Got it working by using more headers module. Thanks :)

**Comment by saviogl** [comment]
@MrDHat Can you post your response here?
