### ISSUE TITLE
Removing # from the URL

### ISSUE THREAD

**Issue by angel1st** [balderdashy/sails#2753]
Hi there,
I want to manage routing at the frontend by AngularJS route and I want to have "pretty" URLs, meaning excluding "#" symbol from the URLs. I found this article https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode, explaining how to do that in plain ExpressJS.
Currently in my `routes.js` file I have got:

        '/': {
            controller: 'HomeController',
            action: 'index'
       }

and change it to:

       '/*': {
            controller: 'HomeController',
            action: 'index'
       }

However, I have `Uncaught SyntaxError: Unexpected token <` in `sailsjs.io` file and almost all *.js files in my project.
So how can I handle that?

**Comment by mikemastah** [comment]
This is because everything now redirects to the index action in your HomeController.

You should probably try to use:
```
'/*': {
  controller: 'HomeController',
  action: 'index',
  skipAssets: true
}
```
As found in the [docs](http://sailsjs.org/#!/documentation/concepts/Routes/RouteTargetSyntax.html?q=route-target-options)

**Comment by angel1st** [comment]
Thanks @mikemastah  - the only difference between your code and mine is the `skipAssets: true` - this line did the trick indeed.
It is still not clear for me the explanation however. Since I want everything to be redirected to index action of HomeController, which on its turn just renders index.ejs. This is why I am doing Single Page Application (SPA).
So how actually `skipAssets: true` helped me - could you please elaborate a bit more? Thanks in advance.

**Comment by mikemastah** [comment]
Of course.

Your route `'/*'` specifies that *everything* which matches your route should be redirected to your index action. To explain what this means let's say you have your routes.js config setup like so:
```
"GET /api/auth/login": {controller: "HomeController", action: "login"},
"/*": {controller: "HomeController", action: "index"},
```
Also let's say your HomeController action looks like this:
```
index: function (req, res) {
  res.ok("<h1>Hey!</h1>");
},

login: function (req, res) {
  res.ok("<span>Logged in!</span>");
}
```
| URL  | Response|
| ------------- | ------------- |
| /home  | &lt;h1&gt;Hey!&lt;/h1&gt;  |
| /login  | &lt;h1&gt;Hey!&lt;/h1&gt;  |
| /someAction  | &lt;h1&gt;Hey!&lt;/h1&gt;  |
| /images/header.png  | &lt;h1&gt;Hey!&lt;/h1&gt;  |
| /vendor/angular/angular.min.js  | &lt;h1&gt;Hey!&lt;/h1&gt;  |
| /api/auth/login  | &lt;span&gt;Logged in!&lt;/span&gt;  |

As you can see, all your static files (images, javascript, css) will return `<h1>Hey!</h1>` instead of the expected files.
By using `skipAssets: true` you are effectively saying, match everything *except* when the requested URL is an asset.

Hope this explanation is sufficient.

**Comment by angel1st** [comment]
Hi @mikemastah  - thanks for the prompt response!
Now it seems to have sense.
