### ISSUE TITLE
Some issue about deploy sails in production environment

### ISSUE THREAD

**Issue by cage1618** [balderdashy/sails#2774]
How can I deploy a sails app in production?

I follow the documentation

1.touch a file named local.js in my production.
2.enter the config of mysql such as host, user, password and so on (in the config/connection.js has another config different between user and password)
3.Then I run sails lift —prod test my config

But I does’t create tables auto, when I run sails lift without —prod, It will be work finally

Then, I try to move the config to the config/env/production.js

sails lift —prod and sials lift all don’t work

How can I resovle this issue ? Thank! Hope your reply!! Thanks! Thanks! Thanks! Thanks! Thanks!

**Comment by sgress454** [comment]
Hi @cage1618, thanks for using Sails!  FYI this forum is for reporting bugs in the Sails core; in the future for support please use [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [Gitter Chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). 

<hr/>

What documentation are you following?

Sails automatically runs in `migrate: safe` mode in a production environment, which means it will *not* change your production DB in any way.  

Moving your production configuration to the `config/env/production.js` file is a good start, but it won't get your database schema set on production.  There are a few ways to do this:

1.  Use [sails-migrations](https://github.com/BlueHotDog/sails-migrations); this is a good option as long as you start using it at the beginning of your project and keep migrations up-to-date.
2.  Use `local.js` to connect to your remote database from your local computer in the `development` environment with the `migrate: alter` scheme running, so that Sails creates the schema for you.
3.  Export your local schema using `mysqldump`, then import it to your production database if you have that kind of access.

A new migration scheme called `create` has been added to Waterline that will update database schemas without touching actual data; look for that in our next patch release of Sails.
