### ISSUE TITLE
how to use i18n function in assets/js/files.js

### ISSUE THREAD

**Issue by lamujeresponja** [balderdashy/sails#2817]
Hi all!

I need use i18n() in my code inside of assets/js of my sailsjs project. How can i to do it?

In my views is ok but in my js not, why?

thanks you very much.

I have sailsjs@0.10.5

**Comment by RWOverdijk** [comment]
Hello @lamujeresponja,

Because JS is statically served. If you wish to use variables inside of your JS you'll have to change the grunt (or gulp) config to do so. These typically use a view engine so it might be a bit tricky.

Also, please post this question on stackoverflow. It's not a bug or feature request so it doesn't really belong here.

**Comment by lamujeresponja** [comment]
Thanks RWOverdijk. 

Sorry.
I put my question in Stackoverflow. http://stackoverflow.com/questions/29493181/sails-js-how-to-use-i18n-function-in-assets-js-files-js

Best regards.
