### ISSUE TITLE
Convention for services: quick question

### ISSUE THREAD

**Issue by onetwopunch** [balderdashy/sails#2840]
I'm using sails with passport generator and ember-data generator. Is the convention for services to capitalize the service like `Ember.js` or lowercase it like `passport.js`? There just seems to be a discrepancy.

**Comment by tjwebb** [comment]
I typically capitalize my my service filenames, and suffix them with "Service". e.g. `MinerService`: https://github.com/hashpanel/server/tree/master/api/services.

If you have globals on, then you'll want these names to be unique, which is why suffixing with `Service` is a good idea. This convention is also used in the official sails.js documentation: http://sailsjs.org/#!/documentation/concepts/Services?q=how-do-i-create-a-service

**Comment by onetwopunch** [comment]
@tjwebb Thanks so much
