### ISSUE TITLE
view rendering issue

### ISSUE THREAD

**Issue by martingg88** [balderdashy/sails#2864]
view .ejs is not render for any user agent like wget or facebook or google robot. 

any idea?

**Comment by martingg88** [comment]
i found out that res.ok() doesn't work well with robot agent like wget or facebook and others.

**Comment by randallmeeker** [comment]
This appears to be a good question about google bot (among others) indexing a sails.js site. In its current implimentation Sails will want to spit out JSON for any bot trying to access its page (using res.ok) unless that bot explicitly asks for HTML. Google bot's headers are set to ```Accept: */*```, which means sails will always give it HTML. 

This is also referenced in issue 
https://github.com/balderdashy/sails/issues/2764

The Rules
https://github.com/balderdashy/sails-docs/blob/master/reference/req/req.wantsJSON.md

@martingg88 I would suggest in the mean time you modify your reponse file to look for a particular set of robots in order to render. 

Going forward there needs to be a setting in Sails.js that can allow for this. 

IMO I think the setup where Sailsjs really wants to default to JSON seems to have been a mistake. Most systems that want JSON know how to ask for it, but not all system that want HTML know how to ask for it. 

......

Granted their is the question of why a site being indexed by google has the option of rendering JSON in the first place. @martingg88 do you have a publicly accessible indexed site that is also rendering HTML on the same pages that you want to render JSON, or should you be using ```res.view()``` instead of ```res.ok()```?? just wondering about your implementation.

**Comment by martingg88** [comment]
yes..some of my code will render both html and json. yet. i try to disable the req.wantsJSON for all the robot. I think google/facebook/bing robot they mostly prefer to scrap html/sematic tags than json data.

**Comment by sgress454** [comment]
@martingg88 sounds like you may already be doing this, but a good strategy in your case may be to use a policy to detect robots (by user agent) and manually set `req.wantsJSON` to false.  Anyways thanks for posting, definitely something to keep in mind.
