### ISSUE TITLE
Sockets in deployment

### ISSUE THREAD

**Issue by luish000** [balderdashy/sails#2885]
Hi people.

I have a proble in openshift I dont know why the afterDisconnect function for disconnect event in sockets is not execute immediately, but in localhost the execution of this function is immediately

**Comment by sgress454** [comment]
Hi @luish000, thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core.  In the future if you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).   
<hr/>
To shed some light on your issue, remember that all of the Socket calls are asynchronous; nothing is ever happening immediately.  If it seems that way on localhost vs. production, it's likely due to the fact that when running your app locally, your requests don't have to travel very far between the browser and your Sails.js app, whereas when deployed someplace like Openshift there's quite a bit of overhead that takes places during each request.
