### ISSUE TITLE
Hook after response

### ISSUE THREAD

**Issue by mateeyow** [balderdashy/sails#2896]
Is there a way to add a hook on a route or controller and do something with the response object?

**Comment by Josebaseba** [comment]
Check this hook that I made to add a new method to the request object. Maybe it can help you: https://github.com/Josebaseba/sails-hook-validator

**Comment by mateeyow** [comment]
I think what your code does is review the request object, what I want to do is do something with the response object. So I don't want to do anything before the response, it's like adding a lifecycle afterUpdate or whatnot. But thanks anyway. I'll check this out for future reference.

**Comment by Josebaseba** [comment]
I create a small sails project that maybe it can help you, with a custom hook:

https://github.com/Josebaseba/sails-response-end-listener

Take a look, and tell me if that solution works for you too.

**Comment by sgress454** [comment]
@mateeyow Just FYI, this forum is for reporting bugs in the Sails core.  In the future for, please post support questions to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).   

@Josebaseba your solution is good, but if all that is required here is a way to modify the response before it's sent out, we suggest customizing the "api/responses/ok.js" response and using that in your controllers (i.e. do `res.ok()` instead of `res.send()`).
