### ISSUE TITLE
Hook routes and policies

### ISSUE THREAD

**Issue by eddieajau** [balderdashy/sails#2897]
Is there a way to bind policies to hook routes?

My hook is like this:

```js
function myHook(sails) {
	return {
		routes: {
			before: {
			},

			after: {
				'GET /articles': function (req, res, next) {
					return res.jsonx([{},{}]);
				},

				'GET /articles/:id': function (req, res, next) {
					return res.jsonx({});
				}
			}
		}
	};
}

module.exports = myHook;
```
And my policies are like this:

```js
module.exports.policies = {

	'PublicController': true,

	// Default policy for all controllers and actions
	'*': 'authenticated'
};
```

But it appears that the hook routes are being included after the policies are being bound.

Is there a way to ensure that the hook routes are wired up to the policies?

sails v0.11.0
node v0.12.0

Thanks in advance.

**Comment by tjwebb** [comment]
@loicsaintroch do you have any insight on this?

**Comment by sgress454** [comment]
Hi @eddieajau, just FYI this forum is for reporting bugs in the Sails core.  In the future if you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
<hr/>
The `config/policies` file in Sails only binds policies to Controller actions, so it won't work for routes bound in a hook.  But there is a workaround: in your `config/routes.js` file, try:

```
'/*': {policy: 'authenticated', skipAssets: true},
```

This uses the [policy target syntax](http://sailsjs.org/#!/documentation/concepts/Routes/RouteTargetSyntax.html?q=policy-target-syntax) for routes to run the "authenticated" policy on every route _except_ assets.  If you do this, you'll probably want to remove the default policy from the `config/policies.js` file or else it will run twice...

**Comment by eddieajau** [comment]
> just FYI this forum is for reporting bugs in the Sails core

Yes I know. I was talking to @tjwebb about this and he didn't know whether this was a bug or a feature so suggested that I post here.

> please post to our Google Group or Stackoverflow, or try our live Gitter chat room.

Tried Google Group and Gitter - no responses.

> But there is a workaround

Ok thanks for that but it's not going to work in all situations. How can we have a conversation about whether or not it's permitted to change Sails' core behaviour to support policies in hook routes? I'm happy to put some coding effort behind this, but I will need some guidance with regard to how to do it. My guess is the best option would be to delay wiring up policies to routes until after all hooks are loaded (and that would allow hooks to add their own policies).

**Comment by sgress454** [comment]
Changing the ordering of when policies are wired up won't have much of an effect, because again the only mapping that the policies hook does is between *controller actions* and policies.  This is true even of the wildcard `*` policy; it doesn't apply to views, or to ad-hoc functions written directly in the routes file, for example.  If you were going to have a go at changing that behavior, I'd keep a couple of things in mind:

1. At this point, we'd rather not have big changes in the core hooks bundled with Sails.  Instead, we'd rather see those hooks *un*bundled into separate modules (see [sails-hook-sockets](https://github.com/balderdashy/sails-hook-sockets)).  So that'd be a first step.
2. If what you're really wanting is for the wildcard policy to apply to _all_ routes, and not just controller actions, it would have to be a configurable thing that's off by default, because it would be a breaking change.  If that's _not_ what you want, then you're better off just specifying the policy in `config/routes.js` as I described, since it's applying to a specific subset of routes anyway.
