### ISSUE TITLE
Can't serve static files without an extension in filename.

### ISSUE THREAD

**Issue by kevinwheeler** [balderdashy/sails#2917]
sails version: v0.11.0

I would guess this is because if a filename doesn't have an extension, the URL to this file is interpreted as the URL to a directory that should contain an index.html file.

**Comment by tjwebb** [comment]
I have to ask: why on earth are you serving filenames that have no extension?

**Comment by kevinwheeler** [comment]
I personally don't have a good reason for it, but I did waste a significant amount of time before I realized what the problem was.

**Comment by sgress454** [comment]
Sails isn't serving your extension-less files because they're not being copied to the `.tmp/public` folder, because the default grunt tasks don't copy files without extensions.  You can change that by editing the `tasks/config/copy.js` task, although it would probably take some trial-and-error to get your files included without also including things you don't want.  See the [grunt-contrib-copy](https://github.com/gruntjs/grunt-contrib-copy) docs for the options there.

As for downsides to static files without extension--besides the wasting of significant time that you already mentioned?  There's the fact that without the hint that the extension provides, Express doesn't know what to do with those files, so if you browse to them you'll get a download dialog in most cases.

**Comment by ebaynaud** [comment]
@stellanor grunt is disabled in my project [like that](https://sailsjs.com/documentation/concepts/assets/disabling-grunt)

Any idea I could manage to serve apple-app-site-association?

**Comment by vjrj** [comment]
To deploy files like this `NOTICES`:
https://docs.flutter.dev/deployment/web#building-the-app-for-release

I use:

```
diff --git a/tasks/config/copy.js b/tasks/config/copy.js
index f06c50b..a87ec3c 100644
--- a/tasks/config/copy.js
+++ b/tasks/config/copy.js
@@ -11,12 +11,16 @@
  */
 module.exports = function(grunt) {
 
+  // Fix for files without extension
+  // https://github.com/balderdashy/sails/issues/2917
   grunt.config.set('copy', {
     dev: {
       files: [{
         expand: true,
         cwd: './assets',
-        src: ['**/*.!(coffee|less)'],
+        src: ['**/*',
+              '!**/*.less',
+              '!**/*.coffee'],
         dest: '.tmp/public'
       }]
     },
```
