### ISSUE TITLE
Integrate sticky-sessions, for PM2 and socket.io

### ISSUE THREAD

**Issue by dapriett** [balderdashy/sails#2927]
Hello,

I'm trying to figure out how to integrate sticky-sessions (https://github.com/indutny/sticky-session) with Sails.js.  According to the socket.io docs (http://socket.io/docs/using-multiple-nodes/), sticky-sessions is needed in order to make socket.io work correctly in a node cluster (using PM2).

Thanks!

**Comment by tjwebb** [comment]
Sails already has built-in support for using redis as a shared socket/session store. 

See More Info here: http://sailsjs.org/#!/documentation/anatomy/myApp/config/sockets.js.html

**Comment by dapriett** [comment]
I believe the redis is used for socket event sharing though, right?  I need to make connections stick to the node instance once connected.  For nginx across servers I can make the connections stick, but not sure how I would do it with node clusters with sails.

**Comment by sgress454** [comment]
Sticky sessions are not something that exist at the Sails level; it has to be supported by the load balancer that you're using the distribute the Sails app so that once a client connects to one server in the cluster, all subsequent requests are sent to that same server.  If sticky sessions are enabled, you can just use the default, in-memory session store that ships with Sails.  But even in that case, for production apps you're better off with a more robust session store.  That's why Sails supports Redis for sharing sessions, too.  See the [session config documentation](http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.session.html?q=shared-redis-session-store).  Then you don't have to worry about whether sticky sessions are enabled or not; even if the client makes requests to different servers in the cluster, the session will be maintained.

**Comment by dapriett** [comment]
Not sure what the issue is then - I'm using Redis for sessions

```
module.exports.sockets = {
  adapter: 'socket.io-redis'
};

// Add for Redis sessions
module.exports.session = {
  adapter: 'redis'
}
```

Works fine if I have one instance, but when I have multiple instances (using pm2 clustering), I get a bad request for the websockets, similar to this: https://github.com/balderdashy/sails/issues/2916

**Comment by odnarb** [comment]
+1 same issue

**Comment by tjwebb** [comment]
> I need to make connections stick to the node instance once connected. 

As @sgress454 mentioned, sails has no control over how proxies in front of it route requests. That occurs at a different layer of your hosting infrastructure, and sails nor node.js have any control over that. 

But I don't think you *need* the sessions to "stick" to a particular instance. This sort of defaults the purpose of horizontal scalability anyway -- if that instance is saturated, then you're screwed. You need to setup the shared session and socket stores using redis. This will accomplish the same thing, and allows you to retain the symmetry needed for a correctly-designed cluster.

@odnarb can you be more specific about your particular setup, how you've configured your sessions and socket stores, etc?

**Comment by odnarb** [comment]
Sure, here's some info:
node.js is @ v0.12.2, and here's my npm list --depth 0 output:

├── apn@1.7.3
├── bcrypt-nodejs@0.0.3
├── body-parser@1.10.0
├── coffee-script@1.9.3 extraneous
├── connect-redis@1.4.5
├── ejs@0.8.8
├── express@3.4.1
├── gcm@1.0.1
├── include-all@0.1.6
├── moment@2.8.3
├── mssql@2.1.3
├── node-uuid@1.4.2
├── nodemailer@1.3.0
├── nodemailer-smtp-transport@0.1.13
├── optimist@0.3.4
├── pagination@0.4.2
├── pass-generator@1.0.2
├── raw-body@1.3.1
├── rc@0.5.5
├── request@2.55.0
├── sails@0.11.0
├── sails-disk@0.10.8
├── sails-redis@0.10.3
├── sails-sqlserver@0.10.7
├── socket.io-redis@0.1.4
└── xml2js@0.4.4

local.js:

  port: process.env.PORT,

  ssl: {
    key:  require('fs').readFileSync('./server.key'),
    cert: require('fs').readFileSync('./server.crt')
  },

  environment: process.env.NODE_ENV || 'development',

  models: {
    migrate: 'safe',
    connection:  process.env.DB_CONNECTION || 'disk'
  },

  connections: {
    mssql: {
        module: 'sails-sqlserver',
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        user: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_NAME,
        timeout: 15000,
        pool: false,
        connectionLimit: 0
    }
  },

  session: {
        adapter: process.env.SESS_ADAPTER,
        host: process.env.SESS_HOST,
        port: process.env.SESS_PORT,
        db: process.env.SESS_DB,
        prefix: process.env.SESS_PREFIX
  },
  sockets: {
        adapter: process.env.SOCK_ADAPTER,
        host: process.env.SOCK_HOST,
        port: process.env.SOCK_PORT,
        db: process.env.SOCK_DB
  }

As for the specifics: the db connects to a server, here on my network. The redis instance is on the same server as my sails app so connection info is 'localhost'...but here's my ecosystem.json for pm2:

    "env_test": {
        "NODE_ENV": "test",
        "PORT": "443",
        "DB_CONNECTION": "mssql",
        "DB_USER": "me",
        "DB_PASS": "mine",
        "DB_NAME": "sailsapp",
        "DB_HOST": "sqlserver1",
        "DB_PORT": 1433,
        "SESS_ADAPTER": "redis",
        "SESS_HOST": "localhost",
        "SESS_PORT": 6379,
        "SESS_DB": "sails",
        "SESS_PREFIX": "sess:",
        "SOCK_ADAPTER": "socket.io-redis",
        "SOCK_HOST": "localhost",
        "SOCK_PORT": 6379,
        "SOCK_DB": "sails",
        "SOCK_PREFIX": "sock:"
      }

Thanks for the quick reply btw.

**Comment by dapriett** [comment]
Is it a PM2 issue then - is clustering not supported by sails?  The socket.io keeps failing with 400 Bad request for me with multiple processes, with REDIS...

**Comment by odnarb** [comment]
@dapriett  Well I guess if you're familiar enough with the raw cluster approach you can test if this is pm2-specific or node.js cluster in general.  I don't have the extra time to do that kind of testing unfortunately unless it's a super quick solution like a matter of some silly command option.

**Comment by dapriett** [comment]
I tried testing it without cluster and manually starting multiple sails instances on different ports with nginx & redis.

So if I comment out ip_hash in nginx below so sessions no longer stick, I get the same issue as I was with PM2 and clustering...

```
# NGINX load balanacer config
upstream sails_apps {
        # ip_hash;
        server localhost:1337;
        server localhost:1338;
        server localhost:1339;
        server localhost:1340;
        server localhost:1341;
    }
```

So it appears it is an issue with socket.io requiring sticky sessions, which doesn't make sense to me why it would matter.  I guess it has to do with because socket.io is doing multiple requests to perform handshake and establish connection with a client - and for some reason that has to be to the same node instance.

Socket.io docs recommend using the sticky sessions module (http://socket.io/docs/using-multiple-nodes/) if you're doing clustering - but if you look at sticky sessions (https://github.com/indutny/sticky-session) it requires wrapping the server module before calling listen.  Not sure if sails provides a clean way to inject that on startup.

So maybe the best option for now is to avoid clustering and just start multiple node instance on different ports with NGINX (and ip_hash enabled) in front.  I'm guessing this is probably more of a socket.io bug then sails...

**Comment by odnarb** [comment]
I guess coming back to it, cluster mode isn't even the best way to go for production..  even though I've already built a deployment strategy around using pm2.

Here's a reference for those interested in SSL+nginx+sails.js:

http://blog.keithcirkel.co.uk/load-balancing-node-js/

**Comment by sgress454** [comment]
@dapriett Sorry, you're right--I wasn't reading your issue closely enough, and was just thinking about the session store, and not sockets.  Socket.io 1.0 out of the box does require sticky sessions because it attempts to connect via long-polling first, and then upgrades to websockets if possible.  So for clustering scenarios (or platforms like Heroku) the default configuration won't work.  The simplest workaround is to just disable the polling transport and use websockets exclusively; the downside is reduced browser support, but all the major modern browsers should be fine.  See [this note](http://sailsjs.org/#!/documentation/concepts/Deployment/Scaling.html?q=configuring-your-app-for-a-clustered-deployment) for more details.

**Comment by odnarb** [comment]
@dapriett  Sorry, I derped out. I re-read your post, added ip_hash in the nginx config, without adding "sticky-session" or hacking sails' app.js.

All is well now.

**Comment by leobudima** [comment]
@sgress454 Thanks for your last comment. If you would be so kind, I'd love to get a verification on some of the mentioned aspects for my specific case.

We have an application with session hook disabled, since there's nothing to keep in it, in our case, and - by being stateless - we love the added benefit of effectiveness and ease of horizontal scaling and not needing sticky sessions. 

Can you please confirm that if:

- we have session hook disabled
- we set `transports: ['websocket']` and `adapter: redis` in `sockets.js` in Sails 
- we do the same in our clients: `io.sails.transports = ['websocket'];`

we will be able to have clients be routed to and served from different Sails instances (with redis handling socket sharing), without re-introducing sessions?

Thanks a lot!

**Comment by leobudima** [comment]
A bit later, I can confirm that the approach described above works - using redis, with sessions completely disabled, our clients still get model updates over sockets, from different servers connected to the same database.

**Comment by bberry6** [comment]
So just read all this, as I'm having the same issue (I require long polling for socket.io).  +1!

@dapriett 
So if I use the nginx config like...
```
# NGINX load balancer config
upstream sails_apps {
        ip_hash;
        server localhost:1337;
        server localhost:1338;
        server localhost:1339;
        server localhost:1340;
        server localhost:1341;
    }
```
And start my apps manually instead of using PM2, will the http requests be sticking, since nginx is in front and controlling the app that each requests gets routed to?  If so, it sounds like this could be a temporary workaround for the time being without having to sacrifice the polling transport.  

@sgress454 
My companies firewall blocks all websocket traffic (EXTREMELY ANNOYING!! /rant), so it is more than just browser support that may affect the end user from viewing the web app properly. :/

**Comment by dapriett** [comment]
@bberry6 
If you use PM2 it will start them all on the same port - don't believe it supports sending different port args to each instance it spawns.  We're using docker containers for our application, so we ended up just creating multiple instances (without using PM2 or clustering), and putting it behind nginx.

**Comment by bberry6** [comment]
@dapriett 
got it, thank you!
