### ISSUE TITLE
need some help with res.view()

### ISSUE THREAD

**Issue by xchl** [balderdashy/sails#2930]
I set views folder like this
views
      ----------common
      ----------desktop
            -----------------user/login
      ----------mobile
            -----------------user/login
in the controller
        user.login
                 return  res.view() 
how to do this
         if is mobile device auto load  "mobile/user/login" else "desktop/user/login".

**Comment by TimofeyBiryukov** [comment]
You can use a 'user agent' to determine if it is a mobile or a desctop browser. And judging by this render proper view.

**Comment by xchl** [comment]
@TimofeyBiryukov  yes it is thank you.but i want to auto render.I want to know how to extend res.views() to do this.

**Comment by xchl** [comment]
最后是这样做的，不知道是否是最佳方案
```
    controller.js
    return ViewService(req,res,'user/login',{title:'login-page'});
    ViewService
     moudle.exports = function(req,res,path,data){
             if(req.headers['user-agent']=='iPhone'){
                   res.view('mobile/'+path,data);
             }else{
                   res.view('desktop/'+path,data);
             }
     }
````

**Comment by Oldwo1f** [comment]
hi,
you can use a policie to do that.
just create a policie to parse the request and then add a parameter to request if it come from mobile.

After in your method that return view, just test this params to send the corect view.

Here is an exemple
* note that i use this to check for modern browser, but its the same way for mobile*
*seconde note: i use UAParser to parse UserAgent headers Request but you can make it your own with RegExp.

```javascript
var UAParser = require('ua-parser-js');


module.exports = function(req, res, next) {
  // sails.log('modernd BROWSERS')
  
    var parser = new UAParser();
    var ua1 = req.headers['user-agent'];
    result = parser.setUA(ua1).getResult()
    if(result.browser.name=="IE" && Number(result.browser.major) <=8)
    {
      // if oldbrowser
         req.oldBrowser = true;
    }
    else{
     req.oldBrowser = false;  
    }
   next();
};
```

**Comment by sgress454** [comment]
Thanks for the discussion, everyone.  @xchl, you might also consider overriding the `api/responses/ok.js` file in your project and then using `res.ok` instead of `res.view` in your controller actions.  Also, just FYI we try to reserve this forum for reporting bugs in the Sails core, so in the future questions like this are better placed in our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [Gitter chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com/questions/tagged/sails.js?sort=newest&pageSize=50).
