### ISSUE TITLE
Blueprint's "REST AddTo" triggering 'beforeUpdate' hook on parent

### ISSUE THREAD

**Issue by cyrilchapon** [balderdashy/sails#2936]
Having these models :

*Family.js*
```
module.exports = {
  attributes: {
    name: {
      type: 'string',
      required: true
    },
    members: {
      collection: 'person',
      via: 'family'
    },
   beforeUpdate: function(values, next) {
      console.log(values);
      next(null, values);
   }
}
```

*Person.js*
```
module.exports = {
  attributes: {
    name: {
      type: 'string',
      required: true
    },
    family: {
      model: 'family'
    }
  }
};
```

When I call:
```
POST /person
{"name":"Walter","family":1}
```
Nothing is logged

But when I call:
```
POST /family/1/members
{"name":"Walter"}
```
The console shows
```
{ name: 'White',
  id: 1,
  createdAt: Fri May 15 2015 12:21:24 GMT+0200 (CEST),
  updatedAt: Fri May 15 2015 12:48:42 GMT+0200 (CEST) }
```

This is annoying because beforeUpdate is supposed to have "only real values to update as a parameter", thus for example hashing a password on password update is hard to achieve in here.

**Comment by sgress454** [comment]
The issue isn't that it's calling `beforeUpdate`; that's the correct behavior for a model that's being updated (in this case by having an item added to its `members` collection).  The issue is that when the `.save()` instance method is called on a model, it's the equivalent of calling `Model.update()` with *all of the instance's current attributes* used as the update values.  Using `.add()` and `.save()` is the only way to add an item to an instance's existing collection, hence the problem.  A common workaround is to `delete` any instance attributes you don't want passed into `beforeUpdate` before calling `.save()`.  

In a future version of Waterline there may be another method that will avoid this issue, but for the moment, it means that hashing a password in `beforeUpdate` isn't recommended if you're planning on using the "add" blueprint with that model.  I'd take a look at a PR that deleted the non-collection attributes before calling `.save()` [here](https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actions/add.js#L159), though...

**Comment by cyrilchapon** [comment]
Ok thanks =) Got it!

For community, I solved it not by `delete`ing my hashed password, but rather testing it against a [simple module](https://github.com/etineosas/bcrypt-helper/blob/7da6029548912a4c222aac5574f5171a38ce8a63/index.js#L4-L6) we made to detect already-bcrypt-hashed passwords.
