### ISSUE TITLE
Getting 400 when posting JSON array to blueprint route

### ISSUE THREAD

**Issue by luisincrespo** [balderdashy/sails#2977]
Hi.

I'm using Sails 0.11. Your docs say it is possible to post multiple objects to a blueprint route, just passing a JSON array.

I'm trying to do this, but I'm getting 400 bad request as response.

This is my case:

I have a model called *Prediction*, which only has two fields, *user* (id) and *poll* (id). I'm posting this (to /prediction):

    [
        {
            "user": "556b33e884eb522f02a4f52e",
            "poll": "556c4ff8243f03e501e2b65c" 
        }
    ]

And I'm getting a 400 response, with the following body:

>{
  "error": "E_VALIDATION",
  "status": 400,
  "summary": "2 attributes are invalid",
  "model": "Prediction",
  "invalidAttributes": {
    "user": [
      {
        "rule": "required",
        "message": "\\\"required\\\" validation rule failed for input: null"
      }
    ],
    "poll": [
      {
        "rule": "required",
        "message": "\\\"required\\\" validation rule failed for input: null"
      }
    ]
  }
}

**Comment by ArtworkAD** [comment]
:+1: the same for me. I cannot assign an empty array. It fails with
```
{
    "error": "E_VALIDATION",
    "status": 400,
    "summary": "1 attribute is invalid",
    "model": "Ticket",
    "invalidAttributes": {
        "notifications": [
            {
                "rule": "required",
                "message": "\"required\" validation rule failed for input: []"
            }
        ]
    }
}
```

**Comment by mattcodez** [comment]
The blueprint [uses](https://github.com/balderdashy/sails/blob/e87aed76363357cade682f75c179da8c9c1e4954/lib/hooks/blueprints/actionUtil.js#L274) req.params.all() which parses a POSTed JSON array as an object
Example:
```
{ '0': { name: 'q1', value: '3' },
  '1': { name: 'q2', value: '5' } }
```
Whereas `req.body` parses as expected
```
[ { name: 'q1', value: '3' }, { name: 'q2', value: '5' } ]
```

Not quite sure how this should be fixed. Perhaps check to see if `req.body` is an array first and then default to `req.params.all()` if not?

**Comment by Hanifb** [comment]
Same for me. Without the possiblity to create multiple objects on one post, Sails.js is worthless.

**Comment by CiscoKidxx** [comment]
That's a tad extreme and just your narrow minded opinion.

**Comment by Hanifb** [comment]
@CiscoKidxx Hey, i love sails.js, but without the possibility to post more than one object it restricts the usability of the framework in real life implementations. Specially when the docs claim that this feature is supported.

**Comment by Hanifb** [comment]
Did some digging and was able to create a blueprint that has no problem inserting an array of objects, with correct implementation of req.options.values and blacklist, just a quick isArray check on the req.body, works perfectly on a http post, however the body parser of socket.post still creates an object, it will convert an array to an object
So an req.body will instead of looking like:
`[{fname: "Hanif", lname:"Bali"},{fname: "foo", lname:"bar"}]`
will look like:
` {0: {{fname: "Hanif", lname:"Bali"}}, 1: {fname: "foo", lname:"bar"}]:`

So depending if you are using an socket you will get diffrent data sent to Model.create.

**Comment by tjwebb** [comment]
> Same for me. Without the possiblity to create multiple objects on one post, Sails.js is worthless.

Sails is also *free* and we rely on the community to help us solve issues like this. A PR would be appreciated.

**Comment by Hanifb** [comment]
Sure, no probz, any hints where Sails parses the request body?

**Comment by Hanifb** [comment]
So i dug around and found what causes this behavior, first of all the non-http requests gets treated like this in receive-incoming-sails-io-msg.js in the sails-hook-sockets module:
```javascript
body    : _.extend({}, options.incomingSailsIOMsg.params || {}, options.incomingSailsIOMsg.data || {}),
```
This of course converts the array into an object, but also the subsequent behavior by actionUtil does this when it extracts and handles the data (applying blacklist and default values).

Changing this line corrects the issue:
```javascript
body    : _.isArray(options.incomingSailsIOMsg.data) ? options.incomingSailsIOMsg.data : _.extend({}, options.incomingSailsIOMsg.params || {}, options.incomingSailsIOMsg.data || {}),
```

However the actionUtil.parseValues method will still convert the array to an object regardless of transport because it uses req.params.all().

**Comment by sgress454** [comment]
@Hanifb your PRs look great--we'll just need some tests in order to merge them in!  I'll add comments to the individual PRs about where to put the tests.

**Comment by sgress454** [comment]
Closing this issue in favor of the PRs, good work!

**Comment by luisincrespo** [comment]
Great to know!. Good work @Hanifb.

**Comment by shamasis** [comment]
But both PRs are still open @sgress454! :disappointed: Can we reopen until they are merged and released?

**Comment by sgress454** [comment]
Sorry @shamasis, looking at this now.

**Comment by dbubs** [comment]
@sgress454 any update on this?
