### ISSUE TITLE
HAML Support

### ISSUE THREAD

**Issue by timbuktuuu** [balderdashy/sails#2984]
HI folks,

i wonder if sails stopped the haml Support because i cant get it running. 

Thank you for any kind of Help.

Cheers

**Comment by sgress454** [comment]
Oh, boy.  Looks like Consolidate.js exports `haml`, but loads `hamljs`, giving our automated engine-loader the slip.  Patched [here on master](https://github.com/balderdashy/sails/commit/90e2f97581822f090029713831b2eaccc4ffb596
) so that you can do:

```
  engine: {
    name: 'haml',
    module: 'hamljs',
    ext: 'haml'
  }
```

which also fixes similar issues with Liquid and Hogan templates.  Also submitted a [pull request to Conslidate](https://github.com/tj/consolidate.js/pull/199), we'll see where that goes.

We're gearing up to push out a new release; in the meantime, I'm afraid there's not a ton you can do besides pulling down the patched Sails from Github.
