### ISSUE TITLE
Why is non-config placed in the config folder?

### ISSUE THREAD

**Issue by prawnsalad** [balderdashy/sails#3028]
Is there any reasoning behind why a lot of app code should be placed in the config folder?
* `config/bootstrap.js` This is application bootstrap code
* `config/routes.js` Possibly debatable as app code, but certainly not configuration. Routes define the request structure for an application.
* `config/policies.js` This are all code blocks. Not configuration.
* `config/globals.js` Provides global vars for the app code. Not configuration

Perhaps the term `config` is being used a bit too loosely, mixing development + run time config?

**Comment by tjwebb** [comment]
I consider everything you mention to be "configuration". I see no reason to think that your criteria for determining what is and isn't configuration is any less arbitrary than mine.

**Comment by prawnsalad** [comment]
Just to understand the mindset behind it then, what makes blocks of code in bootstrap.js or policies.js config, while blocks of code within say.. a controller is not?

**Comment by tjwebb** [comment]
I don't what you're asking. Are you looking for our opinion? We designed it this way because it's what all the other *ails frameworks do. The point of convention-over-configuration is to give your brain a rest from such details :)

In my opinion, "bootstrap" logic constitutes one or more of the **initial conditions** of the application. It's a way to alter -- or configure -- these initial conditions before the application is booted, which can affect the behavior of the application **itself**, as a whole.

Controller logic is invoked by the user, not the application, and comprises business-specific functionality. At the end of the day it's all javascript code, of course, but you'd never use a controller to do something you'd normally use bootstrap for, or vice versa. They each serve a distinct and defined purpose, and there's no overlap.
