### ISSUE TITLE
Cron doesn't work

### ISSUE THREAD

**Issue by torresl** [balderdashy/sails#3038]
Hi,

   I tried to  use Cron with sails js. But, it doesn't work. 
My OS is ubuntu 14.04.1. 
I launched ths command : "sudo service cron restart"

I installed these modules :   
https://www.npmjs.com/package/cron
https://www.npmjs.com/package/node-schedule (http://www.worldnucleus.com/2014/12/run-cron-job-in-sailsjs.html )
https://www.npmjs.com/package/sails-hook-schedule

But none of theses modules work.
Did i forget something to config in Sails js framework or a command to launch ?.

thank you in advance

**Comment by richdunajewski** [comment]
sails-hook-schedule doesn't use cron, it merely uses the cron-style format for configuring the schedule. 

In order to run the scheduler, you'll need to run sails and keep it running 24/7. When node-schedule runs the job at the specified time, the code you configured as the task will be run.

Restarting the cron service would have no effect, since no jobs are being registered there. 

For example, I run a sails web server that is always online. Each day at midnight, it runs a task to import some data from a third party which goes through a sails service and uses the ORM to perform the inserts into my DB.

**Comment by torresl** [comment]
Thanks. it works well.
