### ISSUE TITLE
response sended before last query

### ISSUE THREAD

**Issue by elwadi** [balderdashy/sails#3055]
hi,
ihave problem when i use foreach query to find some documents on DB , the response  is sended before query has finish,
this is my code

Third.find({deletedAt:null,customer:true}).exec(function(err,customers){
				if(err) return res.serverError(500);
				else{
					Product.find({deletedAt:null,product:true}).exec(function(err,products){
						if(err) return res.serverError(500);
						else{
								var _invoice_products=[];
								invoice.products.forEach(function(item){
									Product.findOne({id:item.product}).exec(function(err,_product){
										_invoice_products.push({id:_product.id,product:_product.name,qte:item.qte,price:item.price});
									});
								});
								console.log(_invoice_products);
							return res.view('invoice/show_sales',{customers:customers,
																										invoice:invoice,
																										products:products,
																										invoice_products:_invoice_products});
						}
					});

				}
			});

Note : 
console.log(_invoice_products); is always empty !! please help me

**Comment by particlebanana** [comment]
`forEach` is synchronous and the `Product.findOne` query is asynchronous. If you want to use a loop you will need to use something like [async.each](https://github.com/caolan/async#each). 

Also note that if you pass in an array of primary keys you can perform an `in` query and find all of the records so instead of looping through all the products and finding them one by one you could do something like this to get them in a single query:

```javascript
Product.find({ id: [1,2,3] }).exec(/*... */);
```

**Comment by elwadi** [comment]
:+1:
