### ISSUE TITLE
Manually fetch tables from Mysql

### ISSUE THREAD

**Issue by ytzvan** [balderdashy/sails#3109]
I want to access to existing Mysqldb, I sucesfully connect to them, but when I try to access using Model.find(), there's no data. I think this is happening because I set migration : safe, but If I set to migration:alter, at the start up send me an error because Sails-mysql try to "Drop", but I have no rights. How can I migrate the data manually or access direct to the data?

**Comment by richdunajewski** [comment]
Does your model have the correct fields for the MySQL database? It's likely that the adapter is sending a `SELECT field1, field2, field3 ...` query to MySQL rather than the dreaded `SELECT * ...`. If that's the case, your model may not be providing the right field names for the query to return anything. 

If your MySQL DB and Sails models are configured the same, there's no need to migrate anything. Migration is useful when your DB schema is being changed frequently during development when you add or modify fields in your model, so you don't have to manually modify your DB schema each time you want to make a change.

**Comment by ytzvan** [comment]
Hello, I was using the Model.find() options with migrate:safe setting. I
changed Model.find() for Model.query() and make a native SQL statement.
Thanks for all your help.

2015-07-27 10:02 GMT-05:00 Rich Dunajewski <notifications@github.com>:

> Does your model have the correct fields for the MySQL database? It's
> likely that the adapter is sending a SELECT field1, field2, field3 ...
> query to MySQL rather than the dreaded SELECT * .... If that's the case,
> your model may not be providing the right field names for the query to
> return anything.
>
> If your MySQL DB and Sails models are configured the same, there's no need
> to migrate anything. Migration is useful when your DB schema is being
> changed frequently during development when you add or modify fields in your
> model, so you don't have to manually modify your DB schema each time you
> want to make a change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails/issues/3109#issuecomment-125238101>.
>



-- 
*Ytzvan A. Mastino*
<http://compreoalquile.com>+507-6780-9892

**Comment by particlebanana** [comment]
If you need to map attributes in your model to column names you can use the `columnName` property.

```javascript
attributes: {
    name: {
      type: 'string',
      columnName: 'wb_name'
    }
}
```
