### ISSUE TITLE
Error: Cannot find module 'skipper-disk'

### ISSUE THREAD

**Issue by alfredobarron** [balderdashy/sails#3114]
http://sailsjs.org/documentation/concepts/file-uploads#?uploading-a-file

this error trigger when download avatar

**Comment by richdunajewski** [comment]
`npm install --save skipper-disk` will install the new dependency for you and save it to your package.json file. 

Skipper isn't installed by default, in order to keep Sails lightweight. If you're using a piece of code that requires it, you'll just have to install it as a dependency of your project using the above code.

**Comment by alfredobarron** [comment]
i think that was already install in node_modules/sails/node_modules/skipper/node_modules/skipper-disk
