### ISSUE TITLE
Many to Many through relations and sails issues

### ISSUE THREAD

**Issue by nicco** [balderdashy/sails#3181]
I'm running 0.12b3 and I'm using Many to Many through relations and I've noticed the following issues:

The model that represent the relation cannot be access as a Global but it can be access through sails.models.modelName

The model representing the relation does not inherit the functions declared in models.js

**Comment by nicco** [comment]
I Declare in CompanyUser.js this:

```
var CompanyUser = {
    attributes: {
        company: {
            columnName: 'company',
            type: 'string',
            foreignKey: true,
            references: 'company',
            on: 'id',
            onKey: 'id',
            via: 'user'
        },

        manager: {
            type: 'boolean',
            defaultsTo: false
        },

        user: {
            columnName: 'user',
            type: 'string',
            foreignKey: true,
            references: 'user',
            on: 'id',
            onKey: 'id',
            via: 'company'
        }
    }
};

module.exports = CompanyUser;
```

I expect in my Controllers to be able to access
```
CompanyUser.get(...
```
but I don't.

then I have in my config directory I have a file models.js

```
module.exports.models = {
    foo: function(criteria, recordData) {
       foo...
    }
};
```
I expect in my Controllers to be able to access
```
CompanyUser.foo(...
```
but I don't due to CompanyUser being undefined but also if I explicitly call

```
sails.models.CompanyUser.foo(..
```
CompanyUser is now defined but there is no function foo

**Comment by tenzan** [comment]
+1

**Comment by sgress454** [comment]
> I expect in my Controllers/Services to be able to access
> 
> CompanyUser.get(...

`.get` is not a method on Sails models.

> The model that represent the relation cannot be access as a Global but it can be access through sails.models.modelName

If your model is not accessible as a global, it has nothing to do with it being a "relationship" model.  If it is saved in `api/models` and you have the `models` key in `config/globals.js` set to `true` (or commented out), it should be globally exposed.  If you're having an issue in your service file, make sure the code you're calling is _inside the service object or method_, not outside the `module.exports` declaration, since that code would get executed before things get globalized.

If none of this helps, please re-post with a link to your project and more info about your system so we can  try and recreate the issue!

**Comment by nicco** [comment]
So now I have to reopen the issue because i wrote Model.get(), I can change it, Model.find() it was a typo but the issue is still there. I have a quite big sails application and I'm calling other models everywhere with no problem, but when using the through relationship model is do get this issue.
