### ISSUE TITLE
Entity named "Controller" not working with blueprints

### ISSUE THREAD

**Issue by Bazze** [balderdashy/sails#3231]
Hello!

I have an entity in my application that is supposed to be called "Controller", however, the blueprints functionality doesn't seem to know how to handle it. With blueprints on, a model named `Controller` and a controller named `ControllerController` – `GET /controller` will return a 404.

How to reproduce:
```bash
$ sails new sails-test
$ cd sails-test
$ sails generate api Controller
$ sails lift

# From a different tab:
$ curl -v localhost:1337/controller
```

Am I doing something wrong or is this actually how it is?

**Comment by richdunajewski** [comment]
What you're doing appears correct, so it's possible that Sails doesn't like the name Controller. Consider it a reserved word.

I'm not sure if Sails could be easily modified to accept this controller name, but for now I would try an alternate name if possible.

**Comment by sgress454** [comment]
Sails bases a controller's "identity" (what you use to reference it in route configurations) off of the filename, so it removes "Controller" from that filename so that `PetController.js` translates to a controller identity of `pet`.  Looks like there's a bug where the removal logic is a little overzealous.  Luckily it's an easy fix!

**Comment by sgress454** [comment]
FYI in the meantime, until the next release of Sails comes out with the patch for this, you can just add `identity: "controller"` to your `ControllerController.js` file:
```
module.exports = {
   identity: "controller",
   ...rest of controller...
}
```
