### ISSUE TITLE
req.file function missing?

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#3266]
with mocha unit tests.
all previous working test cases get into this error which all have req.file function.

why?

**Comment by sgress454** [comment]
Are you talking about the Sails unit tests?  They're all passing for us.  Are you talking about unit tests for your specific app?  In that case we couldn't possibly know what the problem is.  You'd have to send links to your code as well as give us more specific info about the error and your version of Sails.

Please get some more concrete info (including reproducible steps that someone can take to recreate the error).  By the time you do that, you'll probably have found the issue in your code.  If not, try the [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and see if someone else has a similar problem or insight.  If it's coming up for others, and it looks like an actual bug in Sails core or an officially-supported submodule, please post back here with more info.
