### ISSUE TITLE
Using connection for session

### ISSUE THREAD

**Issue by phillee** [balderdashy/sails#3272]
I'd like to use a connection defined in sails.config.connections in sails.config.session. Is this possible?

**Comment by sgress454** [comment]
Hi @phillee -- just FYI, this forum is for reporting bugs in the Sails core.  In the future for support requests please visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
It's not possible at the moment to use configured connections for your session--but remember you can override configuration [on a per-environment basis](http://sailsjs.org/documentation/concepts/configuration#?environmentspecific-files-config-env), which at least gives you some flexibility.  If you really wanted to tie them together, you could use a variable for both, since the config files are still Javascript:
```
var myConnection = {
   adapter: 'sails-mongo',
   host: 'localhost',
   user: 'myUser',
   ...etc...
};

module.exports = {
    connections: {
       myConnection: myConnection
    },
    session: {
       adapter: myConnection.adapter,
       host: myConnection.host,
       ...etc...
   }
};
