### ISSUE TITLE
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### ISSUE THREAD

**Issue by CiscoKidxx** [balderdashy/sails#3277]
Sails v11.2
Node v12.4

When attempting to send over 500 json records as a post to a blueprint the connection is reset. Everything works perfect if I send less than 20 records.

Here is my controller:

    var Promise = require('bluebird');

    module.exports = {

	newRecord: function (req, res) {
		console.log(req)
		Agent.findOneById(req.query[0].agentId, function(err, agent) {
			var promises = [];
			_.forEach(req.query, function(record) {
				console.log(record);
				promises.push(Record.findOrCreate({userDN: record.userDN}, {
					name: record.name,
					faxPhone: record.faxPhone,
					email: record.email,
					cellPhone: record.cellPhone,
					guiLoginName: record.guiLoginName,
					userDN: record.userDN,
					location: record.location,
					did: record.did,
					owner: agent.id
				}));
			});
			Promise.all(promises)
			.then(function(records) {
				res.json(records);
			})
			.catch(function(err) {
				return res.negotiate(err);
			})
		});
	},

Here is how I am sending the POST:

    var postUsers = function(Users) {
      request.post({
        headers: {'content-type' : 'application/json', 'Content-Length': Buffer.byteLength(Users)},
        url: 'http://localhost:8000/api/record/newRecord',
        qs: Users
      }, function(err, res, body) {
        if (err) console.log(err);
      })
    }

**Comment by particlebanana** [comment]
You are sending it in the query string. The [maximum url length is around 2000 characters](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

You need to send that as a post body rather than a query string. Also best practices would say this endpoint should probably be paginated to prevent memory issues but start with the post body.
