### ISSUE TITLE
Default responses do not return JSON when req.wantsJson is true

### ISSUE THREAD

**Issue by s-devaney** [balderdashy/sails#3285]
Whilst the logic is in the default responses (forbidden, notFound, etc) which are generated using the generator, the res.jsonx doesn't set the content-header as application/json (just text/plain)

I have found that using res.json rather than res.jsonx sets the content header correctly, but I'm not sure if this is supported/best practice.

**Comment by sgress454** [comment]
Not sure I follow what you're saying about the default responses--they all set the content type to `text/html` or to nothing at all--but I can guess at the issue you're having with the (undocumented)  `jsonx` method.  If you look at its [implementation](https://github.com/balderdashy/sails/blob/stable/lib/hooks/responses/index.js#L204-L220), you'll notice two things: first, it doesn't accept `status` as an argument, and second, if `data` is not set, it just uses `.send()`, which won't set a content type for empty data.

Unless you need to support JSONP for your request, just use `.json`.  Otherwise, if you use `.jsonx`, just set the status code yourself:

```
return res.status(403).jsonx(myData);
```

As long as `myData` is defined, `.jsonx` should return a content type header.
