### ISSUE TITLE
pipeline.js absolute routes are not working as expected v0.11.2

### ISSUE THREAD

**Issue by Garethderioth** [balderdashy/sails#3308]
Hello,

When I use bower and put the following config on pipeline.js

```javascript
var cssFilesToInject = [
  '/bower_components/bootstrap/dist/css/bootstrap.css',
  'styles/**/*.css'
];
```

The pipeline is not detecting my boostrap file inside the **bower_components** so the file is not injected. The only way is changing to a relative path:

```javascript
var cssFilesToInject = [
  '../../bower_components/bootstrap/dist/css/bootstrap.css',
  'styles/**/*.css'
];
```

The problem is that in my layout.ejs is putting the same relative path.

```javascript
    <!--STYLES-->
    <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="/styles/importer.css">
    <!--STYLES END-->
```

The pipeline should put the correct relative path or just accept an absolute path.

**Note:** I have to move the **bower_components** folder inside the assets in order to work properly.

**Comment by sgress454** [comment]
> I have to move the bower_components folder inside the assets in order to work properly.

Exactly--any assets you want Sails to deal with automatically need to be in the `assets` folder.  If you need something more advanced, you can build your own Grunt task or come up with another solution entirely!

**Comment by vikeen** [comment]
@Garethderioth I ran into this issue and I made a small workaround for the problem. My assumption is that we should just hook into the sails pipeline. God knows I don't want to recreate it for a 1% problem.

My problem is that I want to leverage npm for all dependencies. Anything less is unacceptable for me. The same could be said for bower, but I just prefer npm. In order to do this I'm going to use `npm install` like normal, but intercept these npm dependencies during the sails asset pipeline.

tasks/config/copy.js
```js
grunt.config.set('copy', {
    dev: {
      files: [{
        expand: true,
        cwd: './assets',
        src: ['**/*.!(coffee|less)'],
        dest: '.tmp/public'
      }]
    },
    build: {
      files: [{
        expand: true,
        cwd: '.tmp/public',
        src: ['**/*'],
        dest: 'www'
      }]
    },
    jsDeps: {
      files: [{
        '.tmp/public/js/dependencies/jquery.js': './node_modules/jquery/dist/jquery.js',
        '.tmp/public/js/dependencies/bootstrap.js': './node_modules/bootstrap/dist/js/bootstrap.js'
      }]
    }
  });
```

Insert the new `copy:jsDeps` so that all build environments will run it.

tasks/register/compileAssets.js
```js
module.exports = function (grunt) {
  grunt.registerTask('compileAssets', [
    'clean:dev',
    'jst:dev',
    'less:dev',
    'copy:jsDeps',
    'copy:dev'
  ]);
};

```
Finally, in `pipeline.js` we code this exactly the same way as sails would expect us to.
```js
var jsFilesToInject = [

  // Dependencies
  'js/dependencies/jquery.js',
  'js/dependencies/**/*.js',

  // All of the rest of your client-side js files
  // will be injected here in no particular order.
  'js/**/*.js',

  // Use the "exclude" operator to ignore files
  // '!js/ignore/these/files/*.js'
];
```

This works as expected and, in my opinion, provides an elegant solution to using a package manager with sails that lives outside the `assets/` directory. 

However, *IMHO*, sails should be able to pull from `node_modules/` just fine though. Maybe I missed something with that? It is the default package manager for the language your platform is built on.

**Comment by jphillips05** [comment]
@vikeen is there a reason you chose to copy to the ./tmp folder instead of the ./assets folder?
