### ISSUE TITLE
sails-mongo usage in session.js gives me an error

### ISSUE THREAD

**Issue by angel1st** [balderdashy/sails#3312]
Hi there,
The below issue was originally reported by me in `sails-mongo` (see https://github.com/balderdashy/sails-mongo/issues/355), but @devinivy pointed me to report it here. 
Hopefully it will properly answered / handled at this place.
I would like to have persistent sessions and choose MongoDB for session store, since this DB is my project choice.
So I look at `config/session.js` and uncomment following lines:

       adapter: 'mongo',
       host: 'localhost',
       port: 27017,
       db: 'myDB',
       collection: 'sessions', 
I already have `sails-mongo` installed in my project, so I thought all is fine.

However, as long as I tried to lift the server, I have got following errors:

    error: A hook (`session`) failed to load!
    error: Could not load Connect session adapter :: connect-mongo

So my question is - why I cannot use already installed sails-mongo adapter for sessions?

If I miss something or you can tell me how to alter the code in order to start using `sails-mongo` instead of `connect-mongo` it would be nice.

Best Regards,
Angel

**Comment by alexanderzeillinger** [comment]
I have the same issue, a solution would be very welcome.

**Comment by tjwebb** [comment]
`connect-mongo` and `sails-mongo` are separate projects that do different things. If you simply `npm install connect-mongo --save`, sessions should work.

### connect-mongo (https://github.com/kcbanner/connect-mongo)

`connect-mongo` is an Express (http://expressjs.com/) plugin that supports storing sessions in MongoDB. This project is actually not related to Sails, except to the degree that Sails uses Express to manage sessions.

### sails-mongo (https://github.com/balderdashy/sails-mongo)

`sails-mongo` is a Waterline Adapter that enables you to use MongoDB with the Waterline ORM (included with Sails) as the persistence layer. `sails-mongo` is not used to store sessions, and is not related to `connect-mongo`

**Comment by angel1st** [comment]
Hey @tjwebb - I would not agree this should be closed. My main point was that it would be nice to re-use `sails-mongo` within the sails project, not than I am not able to install and use `connect-mongo` instead.
I believe redundancy has to be avoid and that was my actual question - How to avoid usage of two adapters which by their basic nature make the same thing: connect sails to MongoDB (yes, I know they do much more stuff, than that)?

**Comment by tjwebb** [comment]
> My main point was that it would be nice to re-use sails-mongo within the sails project

And my main point was that sails-mongo and connect-mongo and entirely different projects built for different reasons. Unification of these projects so that sails-mongo can be used for session management is not on our roadmap. If you'd like to do the work to unify them, a PR would be considered in the `sails-mongo` project.

**Comment by bakeruk** [comment]
I had the same issue when using `connect-mongo`.

I noticed under the error below...

```
error: A hook (`session`) failed to load!
error: Could not load Connect session adapter :: connect-mongo
```

...it said that `_.assign` was not a function. I looked into the source code and noticed it was being caused by code in the `connect-mongo` package when `stringify` was set to `true` in the `/config/session.js` file.

Set `stringify: false` and it works.

```
username: '',
password: '',
auto_reconnect: false,
ssl: false,
stringify: false   // <---- the fix
```

This is a work quick and small work around while this issue gets fixed

**Comment by mikermcneil** [comment]
@angel1st agreed- it would be nice to reuse Waterline adapters in lieu of connect session stores, and this is something I'm still interested in exploring in the future.  It's not an _incredibly_ difficult project, but it is quite time consuming.  It involves first determining the appropriate connect session adapter interface for our version of express.  After that, a mapping would need to be built in the session hook that calls create, update, or destroy (probably directly, rather than instantiating a waterline model, so avoid entanglement with the ORM hook).  It would also need to deal with initial connection setup.  

@bakeruk thanks for posting the workaround!

**Comment by mikermcneil** [comment]
@alexanderzeillinger @bakeruk @angel1st Actually, re what I just said, check out @dmarcelino's work on [connect-waterline](https://github.com/dmarcelino/connect-waterline)

**Comment by vishalbiradar** [comment]
@bakeruk I tried your trick, but still I am getting the same error.
I am executing the below command, to run sails app in production mode.
`$NODE_ENV=production npm start`

But getting,
Warning: connect.session() MemoryStore is not
designed for a production environment.
How to solve it ???

**Comment by wasif849** [comment]
error: A hook (`session`) failed to load!
error: Failed to lift app: Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
