### ISSUE TITLE
unable to overwrite sails.config.paths

### ISSUE THREAD

**Issue by japel** [balderdashy/sails#3346]
as stated in #3325 it is not possible to overwrite sails.config.paths as opposed to this readme:
https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/README.md

here an easy to test repo:

https://github.com/japel/sailsConfigPathsTest

files added:

./config/paths.js
```javascript
module.exports.paths = {
  "models": "api/my/new/models/path"
};
```
api/my/new/models/path/User.js
```javascript
module.exports = {

  attributes: {
    name: 'string',
    age: 'integer',
    active: 'boolean'
  }
};
```
how to test:

* clone
* npm install
* sails console
* > console.log(sails.config.paths);

outputs:
```javascript
{ models: 'X:\\sailsConfigPathsTest\\api\\models',
  tmp: 'X:\\sailsConfigPathsTest\\.tmp',
  config: 'X:\\sailsConfigPathsTest\\config',
  controllers: 'X:\\sailsConfigPathsTest\\api\\controllers',
  policies: 'X:\\sailsConfigPathsTest\\api\\policies',
  services: 'X:\\sailsConfigPathsTest\\api\\services',
  adapters: 'X:\\sailsConfigPathsTest\\api\\adapters',
  hooks: 'X:\\sailsConfigPathsTest\\api\\hooks',
  blueprints: 'X:\\sailsConfigPathsTest\\api\\blueprints',
  responses: 'X:\\sailsConfigPathsTest\\api\\responses',
  views: 'X:\\sailsConfigPathsTest\\views',
  layout: 'X:\\sailsConfigPathsTest\\views\\layout.ejs',
  public: 'X:\\sailsConfigPathsTest\\.tmp\\public' }
```

**Comment by japel** [comment]
Although, I was able to overwrite them using sailsrc file...

**Comment by mikermcneil** [comment]
@japel you're right-- by the time the userconfig hook runs (which loads the files in config/*) it's too late to change paths (because the moduleloader hook has already initialized in order to load the userconfig, whose path is also customizable. 

That's one of the main reasons I added sailsrc - to be able to inject config without having to modify your app.js file or use command-line flags.

I'll update the readme to clarify. Thanks for the detailed report.

**Comment by japel** [comment]
I see! Thank you for clarifying this.
Its really a pitty, that this is not possible... If this was possible, one could very easily create/separate APIs by some environment variable (e.g. for a customer specific API).
C'est la vie...
