### ISSUE TITLE
Confused about file uploading and storing

### ISSUE THREAD

**Issue by JoaoCnh** [balderdashy/sails#3368]
Hey 

I've just recently started using Sails and I'm enjoying it but I'm really confused about the file uploads structure.

I can upload the file. And if I upload it the default folder is .tmp/uploads but if I try to get it in a view I can't. Like '/uploads/etc'. 

If I set a custom folder (and I saw in several online posts and tutorials) they say that I should not save in the .tmp folder because it gets cleaned and that I should store it in the assets folder. So I do...

I can get the image on the view by '/images/etc..' buuut only if I restart the server because grunt will compile it and store so I'll have access.

So I'm confused. How the hell should I store it? So I can just access it in a view? (just for displaying)

**Comment by foobar8675** [comment]
If what you're uploading is supposed to be accessed by multiple servers, you'll want to save the file somewhere more centralized (since I'm using AWS, i store my uploaded files on s3) and generate urls based on the s3 path for viewing within a view.

**Comment by jdcauley** [comment]
@JoaoCnh I completely understand you confusion.

@foobar8675 is right, honestly the best way to deal with client uploads is using s3.

Have a look at Skipper and Skipper-s3 to handle your file uploads. https://github.com/balderdashy/skipper-s3

Otherwise, you might need to look at logic to copy your files to a more persistent directory.

Feel free to message directly or shoot me an email with more questions or to discuss your specific implementation
