### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by KirillSuhodolov** [balderdashy/sails#3391]
Hello, guys. Sorry if this issue can be inappropriate.
I am using sails.js and very happy with it, but recently, when deploying app I have issues with it. 
After staring project via forever or just via node app.js I see many running instances of application. After each request they increase used RAM.

![1 cores](http://dl2.joxi.net/drive/0006/3189/441461/151125/4c4b9d28c1.jpg)
![2 cores](http://dl1.joxi.net/drive/0006/3189/441461/151125/23b32ea1a6.jpg)

sails 0.11, nodejs 0.12, digitalocean

How can I find where memory leak at sails and second questions: how control number of running sails instances?

**Comment by wulfsolter** [comment]
Specify child instances in PM2 with fork/cluster mode and instance count to reduce the number of running app.js'. Maybe check out pm2-dev, made for developing.

http://pm2.keymetrics.io/docs/usage/cluster-mode/
http://pm2.keymetrics.io/docs/usage/application-declaration/

As for a "memory leak", I run a few pretty large Sails instances and know of no leaks on current stable release. Sometimes Node's GC takes a while to run, but if you have a leak it's not due to Sails. See https://github.com/balderdashy/waterline/issues/1180 and
https://github.com/soyuka/nodejs-http-memtest

**Comment by KirillSuhodolov** [comment]
@wulfsolter thanks for response, will dig deeper.

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here:
https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
