### ISSUE TITLE
[enhancement] API reference versioning

### ISSUE THREAD

**Issue by japel** [balderdashy/sails#3412]
Hey guys,

it would be great if the reference documentation was versioned.
People still using sails 0.11.x are probably trying to do things like this:
http://sailsjs.org/documentation/reference/blueprint-api/add-to
but that only works on 0.12.x and is never mentioned.

Best regards

japel

**Comment by sgress454** [comment]
Hi @japel.  The current documentation is always for the latest stable version (currently v0.11.3).  The documentation you linked to should work in v0.11.x; if you're having an issue with it please reach out (with more details about your specific issue, including relevant code) in one of our support forums like the [Google Group](https://groups.google.com/forum/#!forum/sailsjs), our [online chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).

**Comment by japel** [comment]
@sgress454 I see. But what is the point of this github issues then?
I will post an issue on those blueprints, because they are not working on 0.11.x and as you say, they should work. But you want me to post this on google group, online chat or stackoverflow?

Still: Any kind of API reference versioning would be a very good idea.

**Comment by sgress454** [comment]
@japel The Github issues are for reporting bugs on the Sails core.  The blueprint you mentioned passes tests for v0.11.x, and I was able to use it with my v0.11.3 test site without any issues.  It's certainly possible that you have uncovered a bug.  However in most cases where something isn't working as expected, it's a problem in the userland code, so we encourage you to post your issues in a forum meant for user support first before declaring it a bug and posting here.  That having been said, we are committed to keeping Sails bug-free, so if you had posted an issue under the heading "Add blueprint fails to work in Sails v0.11.x" with a detailed description of the problem and some sample code, I would have left that open.

Re: API reference versioning, I'm with you.  We've only had two major releases since putting the new docs site up.  If you ever need docs for v0.10.x, you can find them in the docs repo: https://github.com/balderdashy/sails-docs/tree/0.10

**Comment by japel** [comment]
@sgress454 I see, thank you for clarifying.
