### ISSUE TITLE
Same custom validation rule in different model in conflict

### ISSUE THREAD

**Issue by mikaelcom** [balderdashy/sails#3425]
Sails version: 0.11.2

My models:
- `Community`, with a custom validation rule named `valid_type` for the attribute named `type`
- `Device`, with a custom validation rule named `valid_type` for the attribute named `type`

When the `create` method is called, the `valid_type` used to validate `Community`.`type` attribute is the `Device`.`valid_type` rule.

Tests:
- If I rename the type attribute to `_type`, it has no effect
- If I rename the validation rule in `Community`, `validType` for example, then it works

**Comment by mikermcneil** [comment]
@mikaelcom :boom:  :banana:  is on the case

**Comment by particlebanana** [comment]
Yup so the types aren't namespaced in any way. They are all merged together just due to the way Anchor is built. When the validations get loaded each custom rule is added to the rule definition list and in this case the last one in overrides the previous defined ones.

This would be solved by moving to a different validation library such as [JOI](https://github.com/hapijs/joi) in the future or re-tooling the way anchor rule definitions are instantiated. For now you should be able to add a namespace to the validations to ensure the correct one is ran.

**Comment by mikermcneil** [comment]
@mikaelcom thanks for bringing this up. Is there any particular spot in the Sails documentation you reckon we could improve to help save time for others running into this problem in the future?

I figure the best place to include a note about this is under Custom Validation Rules.

**Comment by mikaelcom** [comment]
Is there any workaround? Do you have a one or we just have to avoid such an usage?

I think it would be good under the Custom Validation Rules section yes,

thx anyway

**Comment by mikermcneil** [comment]
@mikaelcom This is just my opinion, but in practice, I've found it more flexible and consistent to write complex custom validations using services or machines and calling those helper functions before updating or creating models (this is since inevitably as an app matures, you almost always end up setting up validations which you want to see observed for _some_ updates and creates, but not others).  Additionally, custom validations (asynchronous or not) end up causing more confusion/spiderweb code in your app than they solve.

This brings up a bigger issue: despite Sails and Waterline being opinionated frameworks, historically our team has done everything we can to make its features flexible for different users' needs.  In the past, I haven't done as good a job as I should of pushing back on these kinds of requests based on my personal experience.  As I discuss in the updated contribution guide, one of the key sources of friction in open-source development is the ping pong of pull requests submitting new code and project maintainers not necessarily agreeing with the code but feeling [guilty](https://www.youtube.com/watch?v=UIDb6VBO9os) and merging it anyway (and for good reason-- it _really_ sucks getting your PR closed.  I know the feeling!  And tempers can rise and it becomes frustrating).  The contributor who originally submitted the code has the best intentions, but no matter how enthusiastic someone is, _they are just never going to be responsible for the long-reaching implications_ of the code they submit.  And so project maintainers end up getting stuck maintaining features that don't fit with the experience or vision of the project-- and which they may even dislike personally.  I've come to the conclusion that this is where a lot of the issues with burnout originate from in open source projects in general, and it can cause development to stall.

Unfortunately, I think custom validation rules is one example of a time where we did the community a disservice by merging support for the feature in the first place.  Since custom validations are _here now_, we will continue to support them as currently implemented.  And going forward, I'm open to discussing different ways to solve this-- but I just want to make it clear that this feature has never been used by our core team, I don't really think it's the best way to structure your app, and that I am eyeing custom validations for the chopping block for Sails v1.0.

**Comment by mikaelcom** [comment]
What a speech! :+1: 

As I'm not an expert, I'll be glad to to it the right way. So I understand well what you're saying, I should implement my own validation rules in the beforeCreate/beforeUpdate/etc. hooks instead of using custom validations rules? If so, I'll do! If not, teach me :wink:,

Thx for all.

**Comment by mikermcneil** [comment]
@mikaelcom thanks for being flexible.  So yep, that would work- although I'd suggest that you might even go a step further and pull them out into a service method that you can call yourself manually (I've found that we sometimes end up browserifying that code down the line and using it for client-side validations, for example).  So that way, whether it's from your lifecycle callbacks (e.g. beforeCreate) or from scheduled jobs or custom scripts or anywhere else in your app, you can always run the custom validation logic.

Those [services](http://sailsjs.org/documentation/concepts/services/creating-a-service) are conventionally written as dictionaries of functions, and conventionally use one (`options`) or two arguments (`options, cb`) -- that convention is where the machinepack spec came from.  As far as whether to access those services via globals or using require, and _when_ to pull logic out into a service-- I think that's a personal choice based on the stage your project is at.  But a general rule of thumb that has served me well (that I learned from @kentongray) is that you should avoid making things reusable until you've _already written_ the same code (or almost exactly the same code) in **3 different places**.  This doesn't take any more time up front, but it does create a few moments of precipitous duplication.  For me at least, I think it's worth it, because it gives you confidence that your architectural decisions are based on that actual needs of your app.

**Comment by mikaelcom** [comment]
Thanks again, I created lots of services already so I totally see your concerns and your ponit of view that I'll try apply even more.

Keep the good work anyway that has saved me a lot of time already too.

**Comment by kentongray** [comment]
thanks for the shout out! :blush:

**Comment by mikermcneil** [comment]
@mikaelcom awesome, sounds like you're on the right track :)

@kentongray haha no problem- sorry for blowing up your inbox!

**Comment by mikermcneil** [comment]
@mikaelcom spent this afternoon doing a pass at improving our validation docs:  https://github.com/balderdashy/sails-docs/blob/master/concepts/ORM/Validations.md    The validations table in particular could still use some work, but the rest of it is looking a lot better I think. I added some additional content re: ["When to Use Validations"](https://github.com/balderdashy/sails-docs/commit/ddd2ab61e2eb5be16705eefe62991860ac9dc8d5) and the ["Unique" constraint](https://github.com/balderdashy/sails-docs/commit/a2719c172e7a805cbb47a43fa826cddd8897040c).  I also fleshed out the custom validation rules section a bit more and added a warning about the future changes we discussed here.

If anyone reading this has a few minutes to proofread and/or help clean up the ["Validation Rules" table](https://github.com/balderdashy/sails-docs/blob/master/concepts/ORM/Validations.md#validation-rules), I'd greatly appreciate it ^_^

**Comment by mikermcneil** [comment]
Btw if anyone is interested in sending a PR finishing the job, I added a new column "Attribute Type" to the table to represent the attribute `type`s that are compatible with each of the various validations.  The rows I updated in the "What It Checks" column are those which start with `Ensure the incoming value...`  (I'd like to emulate that for the others if possible).  Thanks!

**Comment by mikermcneil** [comment]
For reference: In Sails v1, you can use the `custom: function(){ }` validation rule to achieve this (see https://github.com/balderdashy/sails-docs/blob/e7901e280c1e48ebac539009597dcaa54d4b4dff/concepts/ORM/Validations.md#custom-validation-rules for an example)

**Comment by mikermcneil** [comment]
See also https://github.com/balderdashy/sails/issues/3459#issuecomment-344640065
