### ISSUE TITLE
loadhooks.js issue

### ISSUE THREAD

**Issue by martingg88** [balderdashy/sails#3434]
any idea for this issue that loadhook.js is loaded first before any config files in version 0.11.3.

the order of loading may cause the following config doesn't work.

module.exports = {

  hookTimeout: 40000

}

**Comment by sgress454** [comment]
`loadHook` is loaded before the config files because the config files are themselves loaded via a hook.  This means that if you set `hookTimeout` in a config file, it will not be in effect when the first two core hooks (`moduleLoader` and `userConfig`) are loaded, but will be in effect for all of the other hooks.  If for some reason you need the timeout to be configured for those first two hooks, you can set it in the [.sailsrc](http://sailsjs.org/documentation/anatomy/my-app/sailsrc) file or using a `sails_hookTimeout` environment variable on the command line.

**Comment by martingg88** [comment]
Thanks. But can you give me a configuration sample for .sailsrc and sails_hookTimeout?

**Comment by sgress454** [comment]
In the `.sailsrc` file:
```
"hookTimeout": 40000
```

On the command line:
```
sails_hookTimeout=40000 sails lift
```

**Comment by martingg88** [comment]
thanks.
