### ISSUE TITLE
how to configure using environment variables

### ISSUE THREAD

**Issue by shaunc** [balderdashy/sails#3442]
[The docs](http://sailsjs.org/documentation/concepts/configuration) say that sails can be configured using environment variables.

How are environment variable names mapped to configuration keys? I can't find it in the code. Perhaps it is missing?

**Comment by ericnograles** [comment]
@shaunc The environment-specific configurations are found under /config/env.  Each file will basically correspond with a matching NODE_ENV environment variable name.  For example, dev.js will be used if you have a NODE_ENV of dev.  hth

**Comment by sgress454** [comment]
@shaunc thanks for pointing this out--the docs do seem a bit mysterious on this point.  

What @ericnograles is referring to is the ability to create _environment-specific_ config files, so that if you lift Sails with `NODE_ENV=dev sails lift` it will read from the `config/env/dev.js` file as well as any files under a `config/env/dev` subfolder, and merge the values into `sails.config`.  

However, it is also possible to set `sails.config` values _directly_ using environment variables, by prefixing the config keys with `sails_`.  For example:

```
sails_foo=bar sails lift
```

will lift Sails with `sails.config.foo` set to `bar`.  You can also set values in nested dictionaries by using double-underscores.  A more real-life example:

```
sails_cors__origin="http://localhost:1492" sails lift
```

will lift Sails with `sails.config.cors.origin` set to "http://localhost:1492".

I'll go ahead and add this to the docs.

**Comment by shaunc** [comment]
Ah — great!

In my case I wanted to temporarily extend hook timeout so I could debug something while hook loading. I wanted to avoid code changes to accomplish this. I can imagine that environment variables would be useful in some deployment environments as well.

— Shaun
