### ISSUE TITLE
Saving one to one associations when creating a model

### ISSUE THREAD

**Issue by fordg** [balderdashy/sails#3445]
I'm trying add associations when a model is created when certain conditions are met however the associations aren't being created.

```javascript
module.exports = {
    schema : true,
    attributes: {
        name          : { type : 'string', required   : true },
        basePrice     : { type : 'float' , required : true },
        category      : { model : 'Category'},
        attributes    : { type : 'object' },
        published     : { type : 'boolean', defaultsTo: false }
    },
    afterCreate: function(product, next){
        var variants = [],
            create_variant_tasks = [],
            attributes = product.attributes;

        if(!attributes) return next();

        variants  = generateVariant(attributes,{
            product : product.id,
            store : product.store
        });

        // save to db
        if(product.category.name == 'custom'){
            _.each(variants,function(variant){
                create_variant_tasks.push(
                    ProductVariant.create(variant)
                );
            });

            Promise.all(create_variant_tasks)
            .then(function(){
                next();
            })
            .catch(function(error){
                next();
            });
        }else{
            ProductAsset.create({
                'product':product.id,
                'store':product.store
            })
            .then(function(){
                next();
            })
            .catch(function(error){
                next(error);
            });
        }
    }
};
```
In my category model, category has collection product and in that collection has a value called custom so when I want to choose product with category custom, it will insert data to ProductAsset model but data doesn't insert to database. How to fix my code guys ? :(

**Comment by sgress454** [comment]
Hi @fordg, thanks for using Sails!  This forum is for reporting bugs in the Sails core.  For support questions like these, please use our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).  
<hr/>
In your case I'm guessing the issue is that the `product` object you get in `afterCreate` isn't _populated_, so `product.category` is just an ID, not an object with a `name` property.  Thus, `product.category.name` will never be `custom`.  You can do some `console.log()` messages in your code to confirm this, and if it's the case, you'll want to do a `Category.findOne(product.category)` in that code to get the full category object before running the rest of the code.
