### ISSUE TITLE
process.execArgv not being passed to children

### ISSUE THREAD

**Issue by Bamieh** [balderdashy/sails#3450]
process.execArgv not being passed to grunt tasks
CLI command: 
```
sails lift --foo="baz"
```
Grunt file:
```
module.exports = function(grunt) {
    console.log("process.execArgv ", process.execArgv); // empty array: []

    console.log("--foo: ", grunt.option('foo')); //undefined

    console.log("process.argv: ", process.argv);
        /*
           [ '/usr/local/bin/node',
             '/Users/bamieh/Bamieh/TheShip/node_modules/sails/lib/hooks/grunt/grunt-wrapper.js',
             'default',
             '--pathToSails=/Users/bamieh/Bamieh/TheShip/node_modules/sails',
             '--gdsrc=/Users/bamieh/Bamieh/TheShip/node_modules/sails/node_modules' 
            ]
        */
}
```

I am unable to capture the execArg in any way, although it should be passed 
on line 137 in lib/hooks/grunt/index.js
https://github.com/balderdashy/sails/blob/master/lib/hooks/grunt/index.js#L137

any ideas?

**Comment by sgress454** [comment]
You're misunderstanding how `execArgv` works here--it's an easy mistake to make.  `process.execArgv` contains the command-line options of the _parent process_.  In the case of Sails, that's Node itself.  So if you started your app with:

```
node --harmony app.js --silly
```

then `process.execArgv` would be `['harmony']` (notice the absence of `silly`).  That's what would then be passed down to the Node executable when it forks Grunt, so that `process.execArgv` in the Gruntfile would also be `['harmony']`.  It has nothing to do with the command-line options that _Grunt_ gets, and there's no way to pass `--foo=bar` this way, since `--foo` is not a valid command-line argument for Node.

If you're looking to pass some info along to your Gruntfile, you can use environment variables.  For example:

```
foo=bar sails lift
```

will come through in your Gruntfile as `process.env.foo`.

**Comment by Bamieh** [comment]
@sgress454 ahh indeed this is what i am currently doing, however there is no way to get the passed parameters through lifting sails?
