### ISSUE TITLE
keepResponseErrors Not working

### ISSUE THREAD

**Issue by vagnernascimento** [balderdashy/sails#3454]
Hi, Im trying to put my app in production mode but I need the response errors working. I already tried the option keepResponseErrors: true (config/env/production.js) but not work.
I updated my application to Sails 0.11.3 but have the same issue. Any idea?
Thanks,

**Comment by mikermcneil** [comment]
@vagnernascimento does your app currently have an `api/responses/` folder?  It could be that a local copy is overriding the implicit default responses baked in core.  Here's the spot in core where that check is performed: https://github.com/balderdashy/sails/blob/master/lib/hooks/responses/defaults/index.js#L21

**Comment by sgress454** [comment]
@vagnernascimento `keepResponseErrors` is a feature introduced in the upcoming v0.12 release--apparently it mistakenly made its way into the docs early.  Sorry about that!

The good news is that we just published a new version of the generator module that creates those response files, and since v0.11.x uses the same generator you should be able to get the newest code.  You'll need to re-install Sails for it to work.  To be sure, I'd do:

```
npm cache clean
npm uninstall -g sails
npm install -g sails
```

(you can leave off the the `-g` if you're installing Sails directly into your project).
