### ISSUE TITLE
Grunt memory issue. 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [balderdashy/sails#3468]
I got a tiny server with 512Mb of memory, so I noticed issue about grunt.
After running the sails app Grunt is left in processes and uses 27% of memory which is about 140Mb.
I killed it  and server continued to work fine. What's the point to run grunt after build is finished?
Is there an easy way to fix it?

![screen shot 2016-01-07 at 16 49 48](https://cloud.githubusercontent.com/assets/4464561/12172009/2c9d9c0c-b55f-11e5-88c5-6ed3a7bd0316.png)

**Comment by mikermcneil** [comment]
@AlexanderKozhevin Hmm, are you running your app in development?  That's the only reason the Grunt child process should be hanging around if you're using the default asset pipeline (because of the Grunt watch task).  Be warned: your mileage may vary (completely depends on what Grunt tasks you're using).

I recently did a relatively thorough pass at documenting the Grunt hook in case that's helpful: https://github.com/balderdashy/sails/tree/master/lib/hooks/grunt

**Comment by mikermcneil** [comment]
Here's where the grunt hook handles the "exit" event from the Grunt child process if you're running your app in production mode: https://github.com/balderdashy/sails/blob/master/lib/hooks/grunt/index.js#L272

In development, the hook's [initialize callback](https://github.com/balderdashy/sails/blob/master/lib/hooks/grunt/index.js#L79) is triggered almost immediately after the child process _fires up_, versus waiting until it exits (because it is assumed you might be running grunt-contrib-watch and/or other background tasks).

**Comment by AlexanderKozhevin** [comment]
Yes, you right. My fault. I was running app in ***development*** env. 
In ***production*** grunt exits right after build. 
@mikermcneil , Thanx a lot!

**Comment by mikermcneil** [comment]
@AlexanderKozhevin :+1:  no problem at all- been there myself.
