### ISSUE TITLE
coffeescript support

### ISSUE THREAD

**Issue by t1djani** [balderdashy/sails#3479]
Is there a way to work with coffeescript in sails ? i've tried [#sails-generate-new-coffee](https://www.npmjs.com/package/sails-generate-new-coffee) but it not seem to work for me for compiling my coffeescript controllers and models.

Any Issue ?

**Comment by mikermcneil** [comment]
Hi @t1djani, we'll dig into this as soon as possible.  In the mean time, have a look at https://github.com/balderdashy/sails/issues/2262 if you haven't already.  Thanks!

**Comment by mikermcneil** [comment]
(see also https://github.com/balderdashy/sails/issues/1544)

**Comment by mikermcneil** [comment]
@konstantinzolotarev I know you were [working on this](https://github.com/balderdashy/sails-generate-new/commit/f791f9a6660c3836befe31682b1ce896ae36ff5f) in `sails-generate-new` -- would you mind chiming in on the current status?  I know this was working previously, but as @sgress454 has pointed out in the past, since we're not actively using CoffeeScript ourselves, we don't have an everyday test case like we do with most of the rest of Sails.

@t1djani There has been a lot of entropy when it comes to CoffeeScript in the generator code base for a long time, so I'd like to either stabilize and finish that up or rip it out of core.  Obviously, it would be preferable to maintain support in core, and I have nothing against this feature, but I'm only willing to keep it around if someone who is actively using CoffeeScript in their Sails apps is willing to help get this 100% stable and tested.  Does that make sense?

Thanks guys.

**Comment by leosuncin** [comment]
Hello @t1djani, I use Coffeescript for write code for my controllers, models, services, etc. I will tell you how in your project do the next steps:
 1. Install locally coffeescript and save it in your package.json  
 ```npm install --save coffee-script```
 2. Install generators for coffeescript (optional)  
 ```npm install --save-dev sails-generate-controller-coffee sails-generate-model-coffee```

Thats it, now you can write your code using coffeescript, even config files of sails

**Comment by mikermcneil** [comment]
Thanks for posting your solution, @leosuncin.  If you have a moment, would you mind adding a "Notes" section to http://sailsjs.org/documentation/reference/command-line-interface/sails-generate via a PR editing this page in [sails-docs](https://github.com/balderdashy/sails-docs/blob/master/concepts/0home/0home.md)?  I think this would be a great addition to the official documentation.

**Comment by leosuncin** [comment]
Added pull request https://github.com/balderdashy/sails-docs/pull/617

**Comment by mikermcneil** [comment]
@leobudima thank you!  :+1:
