### ISSUE TITLE
npm install fails when updating from 0.11.0 to 0.11.4

### ISSUE THREAD

**Issue by fc7** [balderdashy/sails#3483]
sails 0.11.0 is already installed under /usr/local/lib/node_modules (on a Mac). 
Running `npm install sails -g` ends up with this error:
```shell
$ npm install sails -g
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.

> sails@0.11.4 preinstall /usr/local/lib/node_modules/.staging/sails-40c17dc7
> node ./lib/preinstall_npmcheck.js

Sails.js Installation: Checking npm-version successful
- maxmin node_modules/sails/node_modules/grunt-contrib-cssmin/node_modules/maxmin
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install" "sails" "-g"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! path /usr/local/lib/node_modules/.staging/colors-215a0c71
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-215a0c71' -> '/usr/local/lib/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/colors'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-215a0c71' -> '/usr/local/lib/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/colors'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     ./npm-debug.log
npm ERR! code 1
```

After uninstalling 0.11.0 the installation of 0.11.4 went fine. Probably this is a npm issue?

**Comment by sgress454** [comment]
@fc7 glad you got it worked out.  Hard to say for sure what the issue was, and it doesn't sound like you'll be able to reproduce it now.  In the future, I suggest always doing clean installs with:

```
npm uninstall sails
npm cache clean
npm install sails
```

Starting from a clean slate gives NPM the highest likelihood of success!

**Comment by AlexVentura** [comment]
I have a similar error working with the latest version:

**Sails version**: 0.12.1
**Node version**: 5.8.0
**NPM version**: 3.7.3
**Operating system**: MacOS X El Capitan 10.11.3

I was working with Sails v0.11.2 and my project was going well even since the installation I have no problems with anything.

***Now I upgrade my OS from 10.11.2 to 10.11.3, I formatted my HD and install everything from scratch*** I have installed Node from the package that the [official website](https://nodejs.org) provide. Every thing was ok, so then, I tried to install Sails using the command:

`sudo npm install sails -g`

After some seconds the console show the next errors:

<img width="682" alt="screen shot 2016-03-14 at 5 42 08 pm" src="https://cloud.githubusercontent.com/assets/13169164/13763559/993a5dbe-ea0c-11e5-87f9-eca723126269.png">


**Can anybody could help me out with this?**
**I uninstalled NodeJS an install it all over again but I got the same error.**
