### ISSUE TITLE
Inconsistencies in publishAdd() function vs. documentation

### ISSUE THREAD

**Issue by rasapetter** [balderdashy/sails#3487]
It's unclear whether the published messages will/should include the added model instance or not.

Looking at the [code](https://github.com/balderdashy/sails/blob/master/lib/hooks/pubsub/index.js#L878) we can see that the function accepts (as the third argument) either a complete model instance or its pk value. If a model instance is provided, it will be included in its entirety in the published message in a property named `added`. On the other hand, if a pk value is provided as the third argument, the `added` property will not be included in the message.

While it can be very handy to get the model instance in the published message, it is inconsistent with both the [public documentation](https://github.com/balderdashy/sails-docs/blob/fc2d3c4e2beabc82a3203cbf25000e31df1982a8/reference/websockets/resourceful-pubsub/publishAdd.md) and even with the function's own description comment (at least to some extent, the argument's name indicates that it accepts a pk value).

What is the intended behavior here? Can we rely on `added` being available if we use `publishAdd()` with model instances?

**Comment by mikermcneil** [comment]
Hey @rasapetter, thanks for bringing this up; and especially for taking the time to put together these links.  The pubsub docs are perhaps the most badly in need of help out of all of our reference docs (both from a content/consistency perspective as well as formatting-- i.e. we've since shifted many of the other doc pages to use the [new layout for method reference pages](http://sailsjs.org/documentation/reference/web-sockets/sails-sockets/sails-sockets-blast)).

> What is the intended behavior here? Can we rely on added being available if we use publishAdd() with model instances?

That's correct-- if you provide a dictionary to `publishAdd()`, it should include that data as `added` in the broadcast.  Looping in @sgress454 in case there's anything he can add.

**Comment by rasapetter** [comment]
Splendid. Thanks!

**Comment by mikermcneil** [comment]
@rasapetter alright- got this into the docs on master this afternoon (see backlink injected by github above).  It's not on the website yet, but if you wouldn't mind taking a look over the latest contents of the file on master in sails-docs to look for anything else helpful we might want to add, I'd appreciate it.
(the reference pages for the other resourceful pubsub methods are in desperate need of some cleanup too, but figured we'd get this one nice and shiny first)

**Comment by mikermcneil** [comment]
This issue was moved to balderdashy/sails-docs#627
