### ISSUE TITLE
Sails apps cannot use hooks published to npm as namespaced modules

### ISSUE THREAD

**Issue by lennym** [balderdashy/sails#3502]
I was trying to load a custom hook from my own npm namespace by installing it from npm from `@lennym/sails-hook-sockets`, but because this installs into `./node_modules/@lennym/sails-hook-sockets` it is ignored by Sails.

I'd propose swapping some of this code (https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L399-L407) for something that instead reads the app's package.json for dependencies, and then uses `require.resolve('<module>/package.json')` to read their `pacakge.json` files.

**Comment by lennym** [comment]
Note: workaround is obviously to put the following in ./api/hooks/sockets.js:

```javascript
module.exports = require('@lennym/sails-hook-sockets');
```

It's just a little bit of a hack, and it's be nicer if it "just worked".

**Comment by mikermcneil** [comment]
Thanks for the heads up @lennym- and for posting the workaround.  I was just looking at a similar issue re: adapters in the orm hook.  We'll look at it for hooks asap.  If anyone has time to submit a PR for this, that'd be awesome.

> I'd propose swapping some of this code (https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L399-L407) for something that instead reads the app's package.json for dependencies, and then uses require.resolve('<module>/package.json') to read their pacakge.json files.

:+1:

**Comment by lennym** [comment]
Thanks. I'll see if I can put together a PR today if I get some time.

**Comment by Salakar** [comment]
@mikermcneil  @lennym  - I believe it's just the regex [here](https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L436) that needs changing to:

```
/^(sails-hook-)|(@.+\/sails-hook-)/
```

Here's a regex101 of it: https://regex101.com/r/lC8sM4/1

**Comment by lennym** [comment]
@Salakar That does not match my understanding from reading the code, which is that the code point you linked to will not be reached at all, because the module in question will never be recursed over, since it does not sit directly in a child directory of `./node_modules` with a package.json file at `./node_modules/<modulename>/package.json`. I will admit to not having debugged the code fully yet to establish this though.

However, I think my approach would be a better one in the long term anyway, since it does not place any dependency on the install location of modules, and so will better support both npm3 environments, or cases where sails apps are loaded as dependencies of other projects (this is actually our current use case, and part of my motivation for this work) and modules may have had their install locations de-deduped up the tree. My feeling generally is that Sails should avoid anywhere traversing/inspecting the `./node_modules` directory, and should always consider `package.json` and `require[.resolve]` as the canonical source for installed modules and their installed locations.

**Comment by lennym** [comment]
@Salakar I've tested this at both `sails@0.11.4` and `sails@0.12.0-rc6` and neither return user-scoped modules with the [results from the node_modules directory traversal here](https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L407)

**Comment by mikermcneil** [comment]
@Salakar @lennym thanks y'all.

@lennym re `flattenNamespacedModules` -- correct- that's a workaround for when NPM released private packages. We'll get a fix for this working on master first, then bring it back for a 0.11.x patch (@sgress454 do you think you can take point on that?)

**Comment by sgress454** [comment]
@lennym re:
> I'd propose swapping some of this code (https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L399-L407) for something that instead reads the app's package.json for dependencies, and then uses require.resolve('<module>/package.json') to read their pacakge.json files.

The reason why the hooks loader wasn't implemented this way is that it requires you to always do `npm i --save` (or manually add packages to your package.json after installing).  If you're just installing a hook just to try it out in your project, you don't want it listed in your `package.json` where you are likely to forget about it.  Plus, every hook would have to have its installation instructions say `npm install <hook name> --save`, which is a bit odd.  

It sounds to me like @Salakar hit on the real issue here--at least since the `flattenNamespaceModules` method appeared, there should be no problem with your hook loading, just with the internal name it's being given.  The regex fix sounds correct.  There's also a configuration setting you can put in your package.json (apparently undocumented, but I'll go and fix that): `sails.hookName`.  If you set a value for the `hookName` property in the `sails` dictionary of your hook's package.json (alongside `isHook: true`), then the loader will use that name internally for the hook.  For instance, if you had:

```
"sails": {
   "isHook": true,
   "hookName": "sockets"
}
```

in your package.json, the hook would be loaded into `sails.hooks.sockets` (replacing the default).

**Comment by mikermcneil** [comment]
@sgress454 thanks for adding `hookName` to the docs.  We redeployed sailsjs.org and it just cleared cloudflare [here](http://sailsjs.org/documentation/concepts/extending-sails/hooks/installable-hooks#?specifying-the-internal-name-sails-uses-for-your-hook-advanced).

@lennym @Salakar We could make the hook identity a required property in the hook spec.  But still, in the mean time, since Sails core is currently handling the inference of hook identity from package names, we should support the latest and greatest from NPM there.

**Comment by sgress454** [comment]
Merged in #3514, and added some more tests including tests for the `hookName` config and for saving hooks in namespaced folders.  Thanks @lennym and @Salakar for the help!

**Comment by luislobo** [comment]
We've been using private npm modules and hookName with no issues.

**Comment by mikermcneil** [comment]
@luislobo :+1: thanks for the update!
