### ISSUE TITLE
While we wailt express 5

### ISSUE THREAD

**Issue by udanpe** [balderdashy/sails#3562]
I dont understand why you write so big and hard code, rewrite express function and after don't can update it.

```
/app.js
var app = require('express')();
app.use(require('./config/controllers').init);
app.listen(3000);
```

```
/config/controllers.js
module.exports = {
  init: function (req, res) {
    var routes = require('./routes');
    var controller = routes[req.method + ' ' + req.path];
    if(controller){
      controller = controller.split('.');
      global[controller[0]] = require('../controllers/' + controller[0]);
      global[controller[0]][controller[1]](req, res);
    } else { res.sendStatus(404); }
  }
};
```
```

/config/routes.js
module.exports = {
    'GET /': 'HomeController.index',
    'GET /login': 'HomeController.login'
};
```

```
/controllers/HomeController.js
module.exports = {
  index: function(req, res) {
    res.render('index', {title:'title'});
  }
};
```
+gulp
+waterline
+CLI

and we have almost sails

maybe better write only middleware for use with express
middleware always have req res next and not change
and all free time integrate most popular modules

sails add passport (generate config and npm install)
sails add nodemailer
sails add validation (sails-hook-validation can stop support any time)

i try see sails code and don't understand why all so hard.
sails 0.12.0 have 150mb modules
express only 1.5mb + 3.5mb other main modules
pm2 monit  show x5-x10 more load cpu and usage memory then express
something went wrong)

or if you want use only express routes maybe better write your own routing and not write and download any exces

**Comment by mikermcneil** [comment]
@udanpe I appreciate you taking the time to post, but our GitHub issues aren't the place for debating the merits of full featured vs lightweight frameworks vs rolling your own. If you have specific implementation changes you'd like to see in core, we have a well documented proposal process for that (see the contribution guide in this repo). However, as I've mentioned [to you before](https://github.com/balderdashy/sails/issues/3474#issuecomment-170182945), it seems we've reached a bit of an impasse. Responding to your past issues has demanded a lot of my time, yet you've mentioned you were not using Sails, so I'm a bit puzzled why you are posting here at all.  Please carefully read our contribution guide and code of conduct before participating in the future. Thanks!

**Comment by sgress454** [comment]
> Just do [x, y and z] and we almost have Sails

@udanpe Spoken like someone who has never tried to write a large-scale distributed application using a low-level framework like Express!  Don't get me wrong--Express is great at what it does.  That's why we use it as the backbone of Sails, and why we're continuing to support the efforts of people like @dougwilson who are building and maintaining the components in [PillarJs](https://github.com/pillarjs).  But once you start building something really big and juicy, you'll find yourself writing and rewriting those x, y and z parts (policies, blueprints, responses, pub/sub, etc. etc.) and presto, you've built your own one-off web framework.  Or you could use something like Sails (built, maintained and used by a large community) and spend all that extra time on your app code (the stuff that really matters).

If you're concerned about Sails' footprint, you'll be happy to know that our plan for Sails 1.0 is to move more and more core functionality into separate repositories, allowing for custom builds of the framework (kind of like how you can have custom builds of jQuery).  The proposal and the excellent subsequent discussion is [readily available for viewing](https://github.com/balderdashy/sails/pull/3504) in our PRs section.   As @mikermcneil states above, if you have a concrete proposal for how to make Sails better, that's the place (and the way) to do it.

On the other hand, if you don't have constructive comments and just want to vent about how this particular framework, out of the many pieces of software available, doesn't meet your expectations, might I suggest a [blog](http://wordpress.com/)?
