### ISSUE TITLE
Unexpected deprecation message on `Model.watch()`

### ISSUE THREAD

**Issue by ljacques** [balderdashy/sails#3563]
Model.watch(req) print a debug message :

debug: sails.sockets.id() is deprecated; use sails.sockets.getId() (see `http://sailsjs.org/documentation/concepts/upgrading/to-v-0-12`)

**Comment by mikermcneil** [comment]
Thanks @ljacques - there's a fix in place on master and we'll be removing this message in a patch release this week (`.watch()` formerly called `.id()` instead of `.getId()` and we forgot to switch it over during the upgrade.  The only reason for the name change was to make the behavior clearer, and `.id()` is just an alias- so there's nothing to worry about in the mean time).

**Comment by ljacques** [comment]
Thanks @mikermcneil 
I keep testing ;-)
