### ISSUE TITLE
Lifting in production slows response

### ISSUE THREAD

**Issue by Boycce** [balderdashy/sails#3564]
Hey there, 
`sails lift --prod` seems to increase html requests to almost double in comparison to `sails lift`. I measured the difference through chrome devtools and noticed it was the *response time* that increased (180ms to 430ms). 

I seem to only detect this issue on my server with higher latencies. 

### Replicate issue

1. `sails new foo --no-frontend`
2. Inside `config/views`, turn layout to *false*
3. Create the folder `views` and place [homepage.txt](https://github.com/balderdashy/sails/files/124719/homepage.txt) inside.
4. Rename the file to `homepage.ejs`

**Comment by Boycce** [comment]
Ahh it's the `compress` [http middleware,](http://sailsjs.org/documentation/concepts/middleware/conventional-defaults) seems strange to have it on by default as you would need a decent amount of content on a webpage to benefit. Feel free to close.

**Comment by mikermcneil** [comment]
@Boycce thanks for the follow up!  For context, this originally came into core as a default because of https://github.com/balderdashy/sails/issues/1150 and http://inspiredjw.com/do-not-forget-to-use-gzip-for-express/  If you have any ideas about how to make the default support more appropriate, I'm all ears (just send it as a quick proposal if you don't mind)

**Comment by Boycce** [comment]
Hey @mikermcneil, yeah all cool I might look into it deeper after this project.
