### ISSUE TITLE
Grunt causes issues when clustering.

### ISSUE THREAD

**Issue by misterjt** [balderdashy/sails#3577]
```
Aborted due to warnings.
Running "clean:dev" (clean) task
Cleaning .tmp/public...ERROR
Warning: Unable to delete ".tmp/public" file (ENOENT: no such file or directory, rmdir '.tmp/public/admin/bower_components/iron-selector/test'). 
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/srv/smmtool/.tmp` ?
error: 
error:      If you think this might be the case, try running:
error:      sudo chown -R YOUR_COMPUTER_USER_NAME /srv/smmtool/.tmp
```
I think, the reason of problem is clustering. When i lift more than 1 process of sails in cluster mode, the first process removes .tmp directory. Second process triyng to do the same, but can not.

The problem appears only when i lift more than one process. 

How to solve it?

**Comment by Kallikrein** [comment]
I had problem with clustering at the orm level. I had de activated the grunt hook, so I don't know if my fix would apply.

I noticed that launching all the forks at once was causing 'race' issues (like db login, or maybe grunt)

Can you trigger forks one by one ? With pm2 it's something like 'scale' if I recall correctly.

I would also like to be able to cluster, it would be good to have a stable built in api.

**Comment by sgress454** [comment]
Hi @misterjt, thanks for posting.  You are correct in that the issue here is Grunt.  Each time your app lifts, Grunt attempts to process your app's assets (including compiling `.less` files) and copy them to a `.tmp` folder.  If multiple processes attempt to do this at once, they'll step on each-other's toes.  Similarly, as @Kallikrein stated, in certain situations (mainly when using `config/bootstrap.js` to create data, or when using the `migrate: alter` strategy), having multiple Sails apps connect to a database at once can cause issues.  

Here's some tips, which should make their way into the documentation (PRs to our docs are always welcome, by the way!):

 * When testing your clustering strategy, always have the apps start in the `production` environment, either by setting the `NODE_ENV` environment variable to "production" (the preferred way) or lifting with the `--prod` command-line argument.  This will best mimic your actual deployment environment.
 * Grunt tasks are bundled with Sails as a convenience, but if they're hindering your development, you can always change them or turn Grunt off entirely.  For example, you can comment out all of the subtasks in  `tasks/register/prod.js` to stop Grunt from running in the `production` environment:
```
module.exports = function(grunt) {
  grunt.registerTask('prod', [
//    'compileAssets',
//    'concat',
//    'uglify',
//    'cssmin',
//    'sails-linker:prodJs',
//    'sails-linker:prodStyles',
//    'sails-linker:devTpl',
//    'sails-linker:prodJsJade',
//    'sails-linker:prodStylesJade',
//   'sails-linker:devTplJade'
  ]);
};
```
or add `"hooks": {"grunt": false}` to your `.sailsrc` file to turn off the Grunt hook completely (though this will affect your development environment as well)
 * Once you've turned off Grunt for production environments, you can copy those subtasks into a new task (called `cluster` for example), which you call directly when starting your clustered server:
```
// In tasks/register/cluster.js
module.exports = function(grunt) {
  grunt.registerTask('cluster', [
    'compileAssets',
    'concat',
    'uglify',
    'cssmin',
    'sails-linker:prodJs',
    'sails-linker:prodStyles',
    'sails-linker:devTpl',
    'sails-linker:prodJsJade',
    'sails-linker:prodStylesJade',
    'sails-linker:devTplJade'
  ]);
};
```
and then start with something like `grunt cluster && pm2 start` (or however you start pm2).  This lets you still take advantage of the asset pipeline that Sails sets up for you, but it will only run once (before pm2) instead of once per Sails server.
 * Make sure to use `migrate: safe` when in the `production` environment (this is the default--just don't override it!)
 * If you have a `config/bootstrap.js` file that creates data, create a separate `config/env/production/bootstrap.js` file that will run in the `production` environment _without_ creating data.

**Comment by misterjt** [comment]
One more issue. Exactly the same condition, but with sockets.
```
A socket is being allowed to connect, but the session could not be loaded.  Will create an empty, one-time session to use for the life of the socket connection.  Details:
 Error: Session could not be loaded
    at _createError (/srv/smmtool/node_modules/sails/lib/hooks/session/index.js:271:21)
    at /srv/smmtool/node_modules/sails/lib/hooks/session/index.js:274:13
    at /srv/smmtool/node_modules/connect-redis/lib/connect-redis.js:93:25
    at try_callback (/srv/smmtool/node_modules/connect-redis/node_modules/redis/index.js:522:9)
    at RedisClient.return_reply (/srv/smmtool/node_modules/connect-redis/node_modules/redis/index.js:592:13)
    at RedisReplyParser.<anonymous> (/srv/smmtool/node_modules/connect-redis/node_modules/redis/index.js:265:14)
    at emitOne (events.js:77:13)
    at RedisReplyParser.emit (events.js:169:7)
    at RedisReplyParser.send_reply (/srv/smmtool/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:281:18)
    at RedisReplyParser.execute (/srv/smmtool/node_modules/connect-redis/node_modules/redis/lib/parser/javascript.js:188:26)
    at RedisClient.on_data (/srv/smmtool/node_modules/connect-redis/node_modules/redis/index.js:478:27)
    at Socket.<anonymous> (/srv/smmtool/node_modules/connect-redis/node_modules/redis/index.js:79:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20) { [Error: Session could not be loaded] code: 'E_SESSION' }
sails-hook-sockets :: connected to Sails admin message bus.
```

When i have 1 instance (even in cluster mode) of sails, everything works fine. When i start 2 instances (in cluster mode too), i got this problem.

This is my config 
```
/**
 * Production environment settings
 *
 * This file can include shared settings for a production environment,
 * such as API keys or remote database passwords.  If you're using
 * a version control solution for your Sails app, this file will
 * be committed to your repository unless you add it to your .gitignore
 * file.  If your repository will be publicly viewable, don't add
 * any private information to this file!
 *
 */

module.exports = {

	/***************************************************************************
	* Set the default database connection for models in the production        *
	* environment (see config/connections.js and config/models.js )           *
	***************************************************************************/

	models: {
		connection: 'MongoServer'
	},
	session:{
		adapter:'connect-redis'
	},
	sockets:{
		adapter:'socket.io-redis'
	},
	port:1337,
	host: '127.0.0.1',
	/***************************************************************************
	* Set the log level in production environment to "silent"                 *
	***************************************************************************/

	log: {
		level: "silly"
	}

};

```

**Comment by sgress454** [comment]
@misterjt are you using websockets as your only transport?  That is, do you have both the `transports` setting in `config/sockets.js`, and `io.sails.transports` in your client-side Javascript set to `['websocket']`?  If not, and if you don't have sticky sessions in your environment, then the initial connection made via polling may not reach the same server as the final handshake, leading to a socket with a mismatched session ID.  See [this note](http://sailsjs.org/documentation/concepts/deployment/scaling#?notes) in the documentation.  (We should probably add this to the "multi-server environments" page of the Realtime concepts section as well).

**Comment by Kallikrein** [comment]
@sgress454 
Could we implement a sails clustering hook, and maybe some health-check api ?

**Comment by sgress454** [comment]
@Kallikrein I am not entirely sure what you mean, but you are certainly welcome to [make a proposal!](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements).

@misterjt Your sockets issue sounds unrelated to this thread; please check out my previous comment and open a new issue if it doesn't help.

Added some [info to the docs](https://github.com/balderdashy/sails-docs/commit/dda1cc1886058d60eb1d63208291caa3dd1419f5#diff-91efd71854b4327fede12e1c87f367cf), so closing this.  Thanks everyone!

**Comment by crobinson42** [comment]
@Kallikrein 'clustering' is different for everyone. I use pm2 and other people use forever, nodemon, etc.. To perform clustering this would be different for each.

My current _**workaround**_ for production deployment & clustering [with pm2] is duplicating the grunt task "prod" to `tasks/register/production.js` and commenting out the tasks in the `prod.js`. This allows you to cluster in a more simple manner, ie: 

```
$ grunt production
   ...grunt running production build...
$ pm2 start app.js -i 4 --name "sails" -- --port 80
```

**Comment by Kallikrein** [comment]
@crobinson42 I do agree, but whatever the solution, the whole sails app is clustered.
It means that grunt tasks, database handshakes, and every custom hook etc. will be launched several times.

I personnaly use pm2 and apart from some docker issues, it's flawless for production.

To go further, I do distinguish two aspects : launch and listen.
While we don't want to cluster the launch (grunt, orm, ..), we do want to cluster the listen.

That's why I've started, a while ago, to dig into the 'listen' point and see how to cluster my app just before this event.
I failed miserably :) I'm still a beginner though.

@sgress454 Just as a synopsis, the idea is to allow sails to expose a built-in master/worker api. I think it's good to have a separation of route and concepts between what the master and the workers would be listening to / connecting to.
