### ISSUE TITLE
Proposal: change Grunt task to NPM scripts

### ISSUE THREAD

**Issue by manuelitox** [balderdashy/sails#3588]
Firstly, I want comment that I like Grunt. In fact, It was the first task manager that I used. Currently, I'm using Gulp. I think that both task managers are really good, but in SailsJS, to simply the process, I think it would be better make it directly with NPM scripts.

Later, If anyone wants use Grunt, Gulp, etc. You should only install it, without deleting the other task manager. 

I can support with this if that's okay for you.

Please, let me know your feedback.

FYI: [Why npm scripts?](https://css-tricks.com/why-npm-scripts/)

**Comment by mikermcneil** [comment]
Hi @manuelitox-  I'm interested to hear more about what you're envisioning.  As long as the standard Grunt integration was still easy to install and use, I wouldn't be opposed conceptually to something like this for Sails v1, since it would lighten the dependency load for Sails installs.  Would you mind closing this issue and [opening a pull request to ROADMAP.md](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements) that adds a one-line summary of this feature as an item on the backlog table?  I think the first step is to go into some more detail on how you're thinking this would work in that proposal PR (i.e. in GitHub's UI).  Doesn't have to be a complete spec all at once or anything-- just enough to gauge interest from the community, ensure coverage of all the important bits and work out any obvious conceptual kinks.  Look forward to reading what you come up with!
