### ISSUE TITLE
Possible that req._sails does not exist depending on configuration

### ISSUE THREAD

**Issue by lennym** [balderdashy/sails#3598]
I've been trying to debug an issue with the default response handlers (`negotiate`, `serverError` etc) not working, and have discovered that it's a result of depending on `req._sails` being heavily depended on in order to access sails.log.

The cause of this issue being that in our app we have disabled the request hook in order to prevent the parsing of `req.params.all()` since the repeated invocation of `_.cloneDeep` contained within the middleware to set that up caused catastrophic performance issues with moderately large json bodies (Context: response times went from > 2 minutes to < 10s when the hook was disabled).

Since `req._sails` is heavily depended on in a number of places, it would be helpful if it were not so easily lost when disabling hooks which are not required.

I'd propose looking to create a single hook for the creation of the `req._sails` property - and potentially any other properties which are potentially depended on in sails code (as opposed to users' code) - that is accompanied by a warning that sails itself may stop working if it is disabled. Alternatively, some method by which to disable the parsing for `req.params.all()` independently since it has such severe performance implications that its removal is likely to be necessary.

**Comment by lennym** [comment]
I've raised https://github.com/balderdashy/sails/pull/3599 because it seems this is pretty simple to resolve. In the meantime I can resolve by setting req._sails in my own custom middleware.

**Comment by sgress454** [comment]
Hi @lennym, it seems to me that the real issue here is the performance hit associated with `req.params.all`.  Moving the code that sets `req._sails` to another arbitrary place so that you can turn off the request hook is a bit of a kludge, whereas "some method by which to disable the parsing for req.params.all()" is a better idea, but still problematic since some code in core ([namely blueprints](https://github.com/balderdashy/sails/blob/61f6687870bc6dccf18784238b2d6a8b9fc2cd89/lib/hooks/blueprints/actionUtil.js#L218)) relies on `req.params.all()` (so we'd want a warning if that was turned off but blueprints were still active).  Ideally, we come up with a better implementation for `req.params.all()`.

**Comment by lennym** [comment]
I think there are two issues at hand here.

1) The request hook has become something of a dumping ground for functionality, and there's no way of doing fine-grained configuration on what aspects are wanted and what aspects are not.

2) req._sails is fundamentally required for other parts of the app to function, and so should be able to be relied on. Thus I moved it to a place where it would always be set, irrespective of configuration. This might be seen as arbitrary, and I'm open to suggestion about where it lives, but the important thing for me is that it's set reliably.

With respect to blueprints failing if req.params.all() is not present, then I'd agree that a warning makes sense - and indeed would make sense in other places where there are interdependent hooks which are not encapsulated (though I would advocate for encapsulation where possible).

As for a better implementation of req.params.all() - I certainly agree since the current implementation is not great in terms of performance, but I don't know anything at all of the use cases for it since I don't use it (and in fact have disabled it).

**Comment by mikermcneil** [comment]
> 1) The request hook has become something of a dumping ground for functionality, and there's no way of doing fine-grained configuration on what aspects are wanted and what aspects are not.

Completely agree.  It probably makes sense to collapse it into core.  It's really only a hook because I wanted to group as much functionality as possible into hooks for easier maintenance.  For the short term, it's worth pointing out in the docs that the request hook really shouldn't be overridden. (btw @lennym @sgress454 if you guys can think of a place that should go in the docs, please add a note.)

That said, there's the open problem:

> repeated invocation of _.cloneDeep

I think the right solution here is probably a getter (it's what socket.io did for a couple of similar cases).  That way, the performance hit is only relevant if you're actually using `req.allParams()`.  I'll take a quick look.

**Comment by mikermcneil** [comment]
> I think the right solution here is probably a getter

Welp, I was wrong:  https://github.com/balderdashy/sails/blob/master/lib/hooks/request/params.all.js#L16

That said, it looks like this could be easily optimized by simply waiting to build the actual set of combined parameters until `req.allParams()` is actually called.

**Comment by mikermcneil** [comment]
@lennym would you mind giving trying out [`sails@90b5ccdc5177190fff35eac9acf77763c1836b51`](https://github.com/balderdashy/sails/commit/90b5ccdc5177190fff35eac9acf77763c1836b51) as a sanity check? Unless you see any issues w/ that, I believe that will improve performance of the request hook dramatically in the general case.  The performance of actions that repeatedly call `.allParams()` will suffer somewhat, but that's a small price to pay for the overall improvements.

(As for the other topics discussed in this thread, let's pick those up in a separate thread-- just want to make sure and get to the bottom of allParams first)

**Comment by lennym** [comment]
Thanks @mikermcneil - I'm not 100% sure what you're asking me to look at in that commit. It seems to be related to logging and deprecation warnings (although unrelatedly I welcome the removal of connect-flash) rather than any change to allParams behaviour?

Unless you were just referring to the documentation updates w.r.t. cross dependencies between hooks? If so then it looks good to me. I would possibly welcome some kind of defence against disabling dependent hooks in code. For example, in my case, if I try to run the `responses` hook without also having run the `request` hook then I should expect to see an error on startup since the responses will not be available. It's undoubtedly a good thing to have the dependencies listed in documentation, but it puts the burden on the user to have completely consumed the documentation to find possible gotchas before configuring an application. Throwing an error or warning like "You have disabled hook 'request', which is required for the hook 'responses'".

Furthermore, I think the task of fully identifying which hooks are dependent on other hooks and ensuring all are enabled will identify some of the places where the cross dependencies don't necessarily make a lot of sense. For example, here we have a number of things (blueprints, responses) which are dependent on request, which in turn looks like it is probably dependent on sessions (courtesy of connect-flash).

Meanwhile, since it is the case that "the request hook really shouldn't be overwritten" then I'd return to the original intention of my issue/PR, which is to identify what aspects of the request hook are such that they should never be overwritten and separate them from those which are optional.

**Comment by lennym** [comment]
I realised that the better solution to my issue of "responses depend on request" is to break that dependency by ensuring that the `responses` hook also sets `req._sails` since then the dependency is entirely satisfied internally. Hence https://github.com/balderdashy/sails/pull/3615

Hopefully this feels like less of a kludge to you @sgress454 ?

**Comment by sgress454** [comment]
@lennym I think @mikermcneil maybe meant to have you look at https://github.com/balderdashy/sails/commit/5f24fb3284928c8ad70cb8880e9fa8cbc8dcef41, which refactors `req.params.all()` to work on-demand?  Looks good to me, except that for backwards-compatibility (and performance) we should probably only calculate the result once and cache it.

**Comment by lennym** [comment]
Ahh yes, that makes a lot more sense. It certainly looks good from my perspective in that it's not going to be doing huge amounts of computation by default. I can't speak for any effect it might have on the behaviour though, since I've disabled all of this in my implementation so don't really have much idea what it's supposed to do.

**Comment by mikermcneil** [comment]
aghh my bad, @leedm777.  @sgress454 is right.

> except that for backwards-compatibility (and performance) 

@sgress454 I don't see any compatibility issues offhand-- are there any you're thinking about in particular? Gave it some thought, and unless I'm missing something, I believe this would only be _less_ efficient if you were calling `req.allParams()` at least several times in the same action, which would be unusual.

**Comment by mikermcneil** [comment]
@sgress454, @lennym unless y'all have any other concerns, going with what's on master for the next patch release (0.12.2).  :fireworks:

**Comment by sgress454** [comment]
@mikermcneil Sorry, missed your last message.  As far as compatibility, it's the same issue as efficiency, as you mentioned: if called several times in the same request, it would a) run all the code again and b) possibly give different results, if `req.body` had been altered.  You shouldn't be altering `req.body` anyway, but the fact remains that before this change, `req.params.all()` would have returned the same result every time you called it, and now it wouldn't.  As far as calling `req.params.all()` more than once--it would be odd to do that in a single action, but between policies and `require()`d files (like good ol' `actionUtil`), it could totally happen.  I don't really see a downside to cacheing the result, since it would only stay in memory as long as the request.
