### ISSUE TITLE
SailsJS not using sockets.js origins attribute

### ISSUE THREAD

**Issue by supericeboy** [balderdashy/sails#3603]
In sockets.js I have

`origins: "localhost:1337"`

After startup in the sails console I check if it is applied:

```
sails> sails.io.origins()
'*:*'
```

If I force it via bootstrap.js it works fine.

bootstrap.js

```
if(sails.config.sockets.origins) {
        sails.io.set('origins', sails.config.sockets.origins);
}
```

Sails Console:

```
sails> sails.io.origins()
'localhost:1337'
```

**Comment by sgress454** [comment]
@supericeboy is it documented somewhere that you can put an `origins` property in `config/sockets.js`?

**Comment by sgress454** [comment]
Also, is the `origins` setting for socket.io documented anywhere?

**Comment by supericeboy** [comment]
[](https://github.com/socketio/socket.io#serveroriginsvstringserver)

Also the other options like transport are identical to the socket.io setting.

Here is makes it seem like we can uncomment this and use it
[](https://github.com/balderdashy/sails-hook-sockets/blob/master/lib/defaults.js#L218)

**Comment by sgress454** [comment]
Excellent, thank you.  It looks like the `origins` value is just not making it into the Socket.io instance [with the other options](https://github.com/balderdashy/sails-hook-sockets/blob/master/lib/initialize.js#L63-L95).  Would you mind posting an issue (or better yet, a pull request that adds the config in the right spot)  in the [sails-hook-sockets](https://github.com/balderdashy/sails-hook-sockets) repo with a link back here, and then closing this issue?

**Comment by supericeboy** [comment]
https://github.com/balderdashy/sails-hook-sockets/pull/23

**Comment by mikermcneil** [comment]
@supericeboy thank you!  @sgress454 is working on this for Sails v1 w/ the help of your PR.  Re: https://github.com/balderdashy/sails-hook-sockets/pull/23,  based on what we've seen so far playing w/ it, looks like we need to take a few additional things into account (and that's what [this validator](https://github.com/balderdashy/sails/blob/master/lib/util/check-origin-url.js) is about, since we can use the same logic in the new security hook in sails v1)
