### ISSUE TITLE
NPM preinstall script can cause install issues (`lib/preinstall_npmcheck.js`)

### ISSUE THREAD

**Issue by markelog** [balderdashy/sails#3674]
**Sails version**: 0.12.1
**Node version**: 5.9.1
**NPM version**: 3.7.3
**Operating system**: mac

<hr/>

### Rationale

1. [Package install scripts vulnerability](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability)
2. It causes some weird issues like http://stackoverflow.com/questions/30252935/error-installing-sails-in-windows-7, i also experience related issue, on ubuntu, it causes `npm i` to exit with '1' code, without any error message, so i can't even debug it or create meaningful ticket :/
3. This script in the first place was introduced to [work](https://github.com/balderdashy/sails/pull/1742) with npm 1.2, which i don't believe is used anymore, so there is no reason to maintain it.

**Comment by sgress454** [comment]
Hi @markelog.  As to your first point, the vulnerability you linked to only applies to malicious packages.  So far, Sails is still considered benevolent :wink:.  And I wish i could believe NPM 1.2 wasn't used anymore, but, I've learned to leave such wishful thinking aside while working through these issues.  But your second point is valid, so we'd be much more inclined to fix this script to work on Windows than drop it entirely.  

You've made this post as a proposal, not as bug report, so it really should be done as a PR.  If you'd like to update it to put some details as to the problem on Windows, we can leave it here.  Otherwise, I'd [check out the contribution guide for proposals](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#submitting-a-proposal), close this, and open a pull request.

**Comment by markelog** [comment]
> Hi @markelog. As to your first point, the vulnerability you linked to only applies to malicious packages.

Yeah, but many already requesting for npm to make `ignore-scripts` by default, it was meant to point out current direction of the community. So many developers will enable this feature already.

> And I wish i could believe NPM 1.2 wasn't used anymore, but, I've learned to leave such wishful thinking aside while working through these issues

npm 1.2 is equivalent to node .8, you don't [support](https://github.com/balderdashy/sails/blob/7b6e786d67285f4578f9ffa2f641baadbcc1c595/.travis.yml#L4) this environment.

> so we'd be much more inclined to fix this script to work on Windows than drop it entirely.

I don't know how you would, it just has exit code '1', nothing to add there. 

> You've made this post as a proposal, not as bug report

This neither, not a proposal nor a bug or both "Proposal to remove this bug". I'm not sure i understand what you mean by those terms and how you differentiate.

In any case, if you want to maintain this for some reason, feel free to close this.

Gotta say, you have veeeery complicated contribution guide, with some many rules with so many things to read and comprehend, like in rails repo they don't make you jump through so many hoops.

**Comment by mikermcneil** [comment]
@markelog 

> 1. Package install scripts vulnerability
>
> many already requesting for npm to make ignore-scripts by default, it was meant to point out current direction of the community. So many developers will enable this feature already.

I think that in this case it would be fine, since if scripts are ignored, that means that folks are using a new version of NPM, so the preinstall NPM version check won't be relevant for them anyways, right?  And if NPM ignores scripts by default, it's the same situation since that would be a new version of NPM.

All that said, I'm not disagreeing with you-- the preinstall script is definitely a bit weird. Makes me feel funny.


> 2. It causes some weird issues like http://stackoverflow.com/questions/30252935/error-installing-sails-in-windows-7, i also experience related issue, on ubuntu, it causes npm i to exit with '1' code, without any error message, so i can't even debug it or create meaningful ticket :/

Appreciate you taking the time to mention that-- Scott and I are using Mac OS X (and linux on the server), so we rely on this kind of info to know when something goes wrong on Windows.  I'd say avoiding errors on Windows far outweighs the importance of backwards compatibility for old versions of NPM.


> 3. This script in the first place was introduced to work with npm 1.2, which i don't believe is used anymore, so there is no reason to maintain it.

You make a great point about Node v0.8.

**Comment by mikermcneil** [comment]
@markelog I totally get this is kind of a murky area since this is an install issue as much as anything else.  Where Scott's coming from is that the original issue subject line and body is phrased like a proposal; i.e. suggesting a change in Sails ("remove preinstall")  vs. pointing out a bug ("fails to install on windows or when a certain flag is set").

We ask for proposals to be sent as PRs primarily for the sake of compartmentalization.  It keeps our issues focused on actionable bugs (i.e. flaws with documented features) rather than things that would might have multiple right answers (like adding features, changing usage, and basically everything else that's not in the docs).  This lets the community as a whole be more efficient when it comes to working through issues. 

What I'll do for now is make an edit to the subject line here to track the install issues.  But at this point I'm 100% down to merge a patch that removes the preinstall script and dumps it off the side of a cliff.

**Comment by mikermcneil** [comment]
@markelog @sgress454 all right this is removed on `master`

**Comment by mikermcneil** [comment]
@markelog Alright- last bit of this was removed in https://github.com/balderdashy/sails/commit/ba85568e51a0895b40b1a87d265aab9e6c8b79a9

So expect no more preinstall check in Sails v1.0 later this year.  I'll wait to close this issue until we publish that.

**Comment by moos** [comment]
What's the interim solution?  It's odd that the default install command `npm install -g sails` so prominently displayed everywhere doesn't work (for some ppl.) -- and this hasn't been addressed since March!

node v6.7.0
npm 3.10.6
mac 10.10.5

Note: running with `--ignore-scripts` removes the pre-install issue, however I'm still getting:
```
$ sails
module.js:457
    throw err;
    ^

Error: Cannot find module './_commander'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/bin/sails:9:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by sgress454** [comment]
🎉This was incorporated into the official 1.0 release.
