### ISSUE TITLE
Anatomy docs+generated config incorrectly claim `sails.config.http.cache` expects seconds (instead of milliseconds)  [Originally: HTTP Cache gets truncated to three digits (999 second max)]

### ISSUE THREAD

**Issue by BigstickCarpet** [balderdashy/sails#3692]
**Sails version**:  0.11.5
**Node version**: 5.1.0
**NPM version**: 3.8.3
**Operating system**: OS X El Capitan

<hr/>

The `sails.config.http.cache` setting appears to be getting truncated to three digits.   For example, if I set the cache timeout to 604800 seconds (one week), Sails actually sets the `Cache-Control` header to `max-age=604` (~10 minutes). Because of this, the longest cache timeout that Sails will allow is 999 seconds (~16 minutes).

**Comment by mikermcneil** [comment]
@BigstickCarpet Thanks!  I'll take a look asap.

**Comment by mikermcneil** [comment]
@BigstickCarpet Ah- should have realized this right away, apologies:

`sails.config.http.cache` is the [number of ms](http://sailsjs.org/documentation/reference/configuration/sails-config-http) that static assets are cached.

Here's the relevant test in core to explain what I mean:
https://github.com/balderdashy/sails/blob/v0.12.3/test/integration/middleware.static.test.js#L110

That doesn't necessarily rule out there being some other problem, but hopefully this is just a documentation issue.  So in the example here, `604800` means 604800 miliseconds, or ~604 seconds.  Also, that test file didn't exist yet in v0.11.5, so it's possible there is an unrelated issue going on-- keep me posted if you suspect there's something unrelated at work.


re: docs:
The [generated comments in new sails apps](https://github.com/balderdashy/sails-generate-backend/blob/v0.12.6/templates/config/http.js#L83) _and_ the [anatomy page](https://github.com/balderdashy/sails-docs/blob/e22c5e2c792d1c415318079876e6964e6329dd41/anatomy/myApp/config/http.js.md) are definitely both wrong (they say "seconds" instead of "milliseconds").

**Comment by mikermcneil** [comment]
Fixes to anatomy docs and frontend generator are pushed to GitHub (will leave this issue open until a patch of the generator is published to NPM and the updated docs are deployed to sailsjs.org)

**Comment by mikermcneil** [comment]
@BigstickCarpet Wow.  Time flies!  Sorry about that-- this was fixed a very long time ago, I just forgot to come back.  Anyway, I double-checked just to be sure I'm not crazy: http://sailsjs.com/documentation/anatomy/my-app/config/http-js

BTW: as of Summer 2016, we started redeploying the Sails website from the docs on a weekly basis (approximately Monday afternoons or evenings, CDT).  So in the future, we can just go ahead and close issues related to the docs like these (here or in the docs repo) soon as they're patched on master (cc @rachaelshaw @jub3i @brettimus @jdcauley @irlnathan @sgress454 @particlebanana )
