### ISSUE TITLE
Sails socket request not working for some browsers

### ISSUE THREAD

**Issue by ycpatel813** [balderdashy/sails#3769]
**Sails version**:0.12.3
**Node version**:v4.4.4
**NPM version**:2.15.1
**Operating system**:Window 7

<hr/>

Hi all,

I have used sails web socket to call all APIs, In development its working fine but when i use it in production it works in some browsers but in some client its not calling socket request and just showing loading.
i have debugged in chrome network its seems WS request is giving 101 status as shown in image.

I think it is firewall issue when i stop firewall its working fine so any suggestion to resolve this firewall related issue.

Please review it 
![sails error](https://cloud.githubusercontent.com/assets/8921044/16220491/d7ffde0c-37aa-11e6-80d6-638b176e6021.png)

**Comment by RWOverdijk** [comment]
A 101 is normal, that's not the problem. It just means that your initial http request has been upgraded to a websocket connection (changing protocol).

I think you should check the frames, see what communication is happening over the connection, the problem is most likely in your app.

**Comment by sgress454** [comment]
Hi @ycpatel813, unfortunately there's not really enough info here to point to anything in the Sails core.  If you can make a repo with steps to reproduce this in a reliable way, we can take a look.  If as you suggest the issue is with a firewall, it's a bit beyond the scope of this forum, but if we come across any suggestions we'll try and post back here!  In the meantime, a good ol' Google search for "socket.io firewall issues" is probably a good place to start...
