### ISSUE TITLE
lodash global not exposed in sails console

### ISSUE THREAD

**Issue by nstCactus** [balderdashy/sails#3795]
**Sails version**: 0.12.3
**Node version**: 6.3.0
**NPM version**: 3.10.3
**Operating system**: OS X El Capitan 10.11.5

<hr/>

No matter what I do, I can't get sails to expose its lodash instance.

Steps to reproduce:

1. `sails new lodash-issue && cd lodash-issue`
1. `sails console` (without editing any file)
1. In the console:
    1. `sails.config.global`  
returns: `{adapters: true, models: true, services: true }` 
    1. `typeof lodash`  
returns: `'undefined'`
    1. `typeof _`  
returns: `'undefined'`
    1. `typeof _` again  
returns: `'string'`
    1. `typeof async`  
Works as expected by dumping the async object

I get the same result if I edit my _config/globals.js_ file as follow:

```
module.exports.globals = {
  sails:    true,
  models:   true,
  services: true,
  _:        true,
  async:    true,
};
```

**Comment by mikermcneil** [comment]
@nstCactus I've noticed this with the Node REPL in general-- if memory serves, it's something to do with the `_` variable. 

Supposedly it's been improved in Node v6.0: http://stackoverflow.com/a/17073313/486547  Because of that, I'm a little hesitant to make any changes to core to resolve this one way or the other (in case that behavior changes again).

But at the very least, I'll make sure this is mentioned in the documentation for `sails console`.  As a workaround, I'd recommend either use `require('lodash')` (if you have it installed in your app as a dependency- just make sure you're on `^3.10.0`)  or add code inside your bootstrap function (in `config/bootstrap.js`) that exposes lodash under a different name.

**Comment by mikermcneil** [comment]
So I took a look, and luckily there's a note about this in the docs already: http://sailsjs.org/documentation/reference/command-line-interface/sails-console#?global-variables-in-sails-console

There, it actually recommends another workaround: `sails.util._`  I double-checked, and this is pinned [to the same version of lodash](https://github.com/balderdashy/sails-util/blob/master/package.json#L24) as in Sails (the most recent 3.x: `3.10.2`), so you'll be good to go!

I'll update the docs to include a mention of the behavior in Node v6.0, and improve the example a bit.

**Comment by mikermcneil** [comment]
Updated docs: https://github.com/balderdashy/sails-docs/commit/23662a37cc1f8169d79a1e7f925bb7f4433475bf

**Comment by mikermcneil** [comment]
@nstCactus Hope that helps!  And sorry for the confusion.  I went ahead and closed this, but if you think of any way we can make this easier to find in the docs, please [send a PR](https://github.com/balderdashy/sails-docs)!
