### ISSUE TITLE
Generate tool works not as expected if i use path with name

### ISSUE THREAD

**Issue by 1001v** [balderdashy/sails#3826]
**Sails version**: 0.12.4
**Node version**: 6.4.0
**NPM version**: 3.10.6
**Operating system**: Manjaro Linux Xfce 

<hr/>
Hello. I think there's the problem with generating such things as controllers and models. I probably used undocumented feature of tool, but there's still a bug anyway. 
When i generate new controller, it's expected that it's name would be Pascal-cased. If i try generate controller like this: sails generate controller api/test, the generator creates directory api as expected, but this directory would be Pascal-cased, while controller's name wouldn't. So executing:
`sails generate controller api/test`
i get this file:
`sailsapp/api/controllers/Api/testController.js`
but not this one as expected:
`sailsapp/api/controllers/api/TestController.js`
I believe, that's a bug.
Thank you.

**Comment by sgress454** [comment]
Hi @1001v, thanks for posting.  The controller will still work if generated this way, since its internal identity is lowercased, but you're right that this isn't what is expected.  I'd normally ask you to re-post this in the [sails-generate-controller repo](https://github.com/balderdashy/sails-generate-controller), but that might get lost for all time, so we'll just keep this in here.  But if you wanted to post a PR in that repo that fixes it (and post back here that you did so), I'd gladly merge!

**Comment by 1001v** [comment]
@sgress454, hi, thanks for answer. [I created a PR](https://github.com/balderdashy/sails-generate-controller/pull/4). If it's good to go, i'm ready to provide the same fix to sails-generate-model, as well as complete documentation with this generate case.

**Comment by mikermcneil** [comment]
Hey @1001v, just did a quick review if you'd check that out.  Thank you!

**Comment by mikermcneil** [comment]
see https://github.com/balderdashy/sails-generate/commit/42da2751af6d1f7a27fb59d1df5f44a718b80064
