### ISSUE TITLE
[documentation] uppercase vs. lowercase in blueprint (shadow) routes

### ISSUE THREAD

**Issue by devendra1102** [balderdashy/sails#3853]
**Sails version**: 0.12.3
**Node version**:v4.2.6
**NPM version**:3.10.2
**Operating system**:Ubuntu 16.04

I have made an api `UserTransactions` using `sails generate api UserTransactions`. So there is automatically generated the restful routes. So all routes  should be like `/userTransactions`. But when I call `/usertransactions` ('T' is small)then also it works. I think it should not work

<hr/>

**Comment by svenvarkel** [comment]
Most likely the reason here is that internally Sails uses lowercase identificators for models, controllers and services.

**Comment by mikermcneil** [comment]
Hey @devendra1102 -- like @svenvarkel suggested, this is caused by the fact that we use lowercase identifiers.  In Sails v1, all blueprint routes will be exposed as lowercase -- and if you want to match uppercase letters, you can route to those blueprint actions using explicit routes in your routes.js file
