### ISSUE TITLE
blueprint find() with ?id=[]1&id[]=2 acts as a findOne()

### ISSUE THREAD

**Issue by cyrilchapon** [balderdashy/sails#3870]
**Sails version**: 0.12.17
**Node version**: 6.9.1
**NPM version**: 3.10.8
**Operating system**: Windows 10

<hr/>

When a collection has only **one element** persisted (say it has `id` set to _1_), running a `GET /element?id=1&id=2` on the collection acts like a `findOne()` returns an **object** ( `{id: 1, ...}` ) whereas it should return an array ( `[ {id: 1, ...} ]` ).

The trouble here is that the url is thus inconsistent as it returns an **object** OR an **array** depending on how many items we have in database.

Plus, if you try the same thing with another field, like `GET /element?name[]=test&name[]=test2`, this does return an array as expected. Make the url even more inconsistent.

Tested only with `sails-mysql` adaper

**Comment by mikermcneil** [comment]
@cyrilchapon You bring up some good points here.

+ I agree that it feels inconsistent that when you hit `http://blueprint-api.example.sailsjs.org/chat?id=1` you get a 200 and a single record (or a 404 response and nothing) rather than always getting a 200 with a JSON array containing exactly one record.
+ When multiple filters are used, e.g. `http://blueprint-api.example.sailsjs.org/chat?content=Yo%20what%27s%20up%20everybody??&content=I%20can%27t%20find%20the%20button!` the behavior seems right to me (that is, that it treats the same-named params like an IN query- so responds w/ records that match _any_ of the matching things).  And if you do `?foo=3&foo=4&bar=2`, it also works like I would expect:  you get records where `foo` is _either_ 3 or 4, _and_ `bar` is 2.  BUT, that does get inconsistent as soon as `id` comes into the picture.  When you do `http://blueprint-api.example.sailsjs.org/chat?id=1&content=foo&content=bar`, even if the content doesn't match, you get the dictionary again, and the rest of the filters are ignored.  (the id takes precedence).

Would you say that sums it up?

--

If so, here's the way I'd suggest tackling it:

1. If the "findOne" RESTful blueprint route matches (e.g. `/chat/:id`), then we always route to the findOne action.  Additional criteria is _never_ supported for the `findOne` blueprint action-- just lookup by `id`.
2. Otherwise, if the "find" RESTful blueprint route matches (e.g. `/chat`), then we _never_ call the findOne blueprint action, and instead, always call the `find` blueprint action.
3. We concrete-ify the "find" shortcut blueprint route so that it does not match `chat/find/:id` -- instead it will now only match `/chat/find` (same thing for the other blueprint routes)

Making these changes in v0.12 would be a breaking change, so I can't do that.  But I'm definitely down to include them in Sails v1 later this year.

Please let me know if you see anything I missed.  Thanks!

**Comment by cyrilchapon** [comment]
> Would you say that sums it up?

Perfectly. Pardon my bad English btw 😃.

In addition, I hadn't catched that `404` on unexisting id with `?id[]=12` or even `?id=12`. If that's indeed the case, well I would add that this `404` seems to be as inconsistent as the *single-result return*. IMHO it should return an empty collection just like `?name[]=pouet`

But anyways, this would be fulfilled with your proposed solution, which looks basically the perfect behavior one would except, I guess !

Btw we ❤️ sails in here.

**Comment by mikermcneil** [comment]
@cyrilchapon good to hear!  We'll plan on getting this in place asap (I believe https://github.com/balderdashy/sails/blob/954408d99b6468f8b9a96c1b7435e3e6a6209672/lib/hooks/blueprints/actions/find.js#L25-L31 is the culprit, mostly)

**Comment by cyrilchapon** [comment]
Found workaround :

use syntax with explicit "`where`"
```
GET /element?where={"id":[1,2]}
```

**Comment by sgress454** [comment]
🎉This was incorporated into the official 1.0 release.
