### ISSUE TITLE
Success callback for Model.message()

### ISSUE THREAD

**Issue by dominiksteiner** [balderdashy/sails#3891]
**Sails version**:0.12.4
**Node version**:6.7.0
**NPM version**:3.10.8
**Operating system**:Mac OSX

<hr/>
Is there a way to add a success callback to the User.message(data) call?

Similar to how it is described here

http://stackoverflow.com/questions/13549734/success-callback-for-emit-method-in-socket-io

but from server to client. So on server side I do

User.message(someData)

and on the client

socket.on('user', function(){
// do something
});

When the client has received the message the server should get notified, so perhaps something like this

User.message(someData, function() {
// success callback - message has been delivered
}, function(error) {
// error callback - message has not been delivered
})

P.S. I created first the same issue also on https://github.com/balderdashy/sails-hook-sockets/issues/32, but as pubsub.js is inside the sails lib opening the ticket here

**Comment by mikermcneil** [comment]
@dominiksteiner Thanks for bringing this up!  To the best of my knowledge, there is no "ack" for socket broadcasts-- at least not that can be safely relied upon in a multi-node (i.e. one-of-many-servers-behind-a-load-balancer) world.  (see http://socket.io/docs/server-api/#server#emit)

This would probably be achievable for single-recipient broadcasts (where you use a socket id, not a room name), but it would have to live on top of Socket.io.  I agree it'd be nice to have a core way of doing a delivery guarantee...  But rather than RPS, the place to tackle that would be in [`sails.sockets.broadcast`](http://sailsjs.org/documentation/reference/web-sockets/sails-sockets/broadcast).  I'd def be open to figuring something like that, just needs a bit more research to figure out the best way to do it first.  (And I think we should use a different method name for it-- e.g. `sails.sockets.reverseRequest(someSocketId, { whatever: ['data', 'you want'] }, function (err, optionalJsonSerializableData) {  })`)


>Minor aside:  Just to give you a heads up:  In Sails v1 (which will be released before the end of the year), we're [changing `message()`](http://sailsjs.com/roadmap).  So instead, you'll be able to use [`.publish()`](http://next.sailsjs.org/documentation/reference/web-sockets/resourceful-pub-sub/publish), which is very similar, except slightly lower level in that it doesn't mess with the format of the message you send out standardize will have the callback.  There'll be more on that in the migration guide when it comes time to upgrade-- just wanted to let you know in advance.

_cc @sgress454_

**Comment by dominiksteiner** [comment]
Thanks @mikermcneil for the quick response.

For our use case we wouldn't be able to use publish() as we want to notify all connected sockets of an another incoming server request, so the req object wouldn't be the one triggered from the sockets. So if message() is going away what would be the alternative?

broadcast() looks like a better fit, so if I use the session id as the room name it would do the same thing as message()?

**Comment by mikermcneil** [comment]
@dominiksteiner Cool!  Yeah, I'd say since this API is in flux, at the moment I'd probably recommend `sails.sockets.broadcast()`.  You can use that to address a room or an individual socket (just use the socket id as the room name).

Something that might be helpful to keep in mind: Behind the scenes, all that `.publish()`/`.message()` are really doing is wrapping `sails.sockets.broadcast()` (and building up a dynamic room name for each record, using the specified record id).  Similarly, `.subscribe()` does the same thing for `sails.sockets.join()`.  And `.unsubscribe()` does it for `sails.sockets.leave()`

**Comment by mikermcneil** [comment]
@dominiksteiner here are some recent updates I did to the RPS docs which might also be helpful: https://github.com/balderdashy/sails-docs/commit/8b53f402ec8cbbd2d621b4b4896c7011b5ee8d93?diff=unified

**Comment by dominiksteiner** [comment]
@mikermcneil thanks for the clarification, I will play with broadcast() and see what can be done there.
