### ISSUE TITLE
`sails.config.blueprints.populate` setting not obeyed by "create" endpoint

### ISSUE THREAD

**Issue by remzr7** [balderdashy/sails#3899]
**Sails version**: 12.0
**Node version**: 7.1.0
**NPM version**: 4.0.2
**Operating system**: 10.12

<hr/>

When using blueprints and setting populate to true on associations are not populated. I'm not sure why this is happening.

This issue is always reproducible and has been reported before by #3375

**Comment by mikermcneil** [comment]
@remzr7 thanks for posting.  To clarify, is this re: the "create" blueprint action?

**Comment by sgress454** [comment]
To follow up:  it was confirmed that the behavior for the `create` blueprint is in Sails v0.12.x is inconsistent with that of the other blueprints in that it doesn't automatically populate the response.  This is fixed in 1.0, but decided not to back-port to v0.12 b/c it could be considered a breaking change.

**Comment by sgress454** [comment]
🎉This was incorporated into the official 1.0 release.
