### ISSUE TITLE
deploy sails use pm2 problem

### ISSUE THREAD

**Issue by cage1618** [balderdashy/sails#3935]
**Sails version**:0.12.11
**Node version**:6.9.2
**NPM version**:3.9.3
**Operating system**:centos x86_64

<hr/>

I use pm2 depoly my sails app, I want to reload the app when code changed. Now the process was restarted but views change not work. How can I resolve this issue? thanks

**Comment by cage1618** [comment]
![image](https://cloud.githubusercontent.com/assets/2541448/21414018/c07bcaee-c836-11e6-872d-89dff3954958.png)

this is my pm2 config file

**Comment by mr47** [comment]
@cage1618 Did you try to set`watch: true` ? Also this is bad practice, better to use pm2.keymetrics.io/docs/usage/deployment/ or you can try to use this https://github.com/Dalas/pm2-webhook

**Comment by richdunajewski** [comment]
I think I noticed that views are cached now and require a restart of the process to update. I think they were loaded on-the-fly before, so you could make a change to the source and refresh the browser to see the update immediately.

Did this change recently? Should be much better for performance reasons as we're not reading a file on each render.

**Comment by sgress454** [comment]
Thanks @cage1618 for reaching out, and thanks @mr47, @richdunajewski and @WittBulter for your suggestions.

I'm going to go ahead and close this because this forum is intended for reporting bugs in the Sails core.  For support for questions of this nature (including professional support), please see http://sailsjs.com/support.
