### ISSUE TITLE
Unexpected wrong req.params in controller

### ISSUE THREAD

**Issue by saintgeo23** [balderdashy/sails#3974]
**Sails version**: 0.12.3
**Node version**: 7.5.0 (we use n)
**NPM version**: 4.1.2
**Operating system**: macOS Sierra v.10.12

<hr/>
Hello!

Every day we get a few visitors (approximately 0.0023%) that meet error when exploring our website.
We catch this error in Graylog and it seems that the reason is that Sails pushes wrong req.params.

For example
We have route in routes.js
```
'/fun/:id': 'Fun.index'
```
But when user goes to `https://ourwebsite.com/fun/SZMppLEJ3?gallery=tag&query=autoloader`
in FunController index method he gets req.params.id equal to
```
 SZMppLEJ3?gallery=tag&query=autoloader
```

**Comment by sgress454** [comment]
Hi @saintgeo23, that is strange indeed.  My guess would be that for some reason, for some users, the URL is getting URI-encoded to be like:

```
/fun/SZMppLEJ3%3Fgallery%3Dtag%26query%3Dautoloader
```

so that the entire string, including the query, is being read in as the `id` param.  This would probably be happening client-side, but I can't really say for sure.

We haven't seen anything like this before, so I don't think it's a Sails or Express issue, but if you get any more info that points in that direction please do post back here!
