### ISSUE TITLE
sails-postgresql: "invalid input syntax for type XXX" with postgresql

### ISSUE THREAD

**Issue by tobernguyen** [balderdashy/sails#3993]
**Sails version**: 1.0.0-22
**Node version**: 6.6.0
**NPM version**: 3.10.8
**Operating system**: OS X 10.11.6

<hr/>

In my model file `api/models/Attendance.js:
```
...
attributes: {
    date: { type: 'string', columnType: 'date' },
    startTime: { type: 'string', columnType: 'time' },
    endTime: { type: 'string', columnType: 'time' },

    user: {
      model: 'user'
    }
  }
...
```

In controller:
```
...
Attendance.create({
  user: user.id,
  date: moment().format("YYYY-MM-DD"),
  startTime: moment().format("h:mm:ss")
}).exec(err => {
  sails.log(err)
});
...
```

The above `create` command will return error: 
```
AdapterError: Unexpected error from database adapter: invalid input syntax for type time: ""
```

I have tried for different `columnType` including: timetz, timestamp, timestamptz. And all of them have same error: `invalid input syntax for type XXXX: ""`.
It seems that the adapter passed **blank value** to postgres-orm.

**My dependencies**
```
  "dependencies": {
    "async": "2.0.1",
    "connect-redis": "^3.2.0",
    "consolidate": "^0.14.5",
    "grunt": "1.0.1",
    "lodash": "3.10.1",
    "moment-timezone": "^0.5.11",
    "passport": "^0.3.2",
    "passport-slack": "0.0.7",
    "pug": "^2.0.0-beta11",
    "sails": "^1.0.0-22",
    "sails-disk": "^0.10.10",
    "sails-hook-autoreload": "^0.13.2",
    "sails-hook-grunt": "^1.0.4",
    "sails-hook-orm": "^2.0.0-12",
    "sails-hook-sockets": "^1.0.1",
    "sails-postgresql": "1.0.0-8"
  }
```

**Comment by sgress454** [comment]
Hi @tobernguyen, the issue here is that the `string` attribute type defaults to `''` (empty string), which isn't a valid value for the column types you're using.  So in your `create` statement, since you're not supplying `endTime`, it's trying to set that to `''` and causing the error.

If you install the latest Sails beta and `sails-postgresql` v1.0.0-9, you'll be able to change this behavior by adding `allowNull` to your attribute definitions:

```
attributes: {
    date: { type: 'string', allowNull: true, columnType: 'date' },
    startTime: { type: 'string', allowNull: true, columnType: 'time' },
    endTime: { type: 'string', allowNull: true, columnType: 'time' },

    user: {
      model: 'user'
    }
  }
```

This will change the base value of `date`, `startTime` and `endTime` to `null` instead of `''`, while retaining the validations of the `string` type.
