### ISSUE TITLE
Inconsistent API for .stream()

### ISSUE THREAD

**Issue by sgress454** [balderdashy/sails#4010]
_From @catdad on June 29, 2016 20:13_

Guys, why is the `stream` method constantly broken? It keeps trying to use variables that don't exist.

In the latest NPM version, 0.11.4, it is trying to use [`new Query`](https://github.com/balderdashy/sails-postgresql/blob/v0.11.4/lib/adapter.js#L1016), which does not exist. It was removed and this method didn't get updated.

In the latest version in GitHub, it is trying to read the variable [`api_version`](https://github.com/balderdashy/sails-postgresql/blob/f0c92f5d2ca6d654d520034c90a90562e3b5fb6c/lib/adapter.js#L1205), which is never being declared in the `stream` function... I think this was code copied from the `find` function.

Are there no unit tests for this stuff? Does the code never get linted? Why is this method always broken? Is there any version where it actually does work?

_Copied from original issue: balderdashy/sails-postgresql#253_

**Comment by sgress454** [comment]
_From @sailsbot on June 29, 2016 20:13_

@catdad Thanks for posting, we'll take a look as soon as possible.  In the meantime, if you haven’t already, please carefully read the [issue contribution guidelines](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions) and double-check for any missing information above.  In particular, please ensure that this issue is about a stability or performance bug with a  documented feature; and make sure you’ve included detailed instructions on how to reproduce the bug from a clean install.   Finally, don’t forget to include the version of Node.js you tested with, as well as your version of Sails or Waterline, and of any relevant standalone adapters/generators/hooks.

Thank you!

**Comment by sgress454** [comment]
_From @sailsbot on July 30, 2016 23:1_

@catdad,@sailsbot: Hello, I'm a repo bot-- nice to meet you!

It has been 30 days since there have been any updates or new comments on this page.  If this issue has been resolved, feel free to disregard the rest of this message and simply close the issue if possible.  On the other hand, if you are still waiting on a patch, please post a comment to keep the thread alive (with any new information you can provide).

If no further activity occurs on this thread within the next 3 days, the issue will automatically be closed.

Thanks so much for your help!

**Comment by sgress454** [comment]
_From @catdad on July 30, 2016 23:7_

Hello Sails Robot,

Yes, this is a real bug, and it is a particularly bad bug. While the sails team has been very slow at even commenting on these issues, let alone accepting completely working PRs legitimate problems, closing a bug such as this would be very bad. You should not do that.

Best,
Kiril, friend of robots

**Comment by sgress454** [comment]
_From @sailsbot on August 30, 2016 23:0_

@catdad,@sailsbot: Hello, I'm a repo bot-- nice to meet you!

It has been 30 days since there have been any updates or new comments on this page.  If this issue has been resolved, feel free to disregard the rest of this message and simply close the issue if possible.  On the other hand, if you are still waiting on a patch, please post a comment to keep the thread alive (with any new information you can provide).

If no further activity occurs on this thread within the next 3 days, the issue will automatically be closed.

Thanks so much for your help!

**Comment by sgress454** [comment]
_From @catdad on August 30, 2016 23:7_

Hello Sails Robot,

I am beginning to think that this is a sign that this lib should not be used.

Never the less, this is a bug that needs to be addressed.

Best,
Kiril

**Comment by sgress454** [comment]
_From @sailsbot on September 30, 2016 23:0_

@catdad,@sailsbot: Hello, I'm a repo bot-- nice to meet you!

It has been 30 days since there have been any updates or new comments on this page.  If this issue has been resolved, feel free to disregard the rest of this message and simply close the issue if possible.  On the other hand, if you are still waiting on a patch, please post a comment to keep the thread alive (with any new information you can provide).

If no further activity occurs on this thread within the next 3 days, the issue will automatically be closed.

Thanks so much for your help!

**Comment by sgress454** [comment]
_From @catdad on September 30, 2016 23:2_

Oh, sailsbot...

**Comment by sgress454** [comment]
_From @d3viant0ne on October 6, 2016 15:48_

Sailsbot needs to simmer down

**Comment by sgress454** [comment]
_From @sailsbot on November 6, 2016 23:0_

@catdad,@sailsbot,@d3viant0ne: Hello, I'm a repo bot-- nice to meet you!

It has been 30 days since there have been any updates or new comments on this page.  If this issue has been resolved, feel free to disregard the rest of this message and simply close the issue if possible.  On the other hand, if you are still waiting on a patch, please post a comment to keep the thread alive (with any new information you can provide).

If no further activity occurs on this thread within the next 3 days, the issue will automatically be closed.

Thanks so much for your help!

**Comment by sgress454** [comment]
_From @d3viant0ne on November 6, 2016 23:17_

@sailsbot - this issue needs an answer. How about you go spam the maintainers and not the users seeking guidance

**Comment by sgress454** [comment]
_From @particlebanana on November 7, 2016 18:13_

Yes `stream` isn't well maintained and had a weird interface to start with. It was hacked on in an early version of Sails for a specific use case.

Working on getting Waterline `0.13` out the door which will remove this from the adapter and move it up into Waterline where it should be anyway as well as documenting the interface fully.

I added the "bug" label so the bot will leave this alone.

**Comment by sgress454** [comment]
_From @d3viant0ne on November 7, 2016 19:17_

@particlebanana - Thanks :)

**Comment by sgress454** [comment]
The `.stream()` method is officially supported in the 1.0 version of the adapter, and documented for all core adapters in the Sails 1.0 docs: https://github.com/balderdashy/sails-docs/blob/1.0/reference/waterline/models/stream.md.

**Comment by catdad** [comment]
This seems like a really bad way to support streams. I've done testing in both mongo and postgress before, and the actual streaming capabilities of both databases are much faster than doing individual queries and paging for data. Sure, it provides a convenient way to support an API without having to implement it in all individual adapters, but it completely misses all the performance gains of using streams.

**Comment by particlebanana** [comment]
@catdad it's impossible to have a consistent api method for this when all the underlying adapters and drivers are completely different and keeping them in sync wasn't working. If you want to use something like [pg-query-stream](https://github.com/brianc/node-pg-query-stream) for performance it's now easier to do in Waterline 0.13 and you can still use the ORM's connection leasing.

**Comment by luislobo** [comment]
I agree with what @particlebanana mentioned, about this being really hard to make this work flawlessly for every adapter.
With the new Waterline version, you will have access to their corresponding driver, thus, being able to actually do native stuff more easily, and implement each adapter particular behavior.

**Comment by catdad** [comment]
Sorry, insanely late response. This approach kind of defeats the purpose of an ORM.

Currently, I use waterline to provide access to multiple databases in my application. I do this by accepting a bit of config, having a single `if` statement that correctly configures waterline with the user-selected database, and then writing a bunch of code all throughout the app that interacts with waterline, not caring at all which database it is actually talking to. Basically, classic ORM stuff.

With the above proposal, I would now have to care all throughout my code which database is being used in order to "do native stuff". But that's the one job of an ORM.

Also, why should "providing consistent behavior" not be the concern of tests? There are already tests that ensure the behavior of several plugin methods. Adding `stream` to that list would ensure that anyone implementing it in an adapter will do so correctly. Then, waterline itself can only provide the paged data wrapper if the adapter has not provided a `stream` method. Why would that be really hard to do?

**Comment by mikermcneil** [comment]
The biggest advantage of Sails v1's `.stream()` method over using `.find()` (and the reason I wrote it in the first place) has always been that it allows you to set a finite ceiling on RAM usage in your application, and provides you a simple way of performing mass data migration, map/reduce etc.  I originally used low-level database support to do this, but the paging approach we use now accomplishes the same thing.

> I've done testing in both mongo and postgress before, and the actual streaming capabilities of both databases are much faster than doing individual queries and paging for data. 

Hey @catdad, thanks for chiming in!  I'm open to discussing ways to bring native-level streaming back, but I'd like to discuss that from the context of a small set of concrete benchmarks outlining the performance gains (either in latency, or as far as scalability via either a metric of CPU cycles or RAM usage).

If there is a significant difference, then it makes sense to me to work towards bringing back support for this via the classic `stream` adapter method  (regardless, the higher-level interface shouldn't need to change).

If, on the other hand, your concern is more about the userland interface (i.e. not wanting to have to migrate a bunch of your existing code that was relying on getting access to a node Stream instance), I understand that too.  It'd be a bit of a different solution, but I'd be happy to kick some ideas around on that front.  Either way, I think it's best to focus on one of those two lines of reasoning at a time (otherwise it's a little too much to keep in one's head, imo)

**Comment by sgress454** [comment]
Closing this now that v1.0 (and its `.stream()` functionality) is officially released.
