### ISSUE TITLE
FEATURE REQUEST: Introduce Formatters to print JSON responses

### ISSUE THREAD

**Issue by mrded** [balderdashy/sails#4049]
**Sails version**: 1.0.0
**Node version**: 7.7.3
**NPM version**: 4.1.2
**Operating system**: macOS 10.12.3 (16D32)

<hr/>

I was thinking about modern MVCs. Nowadays these frameworks are mainly used for providing REST.

That means that they're not MVC anymore, because there are no **V**iews.

Why don't we introduce something like **Formatters** instead of **Views**? It is the same idea, but it will define how to build a JSON.

We use to have `.toJSON()` function, unfortunately it was very limited and deprecated now. Currently we have to define how to return an object in the Controller. It's usually very messy.

Not always you can print an object the same way as it's written in the model. You may need to load some additional data before you print it, and frontend may also require different format of fields.

Forum is a good example. To print `ForumModel` you need to load and calculate how many related topics are inside, how many of them are new, etc.

That code to build one single forum object, can be quite big and messy, especially if you need to reuse it. or print it slightly different (full, teaser).

I think it make sense to move it out of controller, and organise somehow.

---

Formatter will have defined methods how to print an object.

It can be organised as following:
```
api
`-- formatters
    `-- model
         |-- teaser.js
         `-- full.js
```

And to print an object in needed format you will need to do something like this:

```
findOne: function(req, res) {
  Model.findOne(req.param('id')).then(function(object) {
    return res.ok(Formatter(object, 'full'));
  });
}
```

What do you think about that?

**Comment by luislobo** [comment]
I like the idea, but you don't need to change the framework to do that, right? I think you can just implement it as a node module, and use it.

**Comment by mrded** [comment]
Currently I made a service. I can probably wrap it into npm module.

**Comment by luislobo** [comment]
That would be a great idea, I can see some use of it in our projects.

**Comment by sgress454** [comment]
Hi @mrded, this is really interesting.  As @luislobo said this is a great idea for a _companion_ to the framework, rather than an _addition_, but I look forward to seeing where you take it.  You could definitely create a hook that would load formatters from `api/formatters` and publish your hook to NPM.

Another idea of how to go about this sort of thing would be to create custom responses, so instead of using `res.ok()` you would do `res.outputSomeModel()`.  You can [put custom responses in `api/responses`](http://sailsjs.com/documentation/concepts/custom-responses/adding-a-custom-response) and then call them from any controller.  

At some point we'll probably be updating our README / website to feature some community hooks, so let us know how this goes!

**Comment by mrded** [comment]
I initiated a NPM package here https://www.npmjs.com/package/sails-formatter

I'll really appreciate if you can review it and update a description.

Thanks.

**Comment by mrded** [comment]
@sgress454 I really like you suggestion with creating a hook to load formatters from `api/formatters`. Let's see what can I do with it. Thanks!
