### ISSUE TITLE
I have problems with combobox + postgresql and realtime

### ISSUE THREAD

**Issue by david-arzola** [balderdashy/sails#4250]
hello all friend, I have problems with combobox + postgresql and realtime

** not lib **
 react,  angular

** Bootstrap **
Bootstrap v3.3.7

**Sails version**:
sails -v 0.12.14

**Node version**:
node-v8.8.1-linux-x64

**NPM version**:

**DB adapter name**: N/A
sails-postgresql

**DB adapter version**: N/A
sails-postgresql:  0.11.4

**Operating system**:
centos 6.x

**Comment by sgress454** [comment]
Hi @david-arzola! This forum is for reporting bugs in the Sails core or its related projects. In the future, please direct support requests to our [live chat](gitter.im/balderdashy/sails), [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [StackOverflow](http://stackoverflow.com).  

---

We don't maintain combobox, so I'm not sure how much help we can be here, but if you think the issue is related to a bug in Sails itself, please re-open this and post some code or, better yet, a link to a repo we can use to reproduce the problem!
