### ISSUE TITLE
npm install sails-mysql Error: spawn ENOENT

### ISSUE THREAD

**Issue by Mantish** [balderdashy/sails#6766]
Hi, I'm getting an error when trying to install the module.
I think it has something to do with one of the dependencies.

Here's the error log:

npm http GET https://registry.npmjs.org/sails-mysql
npm http 304 https://registry.npmjs.org/sails-mysql
npm WARN git config --get remote.origin.url returned wrong result (git://githu
b.com/felixge/node-mysql.git) undefined
npm WARN git config --get remote.origin.url returned wrong result (git://githu
b.com/felixge/node-mysql.git) undefined
npm http GET https://registry.npmjs.org/underscore/1.4.3
npm http GET https://registry.npmjs.org/underscore.string/2.3.1
npm ERR! git clone git://github.com/felixge/node-mysql.git undefined
npm ERR! git clone git://github.com/felixge/node-mysql.git undefined
npm ERR! Error: spawn ENOENT
npm ERR! at errnoException (child_process.js:977:11)
npm ERR! at Process.ChildProcess._handle.onexit (child_process.js:768:34)
npm ERR! If you need help, you may report this log at:
npm ERR! http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR! npm-@googlegroups.com

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\n
pm-cli.js" "install" "sails-mysql"
npm ERR! cwd D:\nodejs\node_modules\sails
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm http 304 https://registry.npmjs.org/underscore.string/2.3.1
npm http 304 https://registry.npmjs.org/underscore/1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! D:\nodejs\node_modules\sails\npm-debug.log
npm ERR! not ok code 0

**Comment by KrinalPatel11** [comment]
NOTE: This error is almost always caused because the command does not exist, because the working directory does not exist, or from a windows-only bug. I found a particular easy way to get the idea of the root cause of:

Error: spawn ENOENT
The problem of this error is, there is really little information in the error message to tell you where the call site is, i.e. which executable/command is not found, especially when you have a large code base where there are a lot of spawn calls. I found a very easy way to spot which command cause the problem rather than adding event listeners everywhere in your code as suggested in @laconbass’ answer. The key idea is to wrap the original spawn call with a wrapper which prints the arguments send to the spawn call. Here is the wrapper function, put it at the top of the index.js or whatever your server’s starting script.

(function() {
var childProcess = require("child_process");
var oldSpawn = childProcess.spawn;
function mySpawn() {
console.log('spawn called');
console.log(arguments);
var result = oldSpawn.apply(this, arguments);
return result;
}
childProcess.spawn = mySpawn;
})();

Full Answer With Ex. [Here](https://icetutor.com/question/how-do-i-debug-error-spawn-enoent-on-node-js/)
