### ISSUE TITLE
How I can set title or app name for sails application?

### ISSUE THREAD

**Issue by TheFinestArtist** [balderdashy/sails#768]
I'm kind of new to web development and I found sails is cool framework for node.js.

How I can set title or app name for sails application?

Help me..thanks.

**Comment by harishmb** [comment]
how to give the title for every ejs file

**Comment by SpaceG** [comment]
Creating New App Name instead of "sudo sails lift" how run other commandline to lift the app?

How give a app NAME instzead of "sudo sails lift"???!!! own app Name or commandline??? Please!!!?

and how to run the new commandline like this example below?

config/bootstrap.js:


<code>
module.exports.bootstrap = function (cb) {

  // simple override some config settings
  sails.config.appName = "My overriden name";

  // It's very important to trigger this callack method when you are finished
  // with the bootstrap!  (otherwise your server will never lift, since it's waiting on the bootstrap)
  cb();
};

</code>

**Comment by felipemullen** [comment]
@SpaceG why would you want to change the command line for "sails lift"? this is part of the sails cli.

If you want to run your server without sails, you can run "node app.js" from the location of your app.js file. This is also documented in the app.js file itself
