### ISSUE TITLE
How does sails.js scale in multiple-core server and across servers with cluster

### ISSUE THREAD

**Issue by tonychenc** [balderdashy/sails#849]
I saw this issue #170, which discussed about it.

But I didn't find any doc about how to customize sails.js to support cluster?

**Comment by aaronjhoffman** [comment]
@uhho - the nginx configuration is no longer available above, can you share here? And is nginx required to make it work? 

I have my sails app running in docker with ECS and using the ALB (application load balancer). It doesn't seem to make much sense that I would have to include nginx in the mix but currently having trouble with socket.io which is why I'm asking.

Thanks in advance,
Aaron
