### ISSUE TITLE
Sails.js Nested Folders For Controllers, Models, and Views

### ISSUE THREAD

**Issue by abbaabbbaabbbbbaa** [balderdashy/sails#876]
Please do so, that you can create subfolders in the folder 'controllers'. Example: api / controllers / tools / mails, api / controllers / tools / configs, api / controllers / tools / drivers. Where 'mails', 'configs', 'drivers' - is a controllers!

**Comment by diosney** [comment]
@mikermcneil 

No offended :smile: 

Sorry for the very very late reply. I have to catch up with the updates since I moved on other projects, so I don't know exactly what is the status on this specific matter. (I don't wan)

No problem, I can understand your feeling but I think that a reasonable example is not needed here, just look at how the other frameworks have evolved to note that this is a reasonable and needed feature.

In my specific case, I had to build two large apps that needed to be extremely modular, with this I mean that the modules nesting was very deep due its nature, and having all related files contained in her own level and module helped a lot, I mean a lot, when plugin and unplug-in modules.

If at that time if sailsjs had this feature, I certainly had used it instead of plain expressjs.

I know maybe this is not the standard and common apps everyone builds, but indeed is a very useful feature that will bring several users to the framework.

Thanks

**Comment by etiennegauthier** [comment]
I got a use case if anyone is interested. We are considering starting using sails as our main entry point for administration of everything. So in real terms, we will end up using sails on 3,4 maybe one day 10-15 databases/projects. I believe in our case, it is totally fair to expect having project organized in sub folders. Is there any workarounds ?

**Comment by msqz** [comment]
You may access model (which exists in subdirectory)
`yourapp/api/models/yourmodule/SomeModel.js`
from controller (which also exists in subdirectory)
`yourapp/api/controllers/yourmodule/SomeModelController.js`
by using
`var SomeModel = sails.models['yourmodule/someorder'];`
`SomeModel.find()... whatever`
instead of just
`SomeModel.find()... whatever`
in the controller actions

**Comment by sgress454** [comment]
@msqz That's not quite correct.  Currently Sails flattens the Models directory tree, but doesn't include folder names in the model identity.  So a model saved in `yourapp/api/models/yourmodule/SomeModel.js` would be accessed in Sails with (for example) `SomeModel.find()`.  See #3515 for an ongoing discussion of nested models/controllers.
