### ISSUE TITLE
Controller method gets fired twice on request

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#889]
I create a new model

```
sails generate account
```

I add a util method to AccountController

```
sendMail: function(req, res, next){

}
```

For some reason this method is fired twice when I do a post request to /account/sendMail. The first request is of type OPTION and the second POST (which is correct). Why does it fire a OPTION request??

**Comment by sakujo** [comment]
I know it's an old post, but i have the same problem. I have latest sails 0.12.1. Im using ionic / angular as frontend and using the ngResource module of angular. When i use create method of my controller (sails side), my chrome console shows me the requests OPTION and POST too. POST fails after 4 mins and OPTION has a status code 200 very quick. Even though one fails, i've 2 events created at the end and both are shown in frontend (which shouldn't be). I ve allRoutes set true and origin set *. I checked on clientside that im calling the function once.

**Comment by sgress454** [comment]
@sakujo Yes, please open a new issue if you think you are experiencing the same problem.  In this case you'll want to create a repo that reproduces the problem (instructions will be displayed when you create the issue).

If you're having a _second_ issue, please make a separate post for that, rather than posting two problems in the same issue.  Thanks!

**Comment by Kihansi95** [comment]
hello, I met the same problem, and I think that I found where it occur in my project. When the findOne() called, the request will me made twice to that action. Maybe some experienced can make a pull request for this problem
