### ISSUE TITLE
Replace Socket.io with Primus

### ISSUE THREAD

**Issue by alejandroiglesias** [balderdashy/sails#945]
Hi, i would like to suggest replacing Socket.io with [Primus](https://github.com/primus/primus), which is "a simple abstraction around real-time frameworks" and "allows you to easily switch between different frameworks without any code changes". It supports Engine.IO, WebSockets, BrowserChannel, SockJS and Socket.IO as transports or "transformers" as they call them.
### Advantages
1. Effortless switching between real-time frameworks by changing one single line of code. No more API rewrites needed when your project requirements change, the framework get abandoned or simply breaks down.
2. Build-in reconnect, it just works. The reconnect is controlled by an randomized exponential backoff algorithm to reduce server stress.
3. Offline detection, Primus is smart enough to detect when a users drop their internet connection (switching WIFI points/cell towers for example) and reconnects when they are back online.
4. Automatically encodes and decodes messages using custom parsers. Can be easily switched for binary encoding for example.
5. A clean and stream compatible interface for the client and server. You can just stream#pipe data around. In addition to that, the client works on Node.js as well, write once, run it everywhere.
6. Fixes various of bugs in the supported frameworks and additions stability patches to improve real-time communication.
7. Comes with an amazing plugin interface to keep the core library as fast and lean as possible while still allowing the server and the client to be extended.
8. Last but not least, Primus is build with love, passion and dedication to the real-time web.
### Main motivation

The main motivation to ask you to switch to Primus is that i want to use SockJS instead of Socket.io as i don't trust too much on the latter.

[There are very solid arguments](http://xsnippet.org/359042/) from [sockjs-tornado](https://github.com/mrjoes/sockjs-tornado) developer.
And from Primus developer:

> There are small bugs in Engine.IO that are causing our tests to fail. I've submitted patches for these bugs, but they have been reject for silly reasons. The bug causes closed connections to say open. If you're experiencing this you can apply this patch.

(Engine.IO and Socket.IO are developed by the same guy and seems that Socket.IO will use Engine.IO internally in the coming versions.)

So based on all those arguments i think that Sails will benefit too from having a more solid transport and it would be great to use Primus to be able to select your preferred transport and/or take advantage of their optimizations.

**Yes, i'm willing to help, but can't be done on my own as i don't know lots of things regarding the internals of Sails.**

Cheers.

**Comment by andyhu** [comment]
+1

**Comment by mikermcneil** [comment]
@alejandroiglesias @andyhu Hey guys! So I talked to @3rdeden about this almost a year ago when we were both at jsconf.it and I decided to focus on socket.io 1.0 first if that was available, since @rauchg has done such an incredible job there, and particularly w/ engine.io.

Socket.io v1.0 support is included in Sails v0.11 (currently available via `sudo npm install -g sails@beta`)  The sockets hook is also now implemented as [a separate repo](http://github.com/balderdashy/sails-hook-sockets) so making an override for it is as simple as releasing the hook on npm and instructing others to run, e.g. `npm install sails-hook-sockets-primus` (and setting the appropriate properties in your hook-- see [new docs](https://github.com/balderdashy/sails-docs/tree/v0.11/concepts/extending-sails/Hooks) on the subject in the v0.11 branch of sails-docs)

**Comment by mikermcneil** [comment]
updated roadmap: https://github.com/balderdashy/sails/commit/9ee19516e54fdf330c760cce1e0aa1d998be234a

**Comment by andyhu** [comment]
Thanks for the reply. I changed my mind a bit on voting this. Since I saw a benchmark amount all common libraries like socket.io, socksjs, engine.io, Primus etc..(Sorry I couldn't find the link again now). with socket.io it performs not too bad compares to others  (except engine.io which is a lower level thing behind socket.io) in term of maximum connection concurrency, CPU & memory utilization etc.. And since Primus tries to wrap everything around so it a bit more resources. Also I saw in the change log of Socket.io 1.0, some of the long existed memory leak issues have been fixed which one of my friends said that it's the reason stopped them from using it on a non-trivial real communication site. So I did rethink about what benefit it will bring us when change it to Primus, since socket.io covers almost all possible transportation layers.
